// The interaction feedback rows for the credits call sites (see interactionFeedback.catalog.ts for what a row says).
import { type FeedbackRow, row } from './row';

// prettier-ignore
export const creditsFeedback: Record<string, FeedbackRow> = {
  // Credits (audiobook-credits-templates.prd.md, Phase 1)
  'src/components/settings/DeliveryProfilesPanel.tsx::deliveryProfiles#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Settings > Delivery loads the profiles and the choices; an inline error otherwise.'),
  'src/components/settings/DeliveryProfilesPanel.tsx::deliverySelectProfile#1': row('input', 'file-io', 'disabled', 'disabled', 'toast', 'toast', 'yes', 'ok', 'Choosing a profile saves it at once (the project manifest, or the Global default); the select is off until the host answers, a toast names the profile now judging, and a refusal is an error toast in the host words.'),
  'src/components/settings/DeliveryProfilesPanel.tsx::deliveryDuplicateProfile#1': row('click', 'file-io', 'disabled', 'disabled', 'dialog', 'toast', 'yes', 'ok', 'Duplicate makes a custom copy and opens it in the editor, with a toast naming it; the buttons are off until the host answers, and a failure is an error toast.'),
  'src/components/settings/DeliveryProfilesPanel.tsx::deliveryProfiles#2': row('click', 'file-io', 'disabled', 'disabled', 'ui', 'toast', 'na', 'ok', 'After a duplicate, the list is read again so the copy is in it; a failure is the same error toast.'),
  'src/components/settings/DeliveryProfilesPanel.tsx::deliverySaveProfile#1': row('click', 'file-io', 'pending', 'pending', 'toast', 'inline', 'yes', 'ok', 'Save profile is busy while the host writes delivery-profiles.json; the editor closes with a toast naming the new revision, and a refusal stays in the editor as an inline alert in the host words.'),
  'src/components/settings/DeliveryProfilesPanel.tsx::deliveryProfiles#3': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'na', 'ok', 'After a save, the list is read again so the new revision shows; a failure is the same inline alert in the editor.'),
  'src/components/settings/DeliveryProfilesPanel.tsx::deliveryDeleteProfile#1': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'yes', 'ok', 'Delete asks first (ConfirmDialog, ADR 0075), stays busy until the host answers, then a toast; a refusal (a built-in) is an error toast.'),
  'src/components/settings/CreditsPanel.tsx::creditsTemplates#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The template library load; an inline error banner otherwise.'),
  'src/components/settings/CreditsPanel.tsx::creditsProjectValues#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The project values and manuscript-seeded suggestions load; an inline error banner otherwise.'),
  'src/components/settings/CreditsPanel.tsx::creditsPreview#1': row('effect', 'instant', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'A background preview refresh on every body/value change; a failed render just falls back to "Nothing to preview yet." rather than a toast per keystroke, and the fields it was rendering from stay visible and correct.'),
  'src/components/settings/CreditsPanel.tsx::creditsChapterAnnouncements#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The chapter announcement preview for the first chapter (Phase 5); a failure (no manuscript yet) says why in the preview box instead of a toast per keystroke.'),
  'src/components/settings/RetailSamplePanel.tsx::manuscriptChapters#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The chapters and lines the sample is picked from; a failure is an inline alert in the Retail sample section.'),
  'src/components/settings/RetailSamplePanel.tsx::creditsRetailSample#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The saved sample, or why it cannot be shown; a failure is an inline alert.'),
  'src/components/settings/RetailSamplePanel.tsx::saveCreditsRetailSample#1': row('click', 'file-io', 'disabled', 'disabled', 'toast', 'inline', 'na', 'ok', 'Save sample and Clear sample disable while busy; a range over 5 minutes is refused with its length as an inline alert and the previous sample is kept (Phase 5, C10).'),
  'src/components/settings/CreditsPanel.tsx::saveCreditsTemplate#1': row('click', 'file-io', 'disabled', 'disabled', 'toast', 'toast', 'na', 'ok', 'Save template disables while busy (and its own pending look) and cannot fire twice; a failure is a toast and the draft stays editable to retry.'),
  'src/components/settings/CreditsPanel.tsx::duplicateCreditsTemplate#1': row('click', 'file-io', 'disabled', 'disabled', 'toast', 'toast', 'na', 'ok', 'Duplicate disables while busy and cannot fire twice; a failure is a toast.'),
  'src/components/settings/CreditsPanel.tsx::deleteCreditsTemplate#1': row('click', 'file-io', 'disabled', 'disabled', 'toast', 'toast', 'na', 'ok', 'Delete disables while busy and cannot fire twice; a failure is a toast, and the template stays in the library to retry.'),
  'src/components/settings/CreditsPanel.tsx::saveCreditsProjectValues#1': row('input', 'file-io', 'disabled', 'disabled', 'ui', 'toast', 'na', 'ok', "Saves on every change to a project value field (never blocks on an unresolved token, C6); the field being saved disables until it ends, so a second edit cannot race the first, and a failure is a toast while the typed value stays on screen."),

  // "Set up the credits" (credits-token-setup-and-front-matter-detection.prd.md, Phase 2, ADR 0208)
  'src/components/home/Home.tsx::creditsSetupState#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Only decides whether the "Set up the credits" dialog shows; a failed read leaves it absent for this load, same as guideEntities.'),
  'src/components/credits/CreditsSetupDialog.tsx::saveSettings#1': row('click', 'file-io', 'disabled', 'disabled', 'ui', 'toast', 'na', 'ok', 'Inside Save, only when "Use for all my projects" is checked: the whole dialog is busy/disabled until both this and creditsSetupSave finish, and a failure of either is one toast leaving every field editable to retry.'),
  'src/components/credits/CreditsSetupDialog.tsx::creditsSetupSave#1': row('click', 'file-io', 'disabled', 'disabled', 'ui', 'toast', 'na', 'ok', 'Save: fields disable while busy; the dialog closes once the host answers "not needed any more" and a failure is a toast with every typed value kept on screen to retry.'),
  'src/components/credits/CreditsSetupDialog.tsx::creditsSetupDismiss#1': row('click', 'instant', 'disabled', 'disabled', 'ui', 'toast', 'na', 'ok', '"Not now": the dialog closes for this session once the host confirms; a failure is a toast and the dialog stays open to retry.'),
  'src/components/credits/CreditsSetupDialog.tsx::creditsSetupDismiss#2': row('click', 'instant', 'disabled', 'disabled', 'ui', 'toast', 'na', 'ok', '"Don\'t ask for this project": same as "Not now", stored on the manifest instead of the session.'),
  'src/components/credits/CreditsSetupBanner.tsx::creditsSetupDismiss#1': row('click', 'instant', 'disabled', 'disabled', 'ui', 'toast', 'na', 'ok', 'The banner\'s own "Don\'t ask for this project" (Phase 3): the banner disappears once the host confirms; a failure is a toast and it stays.'),
  'src/components/manuscript/Manuscript.tsx::creditsSetupState#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Only decides whether the credits-setup banner and the credits cards\' Fill in button show; a failed read leaves both absent, same as creditsTemplates on this page.'),
};
