// The interaction feedback rows for the delivery call sites (see interactionFeedback.catalog.ts for what a row says).
import { type FeedbackRow, row } from './row';

// prettier-ignore
export const deliveryFeedback: Record<string, FeedbackRow> = {
  // Delivery (diagnostics-delivery-and-cleanup-tools.prd.md, Phase 5)
  'src/components/delivery/DeliveryPage.tsx::measureState#1': row('mount', 'instant', 'na', 'na', 'ui', 'inline', 'yes', 'ok', 'On opening Delivery: the last measurement the host kept is shown again, and one still running is followed with its progress; a failed read is an inline alert in the Measurements panel.'),
  'src/components/delivery/DeliveryPage.tsx::deliveryProfiles#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Reads the delivery profile the project is judged against, for the profile panel; when it cannot be read the panel says so inline. The measurement itself carries the profile that judged it, so the table never depends on this read.'),
  'src/components/delivery/DeliveryPage.tsx::measureState#2': row('timer', 'instant', 'inline', 'disabled', 'poll', 'inline', 'yes', 'ok', 'Polls every 500 ms while the measurement runs: the bar is the share of the bytes read (ADR 0015) and each file row says whether it waits, is being measured or is done; the end is also a job:ended toast (ADR 0076).'),
  'src/components/delivery/DeliveryPage.tsx::measurePickFiles#1': row('click', 'os-dialog', 'pending', 'pending', 'ui', 'inline', 'na', 'ok', 'Choose files to measure is busy while the operating system picker is open; closing it without a choice does nothing. A failure is an inline alert in the Measurements panel.'),
  'src/components/delivery/DeliveryPage.tsx::measureAnalyze#1': row('click', 'job', 'pending', 'host', 'poll', 'inline', 'yes', 'ok', 'Starts the measurement of the picked files with the same button still busy, then the panel shows its progress and the button is off until it ends; a refusal (a path not picked, too many files, one already running) is an inline alert in the host words.'),
  'src/components/delivery/DeliveryPage.tsx::measureCancel#1': row('click', 'instant', 'inline', 'none', 'ui', 'inline', 'yes', 'ok', 'Cancel stops the measurement; files already measured keep their results and the rest say they were not measured. A failed request is an inline alert.'),
  'src/components/delivery/BookChecklistPanel.tsx::creditsTemplates#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Loads the credits templates for the "In this project" bonus line under acx.credits; a failed load just leaves that line out, since the rule\'s own "not checked by the app" status already shows and this is only a bonus fact under it.'),
  'src/components/delivery/BookChecklistPanel.tsx::creditsRetailSample#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Reads the retail sample for the "In this project" bonus line under acx.retail_sample; a failed load just leaves that line out, since the rule\'s own "not checked by the app" status already shows and this is only a bonus fact under it.'),
  // Delivery, Diagnostics tab (diagnostics-delivery-and-cleanup-tools.prd.md Phase 6)
  'src/components/delivery/DiagnosticsTab.tsx::diagnosticsState#1': row('mount', 'instant', 'na', 'na', 'ui', 'inline', 'yes', 'ok', 'On opening the Diagnostics tab: the thresholds a check uses and the last check the host kept, or one still running followed with its progress; a failed read is an inline alert in the Diagnostics panel.'),
  'src/components/delivery/DiagnosticsTab.tsx::diagnosticsState#2': row('timer', 'instant', 'inline', 'disabled', 'poll', 'inline', 'yes', 'ok', 'Polls every 500 ms while the check runs: the bar is the share of the bytes read (ADR 0015) and each file row says whether it waits, is being checked or is done; the end is also a job:ended toast (ADR 0076).'),
  'src/components/delivery/DiagnosticsTab.tsx::measurePickFiles#1': row('click', 'os-dialog', 'pending', 'pending', 'ui', 'inline', 'na', 'ok', 'Choose files to check is busy while the operating system picker is open; closing it without a choice does nothing. A failure is an inline alert in the Diagnostics panel.'),
  'src/components/delivery/DiagnosticsTab.tsx::diagnosticsAnalyze#1': row('click', 'job', 'pending', 'host', 'poll', 'inline', 'yes', 'ok', 'Starts the check of the picked or measured files with the same button still busy, then the panel shows its progress and both buttons and the source-kind choice are off until it ends; a refusal (a path not picked, an unknown source kind, one already running) is an inline alert in the host words.'),
  'src/components/delivery/DiagnosticsTab.tsx::diagnosticsCancel#1': row('click', 'instant', 'inline', 'none', 'ui', 'inline', 'yes', 'ok', 'Cancel stops the check; files already checked keep their findings and the rest say they were not checked. A failed request is an inline alert.'),
  // Delivery, the report export (diagnostics-delivery-and-cleanup-tools.prd.md Phase 7)
  'src/components/delivery/ReportExportPanel.tsx::deliveryExportReport#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'na', 'ok', 'Export report is busy while the host writes the two files, and off while a measurement runs; the panel then names the files written and what the report counts. A refusal (no project, a job running, nothing measured) or a write failure is an inline alert in the host words, and nothing is written.'),

};
