// The interaction feedback rows for the editing call sites (see interactionFeedback.catalog.ts for what a row says).
import { type FeedbackRow, row } from './row';

// prettier-ignore
export const editingFeedback: Record<string, FeedbackRow> = {
  // Editing check panel (editing-readiness-analysis.prd.md, Phase 7)
  'src/components/editing/EditingCheckPanel.tsx::tracksList#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The REAPER tracks for the chapter-track link shown when a mapping refusal needs one; the block says it is reading them, and a failure is written in place with a link to the Tracks page (mirrors RecordingCheck.tsx\'s own TrackLink).'),
  'src/components/editing/EditingCheckPanel.tsx::chapterTrackMapConfirm#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Confirm on the in-panel MappingConfirm: busy until the link is written, then the refusal clears and the signals are read again; a failure is written in place.'),
  'src/components/editing/EditingCheckPanel.tsx::editingCandidates#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The chapter\'s current candidates on open, and again once a run for this chapter ends; a failed read is an inline alert above the class summaries, which still show from the signals alone.'),
  'src/components/editing/EditingCheckPanel.tsx::stageRecommendations#1': row('mount', 'file-io', 'na', 'na', 'ui', 'na', 'na', 'ok', 'Reads the chapter\'s editing signals (met, not met, unknown with its cause) on open, and again after a run ends or a mapping is confirmed; a failed read is not shown as an error - the panel falls back to the candidate list alone, since a signal is only ever a richer explanation of what the candidates already say.'),
  'src/components/editing/EditingCheckPanel.tsx::editingState#1': row('mount', 'instant', 'na', 'na', 'ui', 'na', 'na', 'ok', 'Reads the current or last check on open, so a run left going from the Tracks page or the SR popover is picked up here too; nothing to acknowledge and nothing to fail against, since it only decides which view (running or not) to show first.'),
  'src/components/editing/EditingCheckPanel.tsx::editingState#2': row('timer', 'instant', 'na', 'na', 'poll', 'na', 'na', 'ok', 'Polls every 500 ms while a run for this chapter is going, showing the host\'s own real progress (ADR 0015); a failed poll is not surfaced on its own; the next tick tries again, and the run itself still ends with a state the following tick reads.'),
  'src/components/editing/EditingCheckPanel.tsx::chapterTrackMapList#1': row('click', 'file-io', 'pending', 'host', 'na', 'inline', 'na', 'ok', 'Reads the project\'s documentId once, cached, before the first Check editing / Check again; folded into the same pending Start button as editingStart#1, and a failure surfaces as that button\'s own toast.'),
  'src/components/editing/EditingCheckPanel.tsx::editingStart#1': row('click', 'job', 'pending', 'host', 'event', 'inline', 'yes', 'ok', 'Check editing / Check again is busy until the host answers; a refusal (unmapped, another check running, no project) is written in place, with the inline mapping prompt for the link causes. A successful start shows the progress bar the state poll (editingState#2) drives; the end is read by the same poll, not a separate event, since editing-readiness-analysis.prd.md Phase 5 ships no coverage:state-style live event yet.'),
  'src/components/editing/EditingCheckPanel.tsx::editingCancel#1': row('click', 'instant', 'pending', 'pending', 'poll', 'inline', 'na', 'ok', 'Cancel is busy until the host answers; the next state poll (editingState#3) shows Cancelled and Check again, and a failed cancel is a toast (the run keeps going, so nothing is silently lost).'),
  'src/components/editing/EditingCheckPanel.tsx::editingState#3': row('click', 'instant', 'na', 'na', 'ui', 'na', 'na', 'ok', 'Read once right after Cancel answers, so the panel does not wait a further 500 ms for the next poll to show Cancelled; covered by editingCancel#1\'s own row.'),
  'src/components/editing/EditingCandidateRow.tsx::findingsReview#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Accept, Dismiss, Defer and Reopen run one at a time through usePendingAction: the pressed button is busy, the others are off, and the row\'s status line updates; a refusal on changed evidence (ADR 0120) re-reads the candidate (findingsGet#1) and says so in plain words, otherwise it gives the host reason.'),
  'src/components/editing/EditingCandidateRow.tsx::findingsGet#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Only after a refused decision, to tell changed evidence from any other refusal; if it fails too, the inline alert gives the host reason for the refusal (mirrors FindingDetail.tsx\'s own re-read).'),

};
