// The interaction feedback rows for the home call sites (see interactionFeedback.catalog.ts for what a row says).
import { type FeedbackRow, row, subscription } from './row';

// prettier-ignore
export const homeFeedback: Record<string, FeedbackRow> = {
  // Home
  'src/components/home/AudiobookEstimatePanel.tsx::manuscriptChapters#1': row('mount', 'file-io', 'na', 'na', 'ui', 'toast', 'na', 'ok', 'A failed load empties the estimate and says why, instead of reading as a manuscript with no chapters (phase 6); also re-read when the window regains focus (throttled, home-stage-check-line.prd.md Phase 2), sharing the same failure handling.'),
  'src/components/home/AudiobookEstimatePanel.tsx::manuscriptSetChapterStatus#1': row('input', 'file-io', 'none', 'none', 'ui', 'toast', 'na', 'ok', 'A small file write; the select shows the new status when it returns.'),
  'src/components/home/AudiobookEstimatePanel.tsx::subscribeCoverage#1': subscription('The recording check state (recording coverage Phase 6): a row shows the percent of a check sent to the background, and a completed check re-reads the chapters for their measured recordedFraction.'),
  'src/components/home/AudiobookEstimatePanel.tsx::chapterTrackLinks#1': row('effect', 'file-io', 'na', 'na', 'ui', 'toast', 'na', 'ok', 'Every narration chapter\'s track link state and each track\'s facts from one .rpp parse (chapter-track-link-control.prd.md Phase 2): fills the Track column and re-reads after a link, relink or unlink; a failed read is a toast, leaving the column as it was.'),
  'src/components/home/AudiobookEstimatePanel.tsx::chapterSyncUndo#1': row('click', 'file-io', 'none', 'none', 'toast', 'toast', 'na', 'ok', 'Undo on the chapter-sync toast (daw-chapter-track-auto-sync.prd.md Phase 3, S12): removes each link the batch just made; a failure is its own toast and the links stay as the batch left them.'),
  'src/components/home/AudiobookEstimatePanel.tsx::manuscriptSetChapterKind#1': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Remove from recording, confirmed in the track slide-over (chapter-track-link-control.prd.md Phase 3): busy until it returns, a toast either way, and a failure keeps the confirm open (ChapterTrackPanel) for a retry.'),
  'src/components/home/AudiobookEstimatePanel.tsx::manuscriptSetChapterKind#2': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Restore on a Removed-from-recording row; that row is busy until it returns and a toast either way.'),
  'src/hooks/useChapterSync.ts::chapterSyncState#1': row('mount', 'file-io', 'na', 'na', 'event', 'silent', 'na', 'exempt', 'Seeds the state useChapterSync exposes before the very next chaptersync:state event takes over; a failed seed just leaves it undefined a moment longer, and this mount effect has no narrator action to guard or report against (SILENT_CATCHES).'),
  'src/hooks/useChapterSync.ts::subscribeChapterSync#1': subscription('Chapter sync\'s state (daw-chapter-track-auto-sync.prd.md Phase 3): every link path, sync and Undo sends chaptersync:state; Home\'s toast and the coming consent dialog and Tracks states all read this one subscription.'),
  'src/components/home/RecordingCheck.tsx::coverageResult#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Reads the chapter\'s stored check when the dialog opens (never runs one, Q14); the dialog says it is reading, and a failure is written in the dialog with Retry.'),
  'src/components/home/RecordingCheck.tsx::coverageStart#1': row('click', 'job', 'pending', 'host', 'event', 'dialog', 'yes', 'ok', 'Check recording is busy until the host answers, then the work dialog shows the host\'s real progress; the host refuses a second check (busy) and a refusal is written in the dialog in plain words. The end is one job:ended the app announces wherever the narrator is (ADR 0076).'),
  'src/components/home/RecordingCheck.tsx::whisperInstall#1': row('click', 'download', 'dialog', 'host', 'dialog', 'dialog', 'no', 'ok', 'The same first-use question and download dialog as Proofing (useAssetInstall): nothing downloads until the narrator says yes, and a successful install goes on with the check.'),
  'src/components/home/RecordingCheck.tsx::whisperInstallState#1': row('timer', 'download', 'dialog', 'na', 'poll', 'dialog', 'no', 'ok', 'The one install-poll loop (useAssetInstall): real bytes in the dialog, and a failed poll is shown there. The download ends with job:ended.'),
  'src/components/home/RecordingCheck.tsx::whisperInstallCancel#1': row('click', 'download', 'dialog', 'dialog', 'dialog', 'dialog', 'no', 'ok', 'Cancel is drawn only while bytes arrive; the dialog says it was cancelled, and a failed cancel is shown in the dialog.'),
  'src/components/home/RecordingCheck.tsx::coverageCancel#1': row('click', 'instant', 'pending', 'pending', 'ui', 'toast', 'na', 'ok', 'A second press is ignored until the host answers; the next state event turns the work dialog to Cancelled, and a failed cancel is a toast.'),
  'src/components/home/RecordingCheck.tsx::tracksList#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The REAPER tracks for the chapter-track link shown when a check needs one; the block says it is reading them, and a failure is written in place with a link to the Tracks page.'),
  'src/components/home/RecordingCheck.tsx::chapterTrackMapConfirm#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Confirm on the in-dialog MappingConfirm: busy until the link is written, then the stored result is read again; a failure is written in place.'),
  'src/components/home/RecordingCheckReport.tsx::findingsList#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'A background count of the chapter\'s other pickups - take review\'s unreviewed repeated reads (recording-check-summary.prd.md Phase 3, RS4 A) - alongside the check\'s own gaps; nothing for the narrator to guard or retry, so a failure just leaves the line out (SILENT_CATCHES).'),
  'src/components/home/ChapterTrackPanel.tsx::tracksList#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The REAPER tracks for the panel\'s own MappingConfirm; the section says it is reading them, and a failure is written in place instead of the picker.'),
  'src/components/home/ChapterTrackPanel.tsx::chapterTrackSet#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'toast', 'no', 'ok', 'Confirm, a candidate\'s Link, or a conflict\'s Keep this one: busy until the link replaces the chapter\'s old one; a toast names the displaced chapter when the track was linked elsewhere, and a failure is a toast.'),
  'src/components/home/ChapterTrackPanel.tsx::chapterTrackUnlink#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'toast', 'no', 'ok', 'Clear: busy until every link the chapter holds is removed; a toast confirms, and a failure is a toast.'),
  // Stage suggestions on Home (chapter-stage-recommendations.prd.md Phase 5): read on load and on Check now, acted on by one click (Q13).
  'src/components/stages/useStageRecommendations.ts::stageRecommendations#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Reads every chapter\'s suggestion when Home opens and again after an import, a finished check, a status changed by hand, the window regaining focus (throttled, home-stage-check-line.prd.md Phase 2) and, on a failed read, Try again (Phase 1); each row says Checking… until the first read answers and Try again is busy meanwhile; a failure reads "Couldn\'t check" in every row, with the reason and Try again above the table and a chip on the card.'),
  'src/components/stages/useStageRecommendations.ts::stageRevert#1': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'yes', 'ok', 'Revert is busy (and the other decisions wait) until the host answers; the status select and the row follow and a toast says where the chapter went back to. A refusal or a failure is an error toast, and a refusal reads the suggestions again.'),
  'src/components/stages/useStageRecommendations.ts::stageConfirm#1': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'yes', 'ok', 'Confirm is busy (and the other decisions wait) until the host answers; the status select moves, the row offers Revert and a toast names the new stage. A refused basis (the evidence moved meanwhile) is an error toast and the suggestions are read again.'),
  'src/components/stages/useStageRecommendations.ts::stageDismiss#1': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'yes', 'ok', 'Dismiss is busy until the host answers; the row reads the suggestion as dismissed and a toast says so. A refusal or a failure is an error toast, and a refusal reads the suggestions again.'),
  // The Credits stat (useCreditsSeconds, audiobook-credits-templates.prd.md Phases 2 and 5): a secondary stat, so every read
  // behind it falls back to leaving the stat out (or room tone at 0) rather than a toast over the narration estimate.
  'src/components/home/useCreditsSeconds.ts::creditsTemplates#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'Loads the templates behind the Credits stat; a failed load leaves the stat out of the row rather than a toast over a secondary stat.'),
  'src/components/home/useCreditsSeconds.ts::creditsPreview#1': row('effect', 'instant', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'Renders the first opening and closing template for their word counts; a failed render leaves the Credits stat out.'),
  'src/components/home/useCreditsSeconds.ts::creditsChapterAnnouncements#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'Renders the first chapter announcement for every narration chapter (Phase 5, ADR 0151); a failed render leaves the Credits stat out.'),
  'src/components/home/useCreditsSeconds.ts::settingsForScope#1': row('effect', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Reads the room tone setting (Phase 5); unreadable, it counts as 0 seconds, the default, and Settings reports the real error.'),
  // Credits rows in the Home chapter table (credits-in-chapter-table.prd.md Phase 2): the same mount-time-load,
  // fail-quiet shape as the Credits stat above, since a row is a secondary summary of the same underlying data - and one
  // real mutation (setCreditsStatus), whose failure does toast, matching manuscriptSetChapterStatus's row below.
  'src/components/home/useCreditsRows.ts::creditsTemplates#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'Loads the templates behind the credits rows; a failed load leaves both rows out rather than a toast over a secondary part of the table.'),
  'src/components/home/useCreditsRows.ts::creditsStatuses#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'exempt', "Loads each credits row's status from the project manifest; a failed load leaves both rows out."),
  'src/components/home/useCreditsRows.ts::creditsPreview#1': row('effect', 'instant', 'na', 'na', 'ui', 'inline', 'na', 'exempt', "Renders a row's template for its word count and unresolved tokens; a failed render leaves both rows out."),
  'src/components/home/useCreditsRows.ts::setCreditsStatus#1': row('input', 'file-io', 'none', 'none', 'ui', 'toast', 'na', 'ok', 'A small file write; the select shows the new status when it returns.'),
  'src/components/home/Home.tsx::guideEntities#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Only decides whether the "entries need review" nudge shows; without it the nudge is absent.'),
  'src/components/home/Home.tsx::transcriptLastCompleted#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Only fills the last-run card, which is empty when the run cannot be read.'),
  'src/components/home/Home.tsx::manuscriptImportState#1': row('timer', 'instant', 'dialog', 'dialog', 'poll', 'dialog', 'no', 'ok', 'The import dialog is modal, so the narrator cannot leave Home while it runs; a job-end event carries the outcome for the notifier (ADR 0076).'),
  'src/components/home/Home.tsx::manuscriptImportPreview#1': row('click', 'job', 'dialog', 'host', 'poll', 'dialog', 'no', 'ok', 'Modal import dialog with real progress; the host refuses a second run.'),
  'src/components/home/Home.tsx::manuscriptImportCommit#1': row('click', 'job', 'dialog', 'host', 'poll', 'dialog', 'no', 'ok', 'Modal import dialog with real progress; a job-end event carries the outcome (ADR 0076).'),
  'src/components/home/Home.tsx::selectManuscript#1': row('click', 'os-dialog', 'pending', 'pending', 'ui', 'toast', 'no', 'ok', 'One choose-a-file button for import and replace: busy while the host dialog is open, so a second press cannot open a second dialog, and a failure is a toast (phase 6).'),
  'src/components/home/Home.tsx::manuscriptBeginImport#1': row('click', 'instant', 'none', 'none', 'dialog', 'toast', 'no', 'ok', 'Instant: it only registers the detected file; the import dialog follows.'),
  'src/components/home/Home.tsx::manuscriptImportCancel#1': row('click', 'instant', 'none', 'none', 'ui', 'toast', 'no', 'ok', 'Instant: it only marks the import cancelled.'),
  'src/components/home/Home.tsx::manuscriptImportPreview#2': row('input', 'job', 'dialog', 'host', 'poll', 'toast', 'no', 'ok', 'A new heading level re-runs the preview inside the same dialog with progress.'),
  'src/components/home/Home.tsx::manuscriptImportCancel#2': row('click', 'instant', 'none', 'none', 'ui', 'toast', 'no', 'ok', 'Cancel from the progress dialog: a refused cancel is now a toast (phase 6).'),
  'src/components/home/Home.tsx::settingsForScope#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Only pre-fills the "Build the Story Bible after import" checkbox; the on-by-default (D8) local state stays usable without it.'),
  'src/components/home/Home.tsx::guideBuild#1': row('event', 'job', 'dialog', 'na', 'poll', 'toast', 'no', 'ok', 'B1-B3: chained after a successful import. A "Manuscript imported." toast precedes it, so the narrator is never left wondering whether the import itself worked; a build failure is its own toast and never unmakes the import.'),
  'src/components/home/Home.tsx::guideBuildState#1': row('timer', 'instant', 'dialog', 'na', 'poll', 'dialog', 'no', 'ok', 'Polls the chained build the same way Guide.tsx polls its own; the app-level job:ended subscriber raises the completion toast (ADR 0076), so this dialog only shows progress.'),

};
