// The interaction feedback rows for Master & QC's call sites (stage navigation Phase 8; formerly the Delivery page's) (see interactionFeedback.catalog.ts for what a row says).
import { type FeedbackRow, row } from './row';

// prettier-ignore
export const masterFeedback: Record<string, FeedbackRow> = {
  // Master & QC's checks (diagnostics-delivery-and-cleanup-tools.prd.md, Phase 5; stage navigation Phase 8)
  'src/components/master/MasterQcPage.tsx::measureState#1': row('mount', 'instant', 'na', 'na', 'ui', 'inline', 'yes', 'ok', 'On opening Master & QC: the last measurement the host kept is shown again, and one still running is followed with its progress; a failed read is an inline alert in the Per-file checks panel.'),
  'src/components/master/MasterQcPage.tsx::deliveryProfiles#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Reads the delivery profile the project is judged against, for the profile panel; when it cannot be read the panel says so inline. The measurement itself carries the profile that judged it, so the table never depends on this read.'),
  'src/components/master/MasterQcPage.tsx::measureState#2': row('timer', 'instant', 'inline', 'disabled', 'poll', 'inline', 'yes', 'ok', 'Polls every 500 ms while the measurement runs: the bar is the share of the bytes read (ADR 0015) and each file row says whether it waits, is being measured or is done; the end is also a job:ended toast (ADR 0076).'),
  'src/components/master/MasterQcPage.tsx::measurePickFiles#1': row('click', 'os-dialog', 'pending', 'pending', 'ui', 'inline', 'na', 'ok', 'Check files… is busy while the operating system picker is open (only before anything is checked: after that it re-checks the same files); closing it without a choice does nothing. A failure is an inline alert in the Per-file checks panel.'),
  'src/components/master/MasterQcPage.tsx::measureAnalyze#1': row('click', 'job', 'pending', 'host', 'poll', 'inline', 'yes', 'ok', 'Starts the measurement of the picked files with the same button still busy, then the panel shows its progress and the button is off until it ends; a refusal (a path not picked, too many files, one already running) is an inline alert in the host words.'),
  'src/components/master/MasterQcPage.tsx::measureCancel#1': row('click', 'instant', 'inline', 'none', 'ui', 'inline', 'yes', 'ok', 'Cancel stops the measurement; files already measured keep their results and the rest say they were not measured. A failed request is an inline alert.'),
  'src/components/master/MasterQcPage.tsx::measurePickFiles#2': row('click', 'os-dialog', 'pending', 'pending', 'ui', 'inline', 'na', 'ok', 'Choose other files… (once files are checked) is busy while the operating system picker is open; closing it without a choice does nothing and keeps the last check. A failure is an inline alert in the Per-file checks panel.'),
  // Master & QC's platform tabs (stage navigation Phase 8, ADR 0440): a tab is the project's own choice of delivery profile
  'src/components/master/MasterQcPage.tsx::deliverySelectProfile#1': row('click', 'file-io', 'inline', 'disabled', 'ui', 'inline', 'na', 'ok', 'Pressing a platform tab saves it as the project\'s delivery profile; every tab is off until the host answers, and the chosen tab, the package title and the profile panel then name it. A refusal (no project, a profile that is gone) is an inline alert under the title, and the tab stays where it was.'),
  'src/components/master/MasterQcPage.tsx::measureState#3': row('click', 'instant', 'inline', 'disabled', 'ui', 'inline', 'na', 'ok', 'After a platform tab is saved, the last check is read again: the host judges it against the new profile when it is read, so the table, the verdicts and why a file fails change without measuring again. A failed read is the same inline alert as the tab\'s.'),
  // Master & QC's mastering chain (the mastering port, ADR 0306)
  'src/components/master/MasteringChain.tsx::masteringProviders#1': row('mount', 'instant', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'On opening Master & QC: the mastering chain the project masters with, drawn as its steps; a failed read is an inline alert in the Mastering chain panel, and nothing else on the page depends on it.'),
  'src/components/master/BookChecklist.tsx::creditsTemplates#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Loads the credits templates for the "In this project" bonus line under acx.credits; a failed load just leaves that line out, since the rule\'s own "not checked by the app" status already shows and this is only a bonus fact under it.'),
  'src/components/master/BookChecklist.tsx::creditsRetailSample#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Reads the retail sample for the "In this project" bonus line under acx.retail_sample; a failed load just leaves that line out, since the rule\'s own "not checked by the app" status already shows and this is only a bonus fact under it.'),
  // Master & QC, Diagnostics (diagnostics-delivery-and-cleanup-tools.prd.md Phase 6)
  'src/components/master/DiagnosticsSection.tsx::diagnosticsState#1': row('mount', 'instant', 'na', 'na', 'ui', 'inline', 'yes', 'ok', 'On opening Master & QC, its Diagnostics section: the thresholds a check uses and the last check the host kept, or one still running followed with its progress; a failed read is an inline alert in the Diagnostics panel.'),
  'src/components/master/DiagnosticsSection.tsx::diagnosticsState#2': row('timer', 'instant', 'inline', 'disabled', 'poll', 'inline', 'yes', 'ok', 'Polls every 500 ms while the check runs: the bar is the share of the bytes read (ADR 0015) and each file row says whether it waits, is being checked or is done; the end is also a job:ended toast (ADR 0076).'),
  'src/components/master/DiagnosticsSection.tsx::measurePickFiles#1': row('click', 'os-dialog', 'pending', 'pending', 'ui', 'inline', 'na', 'ok', 'Choose files to check is busy while the operating system picker is open; closing it without a choice does nothing. A failure is an inline alert in the Diagnostics panel.'),
  'src/components/master/DiagnosticsSection.tsx::diagnosticsAnalyze#1': row('click', 'job', 'pending', 'host', 'poll', 'inline', 'yes', 'ok', 'Starts the check of the picked or measured files with the same button still busy, then the panel shows its progress and both buttons and the source-kind choice are off until it ends; a refusal (a path not picked, an unknown source kind, one already running) is an inline alert in the host words.'),
  'src/components/master/DiagnosticsSection.tsx::diagnosticsCancel#1': row('click', 'instant', 'inline', 'none', 'ui', 'inline', 'yes', 'ok', 'Cancel stops the check; files already checked keep their findings and the rest say they were not checked. A failed request is an inline alert.'),
  // Master & QC, the report export (diagnostics-delivery-and-cleanup-tools.prd.md Phase 7)
  'src/components/master/ReportExportPanel.tsx::deliveryExportReport#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'na', 'ok', 'Export report is busy while the host writes the two files, and off while a measurement runs; the panel then names the files written and what the report counts. A refusal (no project, a job running, nothing measured) or a write failure is an inline alert in the host words, and nothing is written.'),
  // Master & QC, Master all to spec and the delivery package (render-encode-master.prd.md Phase 5)
  'src/components/master/useExportJobs.ts::exportState#1': row('mount', 'instant', 'na', 'na', 'ui', 'inline', 'yes', 'ok', 'On opening Master & QC: the last export job the host kept is shown again, and one still running is followed with its progress; a failed read is an inline alert.'),
  'src/components/master/useExportJobs.ts::packageState#1': row('mount', 'instant', 'na', 'na', 'ui', 'inline', 'yes', 'ok', 'On opening Master & QC: the last package job the host kept, or one still running followed with its progress; a failed read is an inline alert under the Delivery package panel.'),
  'src/components/master/useExportJobs.ts::exportPickFiles#1': row('click', 'os-dialog', 'pending', 'pending', 'ui', 'inline', 'na', 'ok', 'Master all to spec… is busy while the operating system picker is open; closing it without a choice does nothing. A failure is an inline alert.'),
  'src/components/master/useExportJobs.ts::exportStart#1': row('click', 'job', 'pending', 'host', 'poll', 'inline', 'yes', 'ok', 'Master & encode starts the job; the panel then shows its progress and the export controls are hidden until it ends. A refusal (a path not picked, an untitled chapter, one already running) is an inline alert in the host words.'),
  'src/components/master/useExportJobs.ts::exportState#2': row('timer', 'instant', 'inline', 'disabled', 'poll', 'inline', 'yes', 'ok', 'Polls every 500 ms while the export runs: the bar is the share of the files\' bytes prepared and each file row says whether it waits, is mastering, is encoding or is done; the end is also a job:ended toast (ADR 0076).'),
  'src/components/master/useExportJobs.ts::exportCancel#1': row('click', 'instant', 'inline', 'none', 'ui', 'inline', 'yes', 'ok', 'Cancel stops the export; files already prepared keep their results and the rest say they were cancelled. A failed request is an inline alert.'),
  'src/components/master/useExportJobs.ts::packageStart#1': row('click', 'job', 'pending', 'host', 'poll', 'inline', 'yes', 'ok', 'Build packages opens the operating system\'s folder picker, then starts the job; the panel shows it running (no finer progress than that, packager.Assemble has none to report) and its checklist once it ends. A refusal (an unencoded path, an unknown profile, one already running, a missing required item) is an inline alert in the host words; closing the picker without choosing a folder leaves the state unstarted.'),
  'src/components/master/useExportJobs.ts::packageState#2': row('timer', 'instant', 'inline', 'disabled', 'poll', 'inline', 'yes', 'ok', 'Polls every 500 ms while the package builds; the end is also a job:ended toast (ADR 0076).'),
  'src/components/master/useExportJobs.ts::packageCancel#1': row('click', 'instant', 'inline', 'none', 'ui', 'inline', 'yes', 'ok', 'Cancel stops the package build. A failed request is an inline alert.'),
  // Master & QC, multi-platform export (render-encode-master.prd.md Phase 6)
  'src/components/master/useExportJobs.ts::packageMultiState#1': row('mount', 'instant', 'na', 'na', 'ui', 'inline', 'yes', 'ok', 'On opening Master & QC: the last multi-platform package job the host kept, or one still running followed with its per-profile progress; a failed read is an inline alert under the Multi-platform export panel.'),
  'src/components/master/useExportJobs.ts::packageStartMulti#1': row('click', 'job', 'pending', 'host', 'poll', 'inline', 'yes', 'ok', 'Build N packages opens the operating system\'s folder picker once, then starts the job; the panel shows each checked profile\'s own row (pending, running, built or failed) as it goes. A refusal (an empty selection, an unencoded path, an unknown profile, one already running) is an inline alert in the host words; closing the picker without choosing a folder leaves the state unstarted.'),
  'src/components/master/useExportJobs.ts::packageMultiState#2': row('timer', 'instant', 'inline', 'disabled', 'poll', 'inline', 'yes', 'ok', 'Polls every 500 ms while the multi-platform build runs: each profile\'s own row updates as its package finishes; the end is also a job:ended toast (ADR 0076).'),
  'src/components/master/useExportJobs.ts::packageMultiCancel#1': row('click', 'instant', 'inline', 'none', 'ui', 'inline', 'yes', 'ok', 'Cancel stops the multi-platform build before its next profile starts; profiles already built keep their results and one not yet reached stays pending. A failed request is an inline alert.'),

};
