// The interaction feedback rows for the Production home's call sites (production tracking, and what moved in from Home in
// stage-navigation-and-page-replacement.prd.md Phase 2) (see interactionFeedback.catalog.ts for what a row says).
import { type FeedbackRow, row, subscription } from './row';

// prettier-ignore
export const productionFeedback: Record<string, FeedbackRow> = {
  // The header's running-timer chip (stage-navigation-and-page-replacement.prd.md Phase 2)
  'src/App.tsx::productionOverview#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Reads whether a production stage timer runs, once per manuscript, so the header chip shows on whichever page the app opens on; unreadable, the chip stays hidden and the Production home says why when it reads its own.'),
  // Production (production-tracking.prd.md Phase 4)
  'src/components/production/ProductionPage.tsx::productionOverview#2': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'On opening Production: the figures, the board and Next up; while it reads the page says so, and a failed read is an inline alert in place of the page.'),
  'src/components/production/ProductionPage.tsx::productionOverview#1': row('click', 'file-io', 'none', 'none', 'ui', 'inline', 'na', 'ok', 'Refresh, and the re-read after starting or stopping a timer or after anything on the board changes a status, a link or a measurement: the page is redrawn from the new overview; a failed read replaces it with an inline alert.'),
  'src/components/production/ProductionPage.tsx::productionStartTimer#1': row('click', 'file-io', 'pending', 'disabled', 'ui', 'inline', 'yes', 'ok', 'Start timer is busy on its chapter and the other chapters\' buttons are off until it answers; the header\'s timer chip then names the chapter and counts, Stop timer appears in the page header, and every Start timer goes away. A refusal (a timer already running) or a failure is an inline alert in the host words, and nothing is logged.'),
  'src/components/production/ProductionPage.tsx::productionStopTimer#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Stop timer (in the page header) is busy until the session is logged, then it and the header\'s timer chip go away and a status line names the chapter whose session was logged. A failure is an inline alert and the timer keeps running.'),
  'src/components/production/PlanPanel.tsx::productionPlan#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Reads the delivery date, contracted amount and milestones into the Delivery plan panel; its fields stay off until it answers, and a failed read is an inline alert in the panel.'),
  'src/components/production/PlanPanel.tsx::setProductionDeadline#1': row('click', 'file-io', 'pending', 'disabled', 'ui', 'inline', 'yes', 'ok', 'Save date and amount is busy and Save milestones is off until it answers; a status line then says it saved and the figures are read again. An amount that is not a number is refused under its field before anything is sent; the host refusing an impossible date is an inline alert, and nothing is saved.'),
  'src/components/production/PlanPanel.tsx::saveProductionMilestones#1': row('click', 'file-io', 'pending', 'disabled', 'ui', 'inline', 'yes', 'ok', 'Save milestones is busy and Save date and amount is off until it answers; a status line then says it saved. A milestone with no name or no real date refuses the whole list as an inline alert in the host words, and nothing is saved.'),
  // Status report export (production-tracking.prd.md Phase 5)
  'src/components/production/StatusReportPanel.tsx::productionStatusReport#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'na', 'ok', 'Export status report is busy while the host writes the two files; the panel then names the files written and whether the contracted amount and rate were included. A refusal (no project) or a write failure is an inline alert in the host words, and nothing is written.'),
  // Home's surfaces, opened from the board (stage-navigation-and-page-replacement.prd.md Phase 2)
  'src/components/production/ChapterBoard.tsx::manuscriptChapters#1': row('mount', 'file-io', 'na', 'na', 'ui', 'toast', 'na', 'ok', 'A failed load empties the estimate and says why, instead of reading as a manuscript with no chapters (phase 6); also re-read when the window regains focus (throttled, home-stage-check-line.prd.md Phase 2), sharing the same failure handling.'),
  'src/components/production/ChapterBoard.tsx::manuscriptSetChapterStatus#1': row('input', 'file-io', 'none', 'none', 'ui', 'toast', 'na', 'ok', 'A small file write; the select shows the new status when it returns.'),
  'src/components/production/ChapterBoard.tsx::subscribeCoverage#1': subscription('The recording check state (recording coverage Phase 6): a row shows the percent of a check sent to the background, and a completed check re-reads the chapters for their measured recordedFraction.'),
  'src/components/production/ChapterBoard.tsx::chapterTrackLinks#1': row('effect', 'file-io', 'na', 'na', 'ui', 'toast', 'na', 'ok', 'Every narration chapter\'s track link state and each track\'s facts from one .rpp parse (chapter-track-link-control.prd.md Phase 2): fills the Track column and re-reads after a link, relink or unlink; a failed read is a toast, leaving the column as it was.'),
  'src/components/production/ChapterBoard.tsx::chapterSyncUndo#1': row('click', 'file-io', 'none', 'none', 'toast', 'toast', 'na', 'ok', 'Undo on the chapter-sync toast (daw-chapter-track-auto-sync.prd.md Phase 3, S12): removes each link the batch just made; a failure is its own toast and the links stay as the batch left them.'),
  'src/components/production/ChapterBoard.tsx::manuscriptSetChapterKind#1': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Remove from recording, confirmed in the track slide-over (chapter-track-link-control.prd.md Phase 3): busy until it returns, a toast either way, and a failure keeps the confirm open (ChapterTrackPanel) for a retry.'),
  'src/components/production/ChapterBoard.tsx::manuscriptSetChapterKind#2': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Restore on a Removed-from-recording row; that row is busy until it returns and a toast either way.'),
  'src/hooks/useChapterSync.ts::chapterSyncState#1': row('mount', 'file-io', 'na', 'na', 'event', 'silent', 'na', 'exempt', 'Seeds the state useChapterSync exposes before the very next chaptersync:state event takes over; a failed seed just leaves it undefined a moment longer, and this mount effect has no narrator action to guard or report against (SILENT_CATCHES).'),
  'src/hooks/useChapterSync.ts::subscribeChapterSync#1': subscription('Chapter sync\'s state (daw-chapter-track-auto-sync.prd.md Phase 3): every link path, sync and Undo sends chaptersync:state; the Production board\'s toast and the coming consent dialog and Tracks states all read this one subscription.'),
  'src/components/production/RecordingCheck.tsx::coverageResult#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Reads the chapter\'s stored check when the dialog opens (never runs one, Q14); the dialog says it is reading, and a failure is written in the dialog with Retry.'),
  'src/components/production/RecordingCheck.tsx::coverageStart#1': row('click', 'job', 'pending', 'host', 'event', 'dialog', 'yes', 'ok', 'Check recording is busy until the host answers, then the work dialog shows the host\'s real progress; the host refuses a second check (busy) and a refusal is written in the dialog in plain words. The end is one job:ended the app announces wherever the narrator is (ADR 0076).'),
  'src/components/production/RecordingCheck.tsx::whisperInstall#1': row('click', 'download', 'dialog', 'host', 'dialog', 'dialog', 'no', 'ok', 'The same first-use question and download dialog as Proofing (useAssetInstall): nothing downloads until the narrator says yes, and a successful install goes on with the check.'),
  'src/components/production/RecordingCheck.tsx::whisperInstallState#1': row('timer', 'download', 'dialog', 'na', 'poll', 'dialog', 'no', 'ok', 'The one install-poll loop (useAssetInstall): real bytes in the dialog, and a failed poll is shown there. The download ends with job:ended.'),
  'src/components/production/RecordingCheck.tsx::whisperInstallCancel#1': row('click', 'download', 'dialog', 'dialog', 'dialog', 'dialog', 'no', 'ok', 'Cancel is drawn only while bytes arrive; the dialog says it was cancelled, and a failed cancel is shown in the dialog.'),
  'src/components/production/RecordingCheck.tsx::whisperInstall#2': row('click', 'download', 'dialog', 'host', 'dialog', 'dialog', 'no', 'ok', 'The model cascade\'s re-check model (Phase 5, MC4): the same useAssetInstall question and download dialog as whisperInstall#1, for the "Download model" choice on the recheck_asset_required gate; "Check with tiny only" instead skips the download and starts the check with the first pass alone.'),
  'src/components/production/RecordingCheck.tsx::whisperInstallState#2': row('timer', 'download', 'dialog', 'na', 'poll', 'dialog', 'no', 'ok', 'The re-check model\'s install-poll loop (recheckInstall, MC4): real bytes in the dialog, and a failed poll is shown there. The download ends with job:ended.'),
  'src/components/production/RecordingCheck.tsx::whisperInstallCancel#2': row('click', 'download', 'dialog', 'dialog', 'dialog', 'dialog', 'no', 'ok', 'Cancel on the re-check model\'s download (recheckInstall, MC4): drawn only while bytes arrive; the dialog says it was cancelled, and a failed cancel is shown in the dialog.'),
  'src/components/production/RecordingCheck.tsx::coverageCancel#1': row('click', 'instant', 'pending', 'pending', 'ui', 'toast', 'na', 'ok', 'A second press is ignored until the host answers; the next state event turns the work dialog to Cancelled, and a failed cancel is a toast.'),
  'src/components/production/RecordingCheck.tsx::tracksList#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The REAPER tracks for the chapter-track link shown when a check needs one; the block says it is reading them, and a failure is written in place with a link to the Tracks page.'),
  'src/components/production/RecordingCheck.tsx::chapterTrackMapConfirm#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Confirm on the in-dialog MappingConfirm: busy until the link is written, then the stored result is read again; a failure is written in place.'),
  'src/components/production/RecordingCheckReport.tsx::findingsList#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'A background count of the chapter\'s other pickups - take review\'s unreviewed repeated reads (recording-check-summary.prd.md Phase 3, RS4 A) - alongside the check\'s own gaps; nothing for the narrator to guard or retry, so a failure just leaves the line out (SILENT_CATCHES).'),
  'src/components/production/RecordingCheckReport.tsx::subscribePickups#1': subscription('The proofer\'s project-wide pickup list (recording-check-summary.prd.md Phase 3, RS5 B), the same state PickupsDialog on Tracks reads; only subscribed once the `pickups` capability says REAPER is running.'),
  'src/components/production/RecordingCheckReport.tsx::pickupsCount#1': row('effect', 'job', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'A background refresh once the `pickups` capability becomes available, so the count is current rather than whatever REAPER last reported; a failure just leaves the line at the subscription\'s last known value, the same fallback PickupsDialog\'s own automatic refresh uses (SILENT_CATCHES).'),
  'src/components/production/ChapterTrackPanel.tsx::tracksList#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The REAPER tracks for the panel\'s own MappingConfirm; the section says it is reading them, and a failure is written in place instead of the picker.'),
  'src/components/production/ChapterTrackPanel.tsx::chapterTrackSet#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'toast', 'no', 'ok', 'Confirm, a candidate\'s Link, or a conflict\'s Keep this one: busy until the link replaces the chapter\'s old one; a toast names the displaced chapter when the track was linked elsewhere, and a failure is a toast.'),
  'src/components/production/ChapterTrackPanel.tsx::chapterTrackUnlink#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'toast', 'no', 'ok', 'Clear: busy until every link the chapter holds is removed; a toast confirms, and a failure is a toast.'),
  'src/components/production/ChapterTrackPanel.tsx::trackSelectInReaper#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'toast', 'na', 'ok', 'Select in REAPER (Phase 4, Could): busy until REAPER answers; a toast confirms or, for a refusal (REAPER not there, the experimental switch off, or the track gone), says why. Nothing in REAPER changes for a refusal.'),
  // Stage suggestions on the Production board (chapter-stage-recommendations.prd.md Phase 5): read on load and on Check now, acted on by one click (Q13).
  'src/components/stages/useStageRecommendations.ts::stageRecommendations#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Reads every chapter\'s suggestion when the Production home opens and again after an import, a finished check, a status changed by hand, the window regaining focus (throttled, home-stage-check-line.prd.md Phase 2) and, on a failed read, Try again (Phase 1); each row says Checking… until the first read answers and Try again is busy meanwhile; a failure reads "Couldn\'t check" in every row, with the reason and Try again above the table and a chip on the card.'),
  'src/components/stages/useStageRecommendations.ts::stageRevert#1': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'yes', 'ok', 'Revert is busy (and the other decisions wait) until the host answers; the status select and the row follow and a toast says where the chapter went back to. A refusal or a failure is an error toast, and a refusal reads the suggestions again.'),
  'src/components/stages/useStageRecommendations.ts::stageConfirm#1': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'yes', 'ok', 'Confirm is busy (and the other decisions wait) until the host answers; the status select moves, the row offers Revert and a toast names the new stage. A refused basis (the evidence moved meanwhile) is an error toast and the suggestions are read again.'),
  'src/components/stages/useStageRecommendations.ts::stageDismiss#1': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'yes', 'ok', 'Dismiss is busy until the host answers; the row reads the suggestion as dismissed and a toast says so. A refusal or a failure is an error toast, and a refusal reads the suggestions again.'),
  // Credits rows on the Production board (credits-in-chapter-table.prd.md Phase 2): a mount-time load that fails quietly,
  // since a row is a secondary summary - and one
  // real mutation (setCreditsStatus), whose failure does toast, matching manuscriptSetChapterStatus's row below.
  'src/components/production/useCreditsRows.ts::settingsForScope#1': row('effect', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Reads the room tone setting (audiobook-credits-templates.prd.md Phase 5) for a credits row\'s estimated length; unreadable, it counts as 0 seconds.'),
  'src/components/production/useCreditsRows.ts::creditsTemplates#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'Loads the templates behind the credits rows; a failed load leaves both rows out rather than a toast over a secondary part of the table.'),
  'src/components/production/useCreditsRows.ts::creditsStatuses#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'exempt', "Loads each credits row's status from the project manifest; a failed load leaves both rows out."),
  'src/components/production/useCreditsRows.ts::creditsPreview#1': row('effect', 'instant', 'na', 'na', 'ui', 'inline', 'na', 'exempt', "Renders a row's template for its word count and unresolved tokens; a failed render leaves both rows out."),
  'src/components/production/useCreditsRows.ts::setCreditsStatus#1': row('input', 'file-io', 'none', 'none', 'ui', 'toast', 'na', 'ok', 'A small file write; the select shows the new status when it returns.'),
  'src/components/production/ManuscriptImport.tsx::manuscriptImportState#1': row('timer', 'instant', 'dialog', 'dialog', 'poll', 'dialog', 'no', 'ok', 'The import dialog is modal, so the narrator cannot leave the Production home while it runs; a job-end event carries the outcome for the notifier (ADR 0076).'),
  'src/components/production/ManuscriptImport.tsx::manuscriptImportPreview#1': row('click', 'job', 'dialog', 'host', 'poll', 'dialog', 'no', 'ok', 'Modal import dialog with real progress; the host refuses a second run.'),
  'src/components/production/ManuscriptImport.tsx::manuscriptImportCommit#1': row('click', 'job', 'dialog', 'host', 'poll', 'dialog', 'no', 'ok', 'Modal import dialog with real progress; a job-end event carries the outcome (ADR 0076).'),
  'src/components/production/ManuscriptImport.tsx::selectManuscript#1': row('click', 'os-dialog', 'pending', 'pending', 'ui', 'toast', 'no', 'ok', 'One choose-a-file button for import and replace: busy while the host dialog is open, so a second press cannot open a second dialog, and a failure is a toast (phase 6).'),
  'src/components/production/ManuscriptImport.tsx::manuscriptBeginImport#1': row('click', 'instant', 'none', 'none', 'dialog', 'toast', 'no', 'ok', 'Instant: it only registers the detected file; the import dialog follows.'),
  'src/components/production/ManuscriptImport.tsx::manuscriptImportCancel#1': row('click', 'instant', 'none', 'none', 'ui', 'toast', 'no', 'ok', 'Instant: it only marks the import cancelled.'),
  'src/components/production/ManuscriptImport.tsx::manuscriptImportPreview#2': row('input', 'job', 'dialog', 'host', 'poll', 'toast', 'no', 'ok', 'A new heading level re-runs the preview inside the same dialog with progress.'),
  'src/components/production/ManuscriptImport.tsx::manuscriptImportCancel#2': row('click', 'instant', 'none', 'none', 'ui', 'toast', 'no', 'ok', 'Cancel from the progress dialog: a refused cancel is now a toast (phase 6).'),
  'src/components/production/ManuscriptImport.tsx::settingsForScope#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Only pre-fills the "Build the Story Bible after import" checkbox; the on-by-default (D8) local state stays usable without it.'),
  'src/components/production/ManuscriptImport.tsx::guideBuild#1': row('event', 'job', 'dialog', 'na', 'poll', 'toast', 'no', 'ok', 'B1-B3: chained after a successful import. A "Manuscript imported." toast precedes it, so the narrator is never left wondering whether the import itself worked; a build failure is its own toast and never unmakes the import.'),
  'src/components/production/ManuscriptImport.tsx::guideBuildState#1': row('timer', 'instant', 'dialog', 'na', 'poll', 'dialog', 'no', 'ok', 'Polls the chained build the same way Guide.tsx polls its own; the app-level job:ended subscriber raises the completion toast (ADR 0076), so this dialog only shows progress.'),
};
