// The interaction feedback rows for Proof's call sites (see interactionFeedback.catalog.ts for what a row says): the book's notes
// (the Review page until stage-navigation-and-page-replacement.prd.md Phase 5), the chapter view (the chapter workspace) and its
// compare run (the Proofing page).
import { type FeedbackRow, row, subscription } from './row';

// prettier-ignore
export const proofFeedback: Record<string, FeedbackRow> = {
  // Review page (review-dashboard-and-findings-adoption.prd.md, Phase 5)
  'src/components/proof/ProofPage.tsx::findingsSummary#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'Read together with the list: the first load failing is the page load error with Retry, a later one (after a filter change or a decision) is a toast and the list on screen stays.'),
  // Mock 04 on Proof (D85 on #509, ADR 0470): the accepted notes for the header's pickup and edit chips, and the proofer's sheet on the notes header.
  'src/components/proof/ProofPage.tsx::findingsList#2': row('input', 'file-io', 'na', 'na', 'ui', 'toast', 'na', 'ok', 'The accepted notes, read with the summary and the filtered list so the header splits them into "need pickup" and "fix in edit"; it fails with them, as the page load error with Retry first and a toast later.'),
  'src/components/proof/NotesHeader.tsx::pickupsImport#1': row('input', 'job', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Import proofer sheet: choosing a CSV file, the same binding as the Pickups page. Row errors and the import summary show inline under the notes header; a request failure shows as an alert.'),
  'src/components/proof/NotesHeader.tsx::pickupsExport#1': row('click', 'job', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Export for proofer: a completed export triggers the browser file-save download; a failure shows as an alert under the notes header.'),
  'src/components/proof/ProofPage.tsx::findingsList#1': row('input', 'file-io', 'na', 'na', 'ui', 'toast', 'na', 'ok', 'Runs on opening and on every filter, sort or Show more change; an answer to an older request is dropped, the first load failing is the page load error with Retry and a later one is a toast.'),
  'src/components/proof/FindingDetail.tsx::findingsReview#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Pickup (or Fix in edit), Waive, Defer and Reopen (mock 04\'s words, ADR 0470) run one at a time through usePendingAction: the pressed button is busy, the others are off, "Saved: ..." is announced and the list and counts reload. A refusal is an inline alert: on changed evidence (ADR 0120) it says so in plain words and shows the latest version, otherwise it gives the host reason.'),
  'src/components/proof/FindingDetail.tsx::findingsGet#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Only after a refused decision, to tell changed evidence from any other refusal; if it fails too, the inline alert gives the host reason for the refusal.'),
  'src/components/proof/useReaperStatus.ts::findingsReaperStatus#1': row('timer', 'instant', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Read on opening Proof and every 3 s while it is open, from the heartbeat REAPER already sends (nothing is sent to REAPER); a failed read counts as not connected and is the reason shown under the disabled Go to and Loop.'),
  'src/components/proof/ReaperControls.tsx::findingsGoTo#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'A round trip through the REAPER file bridge (under 3 s): Go to is busy and Loop and Stop are off meanwhile (usePendingAction); where REAPER put the cursor is announced, and a refusal (stale finding, recording, older script, REAPER gone) is an inline alert in plain words. The move itself stays in REAPER.'),
  'src/components/proof/ReaperControls.tsx::findingsLoop#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Loop is busy while REAPER sets the loop and plays; the window is announced and Stop loop appears (the page status names the looping finding, so the loop is shown again after the narrator leaves and comes back). A refusal is an inline alert in plain words.'),
  'src/components/proof/ReaperControls.tsx::findingsStopLoop#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Stop loop is busy until REAPER has put back the time selection, loop points and repeat; what came back (or was kept because the narrator changed it) is announced, and a refusal is an inline alert and Stop stays offered.'),
  'src/components/proof/ReaperControls.tsx::findingsAddMarker#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Only after the narrator confirms in the Add a marker in REAPER dialog (the one REAPER action here that changes the project): its Add marker is busy and Cancel is off until REAPER answers (under 3 s), then the dialog closes; the marker added (or the one already there) is announced, and a refusal (not accepted, stale finding, recording, older script, REAPER gone) is an inline alert in plain words. The marker itself stays in REAPER, undoable there.'),
  'src/components/proof/ProofPage.tsx::subscribeJobEnded#1': subscription('A pickup and duplicate scan or a take comparison left running in the background reloads the list and counts when it ends, so its groups or comparison appear without leaving the page (take review Phases 5 and 10).'),
  'src/components/proof/TakeReviewScanDialog.tsx::takeReviewScanState#1': row('mount', 'instant', 'na', 'na', 'ui', 'inline', 'yes', 'ok', 'On opening the scan dialog: a scan still running (left in the background) is shown with its progress; otherwise the form is offered with the project saved pickup scope. A failed read is an inline alert in the dialog.'),
  'src/components/proof/TakeReviewScanDialog.tsx::tracksList#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Fills the track pickers from the REAPER project file (about 2 ms); when it cannot be read the dialog says why inline and Start scan stays off.'),
  'src/components/proof/TakeReviewScanDialog.tsx::takeReviewScanState#2': row('timer', 'instant', 'dialog', 'dialog', 'dialog', 'dialog', 'yes', 'ok', 'Polls every 500 ms while the scan runs, showing the sidecar own percent and stage in WorkDialog (ADR 0015); the end is also a job:ended toast, so Continue in background loses nothing (ADR 0076).'),
  'src/components/proof/TakeReviewScanDialog.tsx::takeReviewScanStart#1': row('click', 'job', 'pending', 'host', 'dialog', 'inline', 'yes', 'ok', 'Start scan is busy while the host checks the scope and starts the job, then the dialog becomes the progress view; a refused scope or a scan already running is an inline alert in the form, in the host words.'),
  'src/components/proof/TakeReviewScanDialog.tsx::takeReviewScanCancel#1': row('click', 'instant', 'dialog', 'dialog', 'dialog', 'inline', 'no', 'ok', 'Cancel asks the sidecar to stop and the job reports cancelled once it has; nothing it found is saved. A failed request is an inline alert.'),
  'src/components/proof/TakeReviewReads.tsx::takeReviewCreateTake#1': row('click', 'job', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Add as take, after the confirm (phase 6): a bounded round trip to REAPER over the bridge. Every dialog control is off while pending; the new take is announced under the reads, and a stale item or REAPER failure is an inline alert inside the dialog, which stays open.'),
  'src/components/proof/useReadNavigation.ts::findingsGoToRead#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Go to on one read of a take-review group or a take comparison: a round trip through the REAPER file bridge, the pressed button busy and the other read controls off meanwhile (usePendingAction); where the cursor went is announced, a refusal is an inline alert in plain words.'),
  'src/components/proof/useReadNavigation.ts::findingsLoopRead#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Loop on one read: busy while REAPER sets the loop and plays; the window is announced and Stop loop appears (the page status names the looping finding, so it shows again after leaving and coming back).'),
  'src/components/proof/useReadNavigation.ts::findingsStopLoop#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Stop loop under the reads is busy until REAPER has put back the time selection, loop points and repeat; what came back is announced and a refusal is an inline alert.'),
  'src/components/proof/ProofPage.tsx::findingsGet#1': row('event', 'file-io', 'na', 'na', 'ui', 'toast', 'yes', 'ok', 'After a finished take comparison is closed: the list is narrowed to take comparisons and the new comparison is read and opened beside it; a failed read is a toast and the narrowed list still shows it.'),
  // The Takes panel (edit-and-proof-workspace.prd.md Phase 6, TakesPanel.tsx): the takes of the paragraph at the playhead.
  'src/components/proof/TakesPanel.tsx::workspaceTakes#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'Reads files already on disk (the saved project, the chapter\'s stored alignment, the findings) for the first paragraph heard when the panel opens, again for the paragraph at the playhead when the narrator asks, and again after every choice and every comparison; a failure is an inline alert in the panel, in the host\'s words.'),
  'src/components/proof/TakesPanel.tsx::workspaceUseTake#1': row('click', 'job', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Use this take is busy while REAPER answers (usePendingAction: every other Use this take is off meanwhile); a read from another item asks first in a confirm that says it is two undo steps. What happened is announced under the list ("Made that take active... in one undo step"), and a refusal (recording, an older script, REAPER gone, the item moved) is an inline alert in the host words with nothing changed.'),
  'src/components/proof/TakesPanel.tsx::retakeLanesState#1': row('timer', 'instant', 'na', 'na', 'ui', 'inline', 'no', 'ok', 'After a lane pick is started (one Use this take on a retake), the panel reads the pick\'s state every 500 ms for up to ten seconds, then announces how it ended; a failed read is an inline alert, and leaving the page ends the wait (the pick itself is REAPER\'s, one undo step).'),
  'src/components/proof/TakesPanel.tsx::workspaceTakesCompareStart#1': row('click', 'job', 'dialog', 'host', 'dialog', 'inline', 'yes', 'ok', 'Compare takes opens the same progress dialog as a group comparison (TakeComparisonDialog, its own rows above), starting the passage\'s comparison once per dialog; the host refuses a second one while one runs and says so. A refusal (fewer than two takes that can be heard, a chapter that changed) is an inline alert in the dialog, and the end is also a job:ended toast, so Continue in background loses nothing.'),
  'src/components/proof/TakeComparisonDialog.tsx::takeComparisonState#1': row('mount', 'instant', 'dialog', 'dialog', 'dialog', 'inline', 'yes', 'ok', 'On opening Compare takes: a comparison already running (left in the background) is followed with its progress rather than started again; a failed read is an inline alert in the dialog.'),
  'src/components/proof/TakeComparisonDialog.tsx::takeComparisonStart#1': row('mount', 'job', 'dialog', 'host', 'dialog', 'inline', 'yes', 'ok', 'Starts the comparison of the group once per dialog (a ref guards a second effect run; the host refuses a second one anyway); the dialog says Starting until the job answers, then shows its progress. A refusal (the group or chapter changed, no manuscript) is an inline alert in the host words.'),
  'src/components/proof/TakeComparisonDialog.tsx::takeComparisonState#2': row('timer', 'instant', 'dialog', 'dialog', 'dialog', 'dialog', 'yes', 'ok', 'Polls every 500 ms while the comparison runs, showing the sidecar own percent and stage in WorkDialog (ADR 0015); the end is also a job:ended toast, so Continue in background loses nothing (ADR 0076).'),
  'src/components/proof/TakeComparisonDialog.tsx::takeComparisonCancel#1': row('click', 'instant', 'dialog', 'dialog', 'dialog', 'inline', 'no', 'ok', 'Cancel asks the sidecar to stop between takes and the job reports cancelled once it has; nothing is saved. A failed request is an inline alert.'),
  'src/components/proof/FindingDetail.tsx::manuscriptParagraphs#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'na', 'na', 'ok', 'Show in Script is busy while the finding paragraph is resolved to its line; if that read fails Script still opens at the chapter, and the Script page reports its own load failure.'),

  // Chapter workspace (edit-and-proof-workspace.prd.md Phase 2): the chapter, its linked track's items and its
  // stored alignment are all loaded together on mount; a failure in any of the first three (they run inside one
  // Promise.all) shows the same page-level inline error, since none of them is useful without the others.
  'src/components/proof/ProofChapterPage.tsx::manuscriptChapters#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Finds the chapter by id from the route; a failure shows the page\'s inline error.'),
  'src/components/proof/ProofChapterPage.tsx::chapterTrackMapList#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Finds the chapter\'s linked track, same as ChapterLinksTable\'s own read of the same binding.'),
  'src/components/proof/ProofChapterPage.tsx::tracksList#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The linked track\'s items, to build the playlist honouring their played ranges.'),
  'src/components/proof/ProofChapterPage.tsx::workspaceAlignment#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Reads the chapter\'s stored word alignment on open and again after a check completes (never runs one, Q14); a failure is the page\'s own inline error.'),
  'src/components/proof/ProofChapterPage.tsx::workspacePeaks#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'The waveform strip\'s peaks (edit-and-proof-workspace.prd.md Phase 5, ADR 0520), loaded alongside the alignment; not a narrator action to retry, and a failure just leaves the strip showing nothing this load, while the text, transport and flags (which do not depend on it) still work (interactionFeedback.catalog.ts SILENT_CATCHES).'),
  'src/components/proof/ProofChapterPage.tsx::subscribeCoverage#1': subscription('The recording check state, same subscription and job dialog (RecordingCheck) Home\'s own row uses.'),

  // Proof book-level waveform card (ADR 0715): the selected chapter's track, alignment and peaks are read together on mount and on every
  // chapter change; a failure in any of them shows the card's one inline alert, since a half-loaded waveform would mislead.
  'src/components/proof/ChapterWaveformCard.tsx::chapterTrackMapList#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The selected chapter track link, read with its items, alignment and peaks; a failure shows the card inline alert.'),
  'src/components/proof/ChapterWaveformCard.tsx::tracksList#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The linked track items, to build the playlist the waveform is laid out on; a failure shows the card inline alert.'),
  'src/components/proof/ChapterWaveformCard.tsx::workspaceAlignment#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The chapter stored alignment, for the flags marked on the waveform; a failure shows the card inline alert.'),
  'src/components/proof/ChapterWaveformCard.tsx::workspacePeaks#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The chapter stored peaks, the waveform itself; a failure shows the card inline alert rather than a made-up picture.'),

  // Findings in the text (edit-and-proof-workspace.prd.md Phase 4): the chapter's findings overlay onto the check's
  // own flags (findingFlags.ts's overlayFindings, a pure function - no host call, no row of its own).
  'src/components/proof/ProofChapterPage.tsx::findingsList#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Reads the chapter\'s findings for the text overlay, on open and again after a decision; not a narrator action to retry, and not swallowed silently since the check-derived flags (Phase 2) still show with nothing lost on a failure (interactionFeedback.catalog.ts SILENT_CATCHES).'),
  'src/components/proof/ProofChapterPage.tsx::findingsReview#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Pickup (or Fix in edit), Waive and Defer run one at a time through usePendingAction (FlagsPanel.tsx\'s FlagDecision, keyed by the flag\'s finding so a new selection gets a fresh note field): the pressed button is busy, the others are off, "Saved: ..." is announced and the findings reload, updating the flag\'s own decision line - the same binding FindingDetail.tsx uses, so it shows there too. A refusal is an inline alert in plain words.'),

  // Go to and Loop in REAPER for the word at the playhead (edit-and-proof-workspace.prd.md Phase 3, useWorkspaceReaper.ts):
  // the same round trip through the REAPER file bridge as the Review page's ReaperControls.tsx rows, over WorkspaceGoTo/
  // WorkspaceLoop/FindingsStopLoop instead of a finding's own bindings.
  // Apply FX to a passage (edit-and-proof-workspace.prd.md Phase 9, ApplyFxDialog.tsx): the confirm dialog reads what REAPER can add on opening, then sends once the narrator confirms.
  'src/components/proof/ApplyFxDialog.tsx::workspaceListFX#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Reads REAPER\'s installed effects when the dialog opens (a round trip through the file bridge, under 3 s); "Asking REAPER what it has…" shows meanwhile, and a REAPER that is away or has FX chains switched off is an inline alert in the dialog with nothing to choose.'),
  'src/components/proof/ApplyFxDialog.tsx::workspaceListFXChains#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Reads the narrator\'s saved FX chains when the chain dialog opens: the same wait and the same inline alert as the effects list.'),
  'src/components/proof/ApplyFxDialog.tsx::settingsForScope#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Reads the narrator\'s favourite effects (Settings, DAW) so they list first; a failed read only means no favourites, and the list still works.'),
  'src/components/proof/ApplyFxDialog.tsx::workspaceAddTakeFX#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Only after the narrator confirms with Add effect (the one action here that changes the REAPER project; one undo step): a bounded round trip over the bridge (under 3 s); every dialog control is off while pending, success closes the dialog and is announced with what REAPER did, and a refusal (two items, stale, recording, REAPER gone) is an inline alert in the host\'s words with nothing changed.'),
  'src/components/proof/ApplyFxDialog.tsx::workspaceApplyFXChain#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Only after the narrator confirms with Put chain on track (one undo step): the same wait, the same busy dialog, the same announcement on success and the same inline refusal wording as adding an effect.'),
  'src/components/proof/useWorkspaceReaper.ts::workspaceGoTo#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'A round trip through the REAPER file bridge (under 3 s): Go to is busy and Loop meanwhile off (usePendingAction); where REAPER put the cursor is announced, and a refusal (the word was not heard, recording, an older script, REAPER gone) is an inline alert in plain words. The move itself stays in REAPER.'),
  'src/components/proof/useWorkspaceReaper.ts::workspaceLoop#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Loop is busy while REAPER sets the loop and plays; the window is announced and Stop loop appears, reading status.loopingFindingId (workspace:<chapterId>:...) rather than local state, so it is shown again after the narrator leaves and comes back. A refusal is an inline alert in plain words.'),
  'src/components/proof/useWorkspaceReaper.ts::findingsStopLoop#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Stop loop is busy until REAPER has put back the time selection, loop points and repeat (shared with the book’s notes: one app loop at a time); a refusal is an inline alert and Stop stays offered.'),
  'src/components/proof/useWorkspaceReaper.ts::workspaceGoTo#2': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Go to for a selected flag\'s word (FlagsPanel.tsx, Phase 4), not necessarily the playhead\'s: its own pending key (tokenPending) keeps it apart from the transport bar\'s row above, so pressing one never shows the other as busy. Same round trip, same inline refusal wording.'),
  'src/components/proof/useWorkspaceReaper.ts::workspaceLoop#2': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Loop for a selected flag\'s word (FlagsPanel.tsx, Phase 4): same as workspaceLoop#1, its own pending key (workspaceGoTo#2\'s tokenPending), and Stop loop above stops it exactly as it stops the transport bar\'s own loop (one app loop at a time, status.loopingFindingId survives navigation the same way).'),

  // The compare run (CompareRun.tsx): Transcript Compare, moved from the retired Proofing page into the chapter view.
  'src/components/proof/CompareRun.tsx::transcriptHints#1': row('mount', 'file-io', 'na', 'na', 'ui', 'toast', 'na', 'ok', 'A failed load says so; the page stays usable.'),
  'src/components/proof/CompareRun.tsx::settingsForScope#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Reads the last model and chunk choice; the defaults stay usable and Settings reports a real error.'),
  'src/components/proof/CompareRun.tsx::transcriptSaveHints#1': row('click', 'file-io', 'none', 'none', 'ui', 'toast', 'na', 'ok', 'A small file write; the list has already changed.'),
  'src/components/proof/CompareRun.tsx::transcriptSuggestHints#1': row('click', 'file-io', 'none', 'none', 'toast', 'toast', 'na', 'ok', 'Derived from the Story Bible in Go: fast, and the toast is the result.'),
  'src/components/proof/CompareRun.tsx::transcriptStart#1': row('click', 'job', 'dialog', 'host', 'toast', 'toast', 'yes', 'ok', 'The phase moves to preparing from the state event and the host refuses a second run. Its end is announced by a job-end event whichever page the narrator is on (ADR 0076).'),
  'src/components/proof/CompareRun.tsx::whisperInstall#1': row('click', 'download', 'dialog', 'host', 'dialog', 'dialog', 'no', 'ok', 'The first-use dialog says Starting at once; the host joins a download that is already running for the same asset (S16), so a second press starts no second one. Real bytes, the check, Cancel while bytes arrive, and a failure sentence in the dialog, through useAssetInstall.'),
  'src/components/proof/CompareRun.tsx::whisperInstallState#1': row('timer', 'download', 'dialog', 'na', 'poll', 'dialog', 'no', 'ok', 'The one install-poll loop (useAssetInstall), every 400 ms: the dialog shows the bytes as they arrive, and a failed poll is shown in the dialog. The download outlives the dialog and ends with job:ended.'),
  'src/components/proof/CompareRun.tsx::whisperInstallCancel#1': row('click', 'download', 'dialog', 'dialog', 'dialog', 'dialog', 'no', 'ok', 'Cancel stops the download and the dialog says it was cancelled; it is drawn only while bytes arrive, and a failed cancel is shown in the dialog.'),
  'src/components/proof/CompareRun.tsx::transcriptReset#1': row('click', 'instant', 'none', 'none', 'ui', 'toast', 'na', 'exempt', 'A demo-only button, rendered in the mock build (`import.meta.env.MODE === "mock"`).'),
  'src/components/proof/CompareRun.tsx::transcriptCancel#1': row('click', 'instant', 'pending', 'pending', 'ui', 'toast', 'na', 'ok', 'Cancel is busy until the host answers and a refused cancel is a toast (phase 6).'),
  'src/components/proof/CompareRun.tsx::transcriptReset#2': row('click', 'instant', 'none', 'none', 'ui', 'toast', 'na', 'ok', 'Leaving the results resets the run; a refusal is a toast (phase 6).'),
  'src/components/proof/PreviewPanel.tsx::previewCandidates#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Read alongside manuscriptChapters (Promise.all); a failed read shows an inline alert with the reason instead of an empty or stale panel (proofing-preview-suggestion.prd.md Phase 3).'),
  // The narrator's pin (Phase 8): settling on a candidate and moving its edges.
  'src/components/proof/PreviewPanel.tsx::previewPin#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Read in the same Promise.all as previewCandidates and manuscriptChapters, so a failed read shows the panel\'s one inline alert rather than a silently missing pinned section.'),
  'src/components/proof/PreviewPanel.tsx::previewPinSet#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'toast', 'no', 'ok', 'Pin on a candidate row (or Unpin, via previewPinClear below, when that row is already the pinned one): every pin/adjust/clear action shares one busy flag so two never overlap. Success re-renders the pinned section from the binding\'s own fresh answer; a refusal is a toast.'),
  'src/components/proof/PreviewPanel.tsx::previewPinAdjust#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'toast', 'no', 'ok', 'The pinned section\'s Start/End +/- controls: disabled once that edge already reaches the chapter\'s boundary or the range is down to one paragraph (canExtendStart etc.), so a press here always changes something. Same shared busy flag and toast-on-refusal as previewPinSet.'),
  'src/components/proof/PreviewPanel.tsx::previewPinClear#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'toast', 'no', 'ok', 'The pinned section\'s ✕, or Unpin on the pinned candidate\'s own row; clearing when nothing is pinned is not an error, though the buttons that would do it are not shown then.'),
  'src/components/proof/PreviewPanel.tsx::manuscriptChapters#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Read alongside previewCandidates, only to resolve a candidate\'s paragraph ids to a global index for "open in reader" and "copy range"; a failed read shares the same inline alert as previewCandidates above.'),
  // The readiness panel's rendered-file section (proofing-readiness-signals.prd.md Phase 6): the chapter itself is
  // the parent ChapterView's own load, so this panel reads no chapter list of its own.
  'src/components/proof/useProofingRender.ts::proofingRenderState#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Reads the chapter\'s render association on mount and after Choose, Clear or Measure; a failed read shows an inline alert instead of a stale "Rendered file" section.'),
  'src/components/proof/useProofingRender.ts::proofingChooseRender#1': row('click', 'os-dialog', 'pending', 'pending', 'ui', 'toast', 'na', 'ok', 'Choose is busy while the native file dialog is open and the file is attested; a cancelled dialog changes nothing, and a refusal (an unreadable file, no confirmed track) is a toast.'),
  'src/components/proof/useProofingRender.ts::proofingClearRender#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'toast', 'na', 'ok', 'Clear is busy until the association is removed; a failed write is a toast and the previous association stays shown.'),
  'src/components/proof/useProofingRender.ts::measureAnalyze#1': row('click', 'job', 'pending', 'pending', 'poll', 'toast', 'na', 'ok', 'Measure starts the existing measurement job (DX-1) on the chosen render, already marked measurable by Choose; Measure is busy while it polls measureState to the end, then the association is read again to show the recorded result.'),
  'src/components/proof/useProofingRender.ts::measureState#1': row('timer', 'instant', 'pending', 'pending', 'poll', 'toast', 'na', 'ok', 'Polled every 500 ms while Measure runs (DeliveryPage.tsx\'s own POLL_MS); a failed poll ends Measure with a toast, and a job that itself errors is announced by its own message.'),

  // Transcript Compare's results as the chapter view's flags (stage-navigation-and-page-replacement.prd.md Phase 5), moved
  // from the retired Proofing page's Results table: marker export stays with the run, the per-row actions sit in the flag
  // detail (FlagsPanel.tsx's CompareActions).
  'src/components/proof/CompareRun.tsx::transcriptExportMarkers#1': row('click', 'job', 'disabled', 'disabled', 'ui', 'toast', 'na', 'ok', 'The button turns into "Exporting…" and disables from the transcript state event.'),
  // "May have changed since comparison" (reaper-automation-follow-through PRD Phase 13): a background hint only, while results
  // are shown, against REAPER's own edit counter. It never blocks or fails visibly - a quiet miss just tries again next poll -
  // since the whole point is a soft nudge, never a claim of certainty (the counter resets when the project reopens).
  'src/components/proof/CompareRun.tsx::subscribeProjectState#1': row('effect', 'subscription', 'na', 'na', 'event', 'na', 'na', 'exempt', 'Subscribed only while results are shown and the comparison has a baseline count; reads REAPER\'s answer to each low-frequency check, compared below. Nothing to acknowledge: it drives a background hint, not a narrator action.'),
  'src/components/proof/CompareRun.tsx::projectStateCheck#1': row('timer', 'instant', 'na', 'na', 'event', 'silent', 'na', 'exempt', 'Asks REAPER for its edit count every 30 s while results are shown (PROJECT_STATE_POLL_MS); the answer arrives through the projectstate:state subscription above. A failed ask just skips this poll - REAPER being closed or between projects is routine, not a narrator-facing failure - and tries again next cycle.'),
  'src/components/proof/CompareRun.tsx::projectStateChangedSince#1': row('event', 'instant', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Compares a successful check\'s count with the comparison\'s own baseline; a match or a fresh checked answer shows or clears the "may have changed" note. A failed compare is quiet, same reasoning as the check above.'),
  'src/components/proof/ProofChapterPage.tsx::transcriptJump#1': row('click', 'instant', 'none', 'none', 'ui', 'toast', 'na', 'ok', 'Play recorded audio in a compare flag\'s detail; a failed jump (REAPER not running) is a toast (phase 6).'),
  'src/components/proof/ProofChapterPage.tsx::transcriptAddEquivalence#1': row('click', 'file-io', 'none', 'none', 'toast', 'toast', 'na', 'ok', 'A small file write from a compare flag\'s detail; the toast is the result.'),
  'src/components/proof/ProofChapterPage.tsx::transcriptLastCompleted#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Only offers to review the last run; without it the offer is absent.'),
  // The book level's chapter picker (ProofPage.tsx).
  'src/components/proof/ProofPage.tsx::manuscriptChapters#1': row('mount', 'file-io', 'na', 'na', 'ui', 'toast', 'na', 'ok', 'Fills the chapter picker; a failed read is a toast and the picker is left out, while the notes (read separately) still show.'),
};
