// The interaction feedback rows for Proof's call sites (see interactionFeedback.catalog.ts for what a row says): the book's notes
// (the Review page until stage-navigation-and-page-replacement.prd.md Phase 5), the chapter view (the chapter workspace) and its
// compare run (the Proofing page).
import { type FeedbackRow, row, subscription } from './row';

// prettier-ignore
export const proofFeedback: Record<string, FeedbackRow> = {
  // Review page (review-dashboard-and-findings-adoption.prd.md, Phase 5)
  'src/components/proof/ProofPage.tsx::findingsSummary#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'Read together with the list: the first load failing is the page load error with Retry, a later one (after a filter change or a decision) is a toast and the list on screen stays.'),
  'src/components/proof/ProofPage.tsx::findingsList#1': row('input', 'file-io', 'na', 'na', 'ui', 'toast', 'na', 'ok', 'Runs on opening and on every filter, sort or Show more change; an answer to an older request is dropped, the first load failing is the page load error with Retry and a later one is a toast.'),
  'src/components/proof/FindingDetail.tsx::findingsReview#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Accept, Dismiss, Defer and Reopen run one at a time through usePendingAction: the pressed button is busy, the others are off, "Saved as ..." is announced and the list and counts reload. A refusal is an inline alert: on changed evidence (ADR 0120) it says so in plain words and shows the latest version, otherwise it gives the host reason.'),
  'src/components/proof/FindingDetail.tsx::findingsGet#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Only after a refused decision, to tell changed evidence from any other refusal; if it fails too, the inline alert gives the host reason for the refusal.'),
  'src/components/proof/useReaperStatus.ts::findingsReaperStatus#1': row('timer', 'instant', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Read on opening Proof and every 3 s while it is open, from the heartbeat REAPER already sends (nothing is sent to REAPER); a failed read counts as not connected and is the reason shown under the disabled Go to and Loop.'),
  'src/components/proof/ReaperControls.tsx::findingsGoTo#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'A round trip through the REAPER file bridge (under 3 s): Go to is busy and Loop and Stop are off meanwhile (usePendingAction); where REAPER put the cursor is announced, and a refusal (stale finding, recording, older script, REAPER gone) is an inline alert in plain words. The move itself stays in REAPER.'),
  'src/components/proof/ReaperControls.tsx::findingsLoop#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Loop is busy while REAPER sets the loop and plays; the window is announced and Stop loop appears (the page status names the looping finding, so the loop is shown again after the narrator leaves and comes back). A refusal is an inline alert in plain words.'),
  'src/components/proof/ReaperControls.tsx::findingsStopLoop#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Stop loop is busy until REAPER has put back the time selection, loop points and repeat; what came back (or was kept because the narrator changed it) is announced, and a refusal is an inline alert and Stop stays offered.'),
  'src/components/proof/ReaperControls.tsx::findingsAddMarker#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Only after the narrator confirms in the Add a marker in REAPER dialog (the one REAPER action here that changes the project): its Add marker is busy and Cancel is off until REAPER answers (under 3 s), then the dialog closes; the marker added (or the one already there) is announced, and a refusal (not accepted, stale finding, recording, older script, REAPER gone) is an inline alert in plain words. The marker itself stays in REAPER, undoable there.'),
  'src/components/proof/ProofPage.tsx::subscribeJobEnded#1': subscription('A pickup and duplicate scan or a take comparison left running in the background reloads the list and counts when it ends, so its groups or comparison appear without leaving the page (take review Phases 5 and 10).'),
  'src/components/proof/TakeReviewScanDialog.tsx::takeReviewScanState#1': row('mount', 'instant', 'na', 'na', 'ui', 'inline', 'yes', 'ok', 'On opening the scan dialog: a scan still running (left in the background) is shown with its progress; otherwise the form is offered with the project saved pickup scope. A failed read is an inline alert in the dialog.'),
  'src/components/proof/TakeReviewScanDialog.tsx::tracksList#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Fills the track pickers from the REAPER project file (about 2 ms); when it cannot be read the dialog says why inline and Start scan stays off.'),
  'src/components/proof/TakeReviewScanDialog.tsx::takeReviewScanState#2': row('timer', 'instant', 'dialog', 'dialog', 'dialog', 'dialog', 'yes', 'ok', 'Polls every 500 ms while the scan runs, showing the sidecar own percent and stage in WorkDialog (ADR 0015); the end is also a job:ended toast, so Continue in background loses nothing (ADR 0076).'),
  'src/components/proof/TakeReviewScanDialog.tsx::takeReviewScanStart#1': row('click', 'job', 'pending', 'host', 'dialog', 'inline', 'yes', 'ok', 'Start scan is busy while the host checks the scope and starts the job, then the dialog becomes the progress view; a refused scope or a scan already running is an inline alert in the form, in the host words.'),
  'src/components/proof/TakeReviewScanDialog.tsx::takeReviewScanCancel#1': row('click', 'instant', 'dialog', 'dialog', 'dialog', 'inline', 'no', 'ok', 'Cancel asks the sidecar to stop and the job reports cancelled once it has; nothing it found is saved. A failed request is an inline alert.'),
  'src/components/proof/TakeReviewReads.tsx::takeReviewCreateTake#1': row('click', 'job', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Add as take, after the confirm (phase 6): a bounded round trip to REAPER over the bridge. Every dialog control is off while pending; the new take is announced under the reads, and a stale item or REAPER failure is an inline alert inside the dialog, which stays open.'),
  'src/components/proof/useReadNavigation.ts::findingsGoToRead#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Go to on one read of a take-review group or a take comparison: a round trip through the REAPER file bridge, the pressed button busy and the other read controls off meanwhile (usePendingAction); where the cursor went is announced, a refusal is an inline alert in plain words.'),
  'src/components/proof/useReadNavigation.ts::findingsLoopRead#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Loop on one read: busy while REAPER sets the loop and plays; the window is announced and Stop loop appears (the page status names the looping finding, so it shows again after leaving and coming back).'),
  'src/components/proof/useReadNavigation.ts::findingsStopLoop#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Stop loop under the reads is busy until REAPER has put back the time selection, loop points and repeat; what came back is announced and a refusal is an inline alert.'),
  'src/components/proof/ProofPage.tsx::findingsGet#1': row('event', 'file-io', 'na', 'na', 'ui', 'toast', 'yes', 'ok', 'After a finished take comparison is closed: the list is narrowed to take comparisons and the new comparison is read and opened beside it; a failed read is a toast and the narrowed list still shows it.'),
  'src/components/proof/TakeComparisonDialog.tsx::takeComparisonState#1': row('mount', 'instant', 'dialog', 'dialog', 'dialog', 'inline', 'yes', 'ok', 'On opening Compare takes: a comparison already running (left in the background) is followed with its progress rather than started again; a failed read is an inline alert in the dialog.'),
  'src/components/proof/TakeComparisonDialog.tsx::takeComparisonStart#1': row('mount', 'job', 'dialog', 'host', 'dialog', 'inline', 'yes', 'ok', 'Starts the comparison of the group once per dialog (a ref guards a second effect run; the host refuses a second one anyway); the dialog says Starting until the job answers, then shows its progress. A refusal (the group or chapter changed, no manuscript) is an inline alert in the host words.'),
  'src/components/proof/TakeComparisonDialog.tsx::takeComparisonState#2': row('timer', 'instant', 'dialog', 'dialog', 'dialog', 'dialog', 'yes', 'ok', 'Polls every 500 ms while the comparison runs, showing the sidecar own percent and stage in WorkDialog (ADR 0015); the end is also a job:ended toast, so Continue in background loses nothing (ADR 0076).'),
  'src/components/proof/TakeComparisonDialog.tsx::takeComparisonCancel#1': row('click', 'instant', 'dialog', 'dialog', 'dialog', 'inline', 'no', 'ok', 'Cancel asks the sidecar to stop between takes and the job reports cancelled once it has; nothing is saved. A failed request is an inline alert.'),
  'src/components/proof/FindingDetail.tsx::manuscriptParagraphs#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'na', 'na', 'ok', 'Show in manuscript is busy while the finding paragraph is resolved to its line; if that read fails the manuscript still opens at the chapter, and the manuscript page reports its own load failure.'),

  // Chapter workspace (edit-and-proof-workspace.prd.md Phase 2): the chapter, its linked track's items and its
  // stored alignment are all loaded together on mount; a failure in any of the first three (they run inside one
  // Promise.all) shows the same page-level inline error, since none of them is useful without the others.
  'src/components/proof/ProofChapterPage.tsx::manuscriptChapters#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Finds the chapter by id from the route; a failure shows the page\'s inline error.'),
  'src/components/proof/ProofChapterPage.tsx::chapterTrackMapList#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Finds the chapter\'s linked track, same as ChapterLinksTable\'s own read of the same binding.'),
  'src/components/proof/ProofChapterPage.tsx::tracksList#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The linked track\'s items, to build the playlist honouring their played ranges.'),
  'src/components/proof/ProofChapterPage.tsx::workspaceAlignment#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Reads the chapter\'s stored word alignment on open and again after a check completes (never runs one, Q14); a failure is the page\'s own inline error.'),
  'src/components/proof/ProofChapterPage.tsx::subscribeCoverage#1': subscription('The recording check state, same subscription and job dialog (RecordingCheck) Home\'s own row uses.'),

  // Findings in the text (edit-and-proof-workspace.prd.md Phase 4): the chapter's findings overlay onto the check's
  // own flags (findingFlags.ts's overlayFindings, a pure function - no host call, no row of its own).
  'src/components/proof/ProofChapterPage.tsx::findingsList#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Reads the chapter\'s findings for the text overlay, on open and again after a decision; not a narrator action to retry, and not swallowed silently since the check-derived flags (Phase 2) still show with nothing lost on a failure (interactionFeedback.catalog.ts SILENT_CATCHES).'),
  'src/components/proof/ProofChapterPage.tsx::findingsReview#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Accept, Dismiss and Defer run one at a time through usePendingAction (FlagsPanel.tsx\'s FlagDecision, keyed by the flag\'s finding so a new selection gets a fresh note field): the pressed button is busy, the others are off, "Saved as ..." is announced and the findings reload, updating the flag\'s own decision line - the same binding FindingDetail.tsx uses, so it shows there too. A refusal is an inline alert in plain words.'),

  // Go to and Loop in REAPER for the word at the playhead (edit-and-proof-workspace.prd.md Phase 3, useWorkspaceReaper.ts):
  // the same round trip through the REAPER file bridge as the Review page's ReaperControls.tsx rows, over WorkspaceGoTo/
  // WorkspaceLoop/FindingsStopLoop instead of a finding's own bindings.
  'src/components/proof/useWorkspaceReaper.ts::workspaceGoTo#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'A round trip through the REAPER file bridge (under 3 s): Go to is busy and Loop meanwhile off (usePendingAction); where REAPER put the cursor is announced, and a refusal (the word was not heard, recording, an older script, REAPER gone) is an inline alert in plain words. The move itself stays in REAPER.'),
  'src/components/proof/useWorkspaceReaper.ts::workspaceLoop#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Loop is busy while REAPER sets the loop and plays; the window is announced and Stop loop appears, reading status.loopingFindingId (workspace:<chapterId>:...) rather than local state, so it is shown again after the narrator leaves and comes back. A refusal is an inline alert in plain words.'),
  'src/components/proof/useWorkspaceReaper.ts::findingsStopLoop#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Stop loop is busy until REAPER has put back the time selection, loop points and repeat (shared with the book’s notes: one app loop at a time); a refusal is an inline alert and Stop stays offered.'),
  'src/components/proof/useWorkspaceReaper.ts::workspaceGoTo#2': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Go to for a selected flag\'s word (FlagsPanel.tsx, Phase 4), not necessarily the playhead\'s: its own pending key (tokenPending) keeps it apart from the transport bar\'s row above, so pressing one never shows the other as busy. Same round trip, same inline refusal wording.'),
  'src/components/proof/useWorkspaceReaper.ts::workspaceLoop#2': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Loop for a selected flag\'s word (FlagsPanel.tsx, Phase 4): same as workspaceLoop#1, its own pending key (workspaceGoTo#2\'s tokenPending), and Stop loop above stops it exactly as it stops the transport bar\'s own loop (one app loop at a time, status.loopingFindingId survives navigation the same way).'),

  // The compare run (CompareRun.tsx): Transcript Compare, moved from the retired Proofing page into the chapter view.
  'src/components/proof/CompareRun.tsx::transcriptHints#1': row('mount', 'file-io', 'na', 'na', 'ui', 'toast', 'na', 'ok', 'A failed load says so; the page stays usable.'),
  'src/components/proof/CompareRun.tsx::settingsForScope#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Reads the last model and chunk choice; the defaults stay usable and Settings reports a real error.'),
  'src/components/proof/CompareRun.tsx::transcriptSaveHints#1': row('click', 'file-io', 'none', 'none', 'ui', 'toast', 'na', 'ok', 'A small file write; the list has already changed.'),
  'src/components/proof/CompareRun.tsx::transcriptSuggestHints#1': row('click', 'file-io', 'none', 'none', 'toast', 'toast', 'na', 'ok', 'Derived from the Story Bible in Go: fast, and the toast is the result.'),
  'src/components/proof/CompareRun.tsx::transcriptStart#1': row('click', 'job', 'dialog', 'host', 'toast', 'toast', 'yes', 'ok', 'The phase moves to preparing from the state event and the host refuses a second run. Its end is announced by a job-end event whichever page the narrator is on (ADR 0076).'),
  'src/components/proof/CompareRun.tsx::whisperInstall#1': row('click', 'download', 'dialog', 'host', 'dialog', 'dialog', 'no', 'ok', 'The first-use dialog says Starting at once; the host joins a download that is already running for the same asset (S16), so a second press starts no second one. Real bytes, the check, Cancel while bytes arrive, and a failure sentence in the dialog, through useAssetInstall.'),
  'src/components/proof/CompareRun.tsx::whisperInstallState#1': row('timer', 'download', 'dialog', 'na', 'poll', 'dialog', 'no', 'ok', 'The one install-poll loop (useAssetInstall), every 400 ms: the dialog shows the bytes as they arrive, and a failed poll is shown in the dialog. The download outlives the dialog and ends with job:ended.'),
  'src/components/proof/CompareRun.tsx::whisperInstallCancel#1': row('click', 'download', 'dialog', 'dialog', 'dialog', 'dialog', 'no', 'ok', 'Cancel stops the download and the dialog says it was cancelled; it is drawn only while bytes arrive, and a failed cancel is shown in the dialog.'),
  'src/components/proof/CompareRun.tsx::transcriptReset#1': row('click', 'instant', 'none', 'none', 'ui', 'toast', 'na', 'exempt', 'A demo-only button, rendered in the mock build (`import.meta.env.MODE === "mock"`).'),
  'src/components/proof/CompareRun.tsx::transcriptCancel#1': row('click', 'instant', 'pending', 'pending', 'ui', 'toast', 'na', 'ok', 'Cancel is busy until the host answers and a refused cancel is a toast (phase 6).'),
  'src/components/proof/CompareRun.tsx::transcriptReset#2': row('click', 'instant', 'none', 'none', 'ui', 'toast', 'na', 'ok', 'Leaving the results resets the run; a refusal is a toast (phase 6).'),
  'src/components/proof/PreviewPanel.tsx::previewCandidates#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Read alongside manuscriptChapters (Promise.all); a failed read shows an inline alert with the reason instead of an empty or stale panel (proofing-preview-suggestion.prd.md Phase 3).'),
  'src/components/proof/PreviewPanel.tsx::manuscriptChapters#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Read alongside previewCandidates, only to resolve a candidate\'s paragraph ids to a global index for "open in reader" and "copy range"; a failed read shares the same inline alert as previewCandidates above.'),
  'src/components/proof/ProofingStagePanel.tsx::manuscriptChapters#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Only to filter to the chapters currently in Proofing and label their rows; the stage suggestions themselves come from useStageRecommendations (already catalogued from Home). A failed read shows an inline alert with the reason instead of an empty or stale panel (chapter-stage-recommendations.prd.md Phase 8).'),

  // Transcript Compare's results as the chapter view's flags (stage-navigation-and-page-replacement.prd.md Phase 5), moved
  // from the retired Proofing page's Results table: marker export stays with the run, the per-row actions sit in the flag
  // detail (FlagsPanel.tsx's CompareActions).
  'src/components/proof/CompareRun.tsx::transcriptExportMarkers#1': row('click', 'job', 'disabled', 'disabled', 'ui', 'toast', 'na', 'ok', 'The button turns into "Exporting…" and disables from the transcript state event.'),
  'src/components/proof/ProofChapterPage.tsx::transcriptJump#1': row('click', 'instant', 'none', 'none', 'ui', 'toast', 'na', 'ok', 'Play recorded audio in a compare flag\'s detail; a failed jump (REAPER not running) is a toast (phase 6).'),
  'src/components/proof/ProofChapterPage.tsx::transcriptAddEquivalence#1': row('click', 'file-io', 'none', 'none', 'toast', 'toast', 'na', 'ok', 'A small file write from a compare flag\'s detail; the toast is the result.'),
  'src/components/proof/ProofChapterPage.tsx::transcriptLastCompleted#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Only offers to review the last run; without it the offer is absent.'),
  // The book level's chapter picker (ProofPage.tsx).
  'src/components/proof/ProofPage.tsx::manuscriptChapters#1': row('mount', 'file-io', 'na', 'na', 'ui', 'toast', 'na', 'ok', 'Fills the chapter picker; a failed read is a toast and the picker is left out, while the notes (read separately) still show.'),
};
