// The built-in recorder's calls (native-recording-suite PRD Phase 2, ADR 0455): the Booth's Record surface with the project
// on "Built-in recorder" (components/booth/useRecorder.ts, BuiltinRecorder.tsx).
import { row, startup, subscription } from './row';

export const recordingFeedback = {
  'src/components/booth/useRecorder.ts::recorderState#1': startup(
    "The engine chip's first reading of the project's recording engine; a failure leaves the chip on REAPER, the default, and the Booth reports the recorder's own error.",
  ),
  'src/components/booth/useRecorder.ts::recorderState#2': startup('The Booth recorder\'s first state; a failure shows inline under "Record with".'),
  'src/components/booth/useRecorder.ts::subscribeRecorderState#1': subscription("The engine chip follows the project's recording engine."),
  'src/components/booth/useRecorder.ts::subscribeRecorderState#2': subscription("The recorder's phase, the take recording and the takes list."),
  'src/components/booth/useRecorder.ts::subscribeRecorderLevel#1': subscription(
    "The recorder's live level: the status line's meter and peak readout, and the setup's meter.",
  ),
  'src/components/booth/useRecorder.ts::recorderDevices#1': row(
    'effect',
    'python',
    'na',
    'na',
    'ui',
    'inline',
    'na',
    'ok',
    "Lists the recorder's input devices when the project chooses the built-in recorder, and on Refresh (pending); a listing problem is the picker's own inline message, never a thrown error.",
  ),
  'src/components/booth/useRecorder.ts::recorderChooseEngine#1': row(
    'click',
    'file-io',
    'pending',
    'pending',
    'ui',
    'inline',
    'yes',
    'ok',
    '"Record with" saves the project\'s engine (Recording.engine); the chip and the Booth change with the answer, and a refusal (the row unavailable, a take recording) shows inline.',
  ),
  'src/components/booth/useRecorder.ts::recorderStart#1': row(
    'click',
    'python',
    'pending',
    'pending',
    'event',
    'inline',
    'no',
    'ok',
    'Record starts a take: the button turns into "REC 00:00" and the status line into "REC · Built-in"; a refusal (a device that will not open) shows inline. Leaving the Booth stops the take, which is saved.',
  ),
  'src/components/booth/useRecorder.ts::recorderStop#1': row(
    'click',
    'python',
    'pending',
    'pending',
    'event',
    'inline',
    'no',
    'ok',
    'Stop ends the take: the button is pending while it finishes, then the take appears at the top of the Takes list; a take that ended by itself is said once there.',
  ),
  'src/components/booth/useRecorder.ts::recorderMeterStart#1': row(
    'input',
    'python',
    'na',
    'host',
    'event',
    'inline',
    'na',
    'ok',
    'Choosing another input while the level check runs moves the check to it; the meter shows it working, an inline alert otherwise.',
  ),
  'src/components/booth/useRecorder.ts::recorderMeterStart#2': row(
    'click',
    'python',
    'pending',
    'pending',
    'event',
    'inline',
    'no',
    'ok',
    'Check level meters the chosen input before a take (no file is written); the meter moves, and a refusal shows inline.',
  ),
  'src/components/booth/useRecorder.ts::recorderMeterStop#1': row(
    'click',
    'python',
    'pending',
    'pending',
    'ui',
    'inline',
    'no',
    'ok',
    'Stop level check releases the input; the button reads "Check level" again.',
  ),
  'src/components/booth/useRecorder.ts::recorderStop#2': row(
    'effect',
    'python',
    'na',
    'na',
    'event',
    'silent',
    'na',
    'exempt',
    'Leaving the Booth stops a take so it never records on unseen; the take is saved, and the Takes list shows it when the Booth is back (SILENT_CATCHES).',
  ),
  'src/components/booth/useRecorder.ts::recorderMeterStop#2': row(
    'effect',
    'python',
    'na',
    'na',
    'event',
    'silent',
    'na',
    'exempt',
    'Leaving the Booth releases a level check; nothing is left mounted to tell (SILENT_CATCHES).',
  ),
  'src/components/booth/BuiltinRecorder.tsx::mediaUrl#1': row(
    'click',
    'instant',
    'inline',
    'none',
    'ui',
    'inline',
    'no',
    'ok',
    'Play builds the take\'s media URL (a string, no host call); the button turns into Stop, and a file that will not play says "Could not play" beside it.',
  ),
  'src/components/proof/NativeTakesPanel.tsx::recorderState#1': startup(
    "The panel's first read of the chapter's native takes; a failure leaves it unrendered until the next recording:state event (subscribeRecorderState) catches up.",
  ),
  'src/components/proof/NativeTakesPanel.tsx::subscribeRecorderState#1': subscription(
    'The chapter’s native takes, their line assignments and keeper marks, live.',
  ),
  'src/components/proof/NativeTakesPanel.tsx::recorderSetTakeLine#1': row(
    'click',
    'file-io',
    'pending',
    'pending',
    'ui',
    'inline',
    'yes',
    'ok',
    "Assign writes the take's line identity (native-recording-suite PRD Phase 3's SetTakeLine, first reachable from the UI here); the take moves under that line's heading, and a refusal shows inline.",
  ),
  'src/components/proof/NativeTakesPanel.tsx::recorderSetTakeKeeper#1': row(
    'click',
    'file-io',
    'pending',
    'pending',
    'ui',
    'inline',
    'yes',
    'ok',
    "Mark keeper / Keeper ✓ (undo) sets or clears the take's keeper mark, handing it over from any other take of the same line; a refusal shows inline.",
  ),
  'src/components/proof/NativeTakesPanel.tsx::mediaUrl#1': row(
    'click',
    'instant',
    'inline',
    'none',
    'ui',
    'inline',
    'no',
    'ok',
    "Play builds the take's media URL (a string, no host call); the button turns into Stop, the same as BuiltinRecorder.tsx::mediaUrl#1.",
  ),
};
