// The interaction feedback rows for the review call sites (see interactionFeedback.catalog.ts for what a row says).
import { type FeedbackRow, row, subscription } from './row';

// prettier-ignore
export const reviewFeedback: Record<string, FeedbackRow> = {
  // Review page (review-dashboard-and-findings-adoption.prd.md, Phase 5)
  'src/components/review/ReviewPage.tsx::findingsSummary#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'Read together with the list: the first load failing is the page load error with Retry, a later one (after a filter change or a decision) is a toast and the list on screen stays.'),
  'src/components/review/ReviewPage.tsx::findingsList#1': row('input', 'file-io', 'na', 'na', 'ui', 'toast', 'na', 'ok', 'Runs on opening and on every filter, sort or Show more change; an answer to an older request is dropped, the first load failing is the page load error with Retry and a later one is a toast.'),
  'src/components/review/FindingDetail.tsx::findingsReview#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Accept, Dismiss, Defer and Reopen run one at a time through usePendingAction: the pressed button is busy, the others are off, "Saved as ..." is announced and the list and counts reload. A refusal is an inline alert: on changed evidence (ADR 0120) it says so in plain words and shows the latest version, otherwise it gives the host reason.'),
  'src/components/review/FindingDetail.tsx::findingsGet#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Only after a refused decision, to tell changed evidence from any other refusal; if it fails too, the inline alert gives the host reason for the refusal.'),
  'src/components/review/useReaperStatus.ts::findingsReaperStatus#1': row('timer', 'instant', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Read on opening the Review page and every 3 s while it is open, from the heartbeat REAPER already sends (nothing is sent to REAPER); a failed read counts as not connected and is the reason shown under the disabled Go to and Loop.'),
  'src/components/review/ReaperControls.tsx::findingsGoTo#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'A round trip through the REAPER file bridge (under 3 s): Go to is busy and Loop and Stop are off meanwhile (usePendingAction); where REAPER put the cursor is announced, and a refusal (stale finding, recording, older script, REAPER gone) is an inline alert in plain words. The move itself stays in REAPER.'),
  'src/components/review/ReaperControls.tsx::findingsLoop#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Loop is busy while REAPER sets the loop and plays; the window is announced and Stop loop appears (the page status names the looping finding, so the loop is shown again after the narrator leaves and comes back). A refusal is an inline alert in plain words.'),
  'src/components/review/ReaperControls.tsx::findingsStopLoop#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Stop loop is busy until REAPER has put back the time selection, loop points and repeat; what came back (or was kept because the narrator changed it) is announced, and a refusal is an inline alert and Stop stays offered.'),
  'src/components/review/ReaperControls.tsx::findingsAddMarker#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Only after the narrator confirms in the Add a marker in REAPER dialog (the one REAPER action here that changes the project): its Add marker is busy and Cancel is off until REAPER answers (under 3 s), then the dialog closes; the marker added (or the one already there) is announced, and a refusal (not accepted, stale finding, recording, older script, REAPER gone) is an inline alert in plain words. The marker itself stays in REAPER, undoable there.'),
  'src/components/review/ReviewPage.tsx::subscribeJobEnded#1': subscription('A pickup and duplicate scan or a take comparison left running in the background reloads the list and counts when it ends, so its groups or comparison appear without leaving the page (take review Phases 5 and 10).'),
  'src/components/review/TakeReviewScanDialog.tsx::takeReviewScanState#1': row('mount', 'instant', 'na', 'na', 'ui', 'inline', 'yes', 'ok', 'On opening the scan dialog: a scan still running (left in the background) is shown with its progress; otherwise the form is offered with the project saved pickup scope. A failed read is an inline alert in the dialog.'),
  'src/components/review/TakeReviewScanDialog.tsx::tracksList#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Fills the track pickers from the REAPER project file (about 2 ms); when it cannot be read the dialog says why inline and Start scan stays off.'),
  'src/components/review/TakeReviewScanDialog.tsx::takeReviewScanState#2': row('timer', 'instant', 'dialog', 'dialog', 'dialog', 'dialog', 'yes', 'ok', 'Polls every 500 ms while the scan runs, showing the sidecar own percent and stage in WorkDialog (ADR 0015); the end is also a job:ended toast, so Continue in background loses nothing (ADR 0076).'),
  'src/components/review/TakeReviewScanDialog.tsx::takeReviewScanStart#1': row('click', 'job', 'pending', 'host', 'dialog', 'inline', 'yes', 'ok', 'Start scan is busy while the host checks the scope and starts the job, then the dialog becomes the progress view; a refused scope or a scan already running is an inline alert in the form, in the host words.'),
  'src/components/review/TakeReviewScanDialog.tsx::takeReviewScanCancel#1': row('click', 'instant', 'dialog', 'dialog', 'dialog', 'inline', 'no', 'ok', 'Cancel asks the sidecar to stop and the job reports cancelled once it has; nothing it found is saved. A failed request is an inline alert.'),
  'src/components/review/TakeReviewReads.tsx::takeReviewCreateTake#1': row('click', 'job', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Add as take, after the confirm (phase 6): a bounded round trip to REAPER over the bridge. Every dialog control is off while pending; the new take is announced under the reads, and a stale item or REAPER failure is an inline alert inside the dialog, which stays open.'),
  'src/components/review/useReadNavigation.ts::findingsGoToRead#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Go to on one read of a take-review group or a take comparison: a round trip through the REAPER file bridge, the pressed button busy and the other read controls off meanwhile (usePendingAction); where the cursor went is announced, a refusal is an inline alert in plain words.'),
  'src/components/review/useReadNavigation.ts::findingsLoopRead#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'yes', 'ok', 'Loop on one read: busy while REAPER sets the loop and plays; the window is announced and Stop loop appears (the page status names the looping finding, so it shows again after leaving and coming back).'),
  'src/components/review/useReadNavigation.ts::findingsStopLoop#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Stop loop under the reads is busy until REAPER has put back the time selection, loop points and repeat; what came back is announced and a refusal is an inline alert.'),
  'src/components/review/ReviewPage.tsx::findingsGet#1': row('event', 'file-io', 'na', 'na', 'ui', 'toast', 'yes', 'ok', 'After a finished take comparison is closed: the list is narrowed to take comparisons and the new comparison is read and opened beside it; a failed read is a toast and the narrowed list still shows it.'),
  'src/components/review/TakeComparisonDialog.tsx::takeComparisonState#1': row('mount', 'instant', 'dialog', 'dialog', 'dialog', 'inline', 'yes', 'ok', 'On opening Compare takes: a comparison already running (left in the background) is followed with its progress rather than started again; a failed read is an inline alert in the dialog.'),
  'src/components/review/TakeComparisonDialog.tsx::takeComparisonStart#1': row('mount', 'job', 'dialog', 'host', 'dialog', 'inline', 'yes', 'ok', 'Starts the comparison of the group once per dialog (a ref guards a second effect run; the host refuses a second one anyway); the dialog says Starting until the job answers, then shows its progress. A refusal (the group or chapter changed, no manuscript) is an inline alert in the host words.'),
  'src/components/review/TakeComparisonDialog.tsx::takeComparisonState#2': row('timer', 'instant', 'dialog', 'dialog', 'dialog', 'dialog', 'yes', 'ok', 'Polls every 500 ms while the comparison runs, showing the sidecar own percent and stage in WorkDialog (ADR 0015); the end is also a job:ended toast, so Continue in background loses nothing (ADR 0076).'),
  'src/components/review/TakeComparisonDialog.tsx::takeComparisonCancel#1': row('click', 'instant', 'dialog', 'dialog', 'dialog', 'inline', 'no', 'ok', 'Cancel asks the sidecar to stop between takes and the job reports cancelled once it has; nothing is saved. A failed request is an inline alert.'),
  'src/components/review/FindingDetail.tsx::manuscriptParagraphs#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'na', 'na', 'ok', 'Show in manuscript is busy while the finding paragraph is resolved to its line; if that read fails the manuscript still opens at the chapter, and the manuscript page reports its own load failure.'),

};
