// The interaction feedback rows for the storyBible call sites (see interactionFeedback.catalog.ts for what a row says).
import { type FeedbackRow, row, subscription } from './row';

// prettier-ignore
export const storyBibleFeedback: Record<string, FeedbackRow> = {
  // Story Bible
  'src/components/storybible/Guide.tsx::guideEntities#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'The first load shows a load error with Retry; a later one is a toast.'),
  'src/components/storybible/Guide.tsx::guideBuildState#1': row('mount', 'instant', 'dialog', 'na', 'poll', 'toast', 'yes', 'ok', 'Shows the rebuild dialog again when the narrator comes back to the page while it still runs.'),
  'src/components/storybible/Guide.tsx::guideBuildState#2': row('timer', 'instant', 'dialog', 'dialog', 'event', 'dialog', 'yes', 'ok', 'The dialog polls for progress only while it is open; the end is announced by the job:ended event, so leaving the page or dismissing the dialog loses nothing (ADR 0076).'),
  'src/components/storybible/Guide.tsx::subscribeJobEnded#1': subscription('A rebuild that ends while the dialog is dismissed still refreshes the entries.'),
  'src/components/storybible/Guide.tsx::assetsInstall#1': row('click', 'download', 'dialog', 'host', 'dialog', 'dialog', 'no', 'ok', 'The language model download of the Story Bible build: the same first-use flow as the voice and Whisper downloads (useAssetInstall), and the host joins a download that is already running.'),
  'src/components/storybible/Guide.tsx::assetsInstallState#1': row('timer', 'download', 'dialog', 'na', 'poll', 'dialog', 'no', 'ok', 'The one install-poll loop (useAssetInstall): the dialog shows the bytes as they arrive and a failed poll in the dialog.'),
  'src/components/storybible/Guide.tsx::assetsInstallCancel#1': row('click', 'download', 'dialog', 'dialog', 'dialog', 'dialog', 'no', 'ok', 'Cancel stops the download and the dialog says so; it is drawn only while bytes arrive.'),
  'src/components/storybible/Guide.tsx::guideBuild#1': row('click', 'job', 'pending', 'pending', 'event', 'toast', 'no', 'ok', 'The build button is busy while the start call runs and a second press cannot start a second rebuild; the dialog and the job-end event follow (phase 3).'),
  'src/components/storybible/GuideDetail.tsx::guidePreview#1': row('click', 'python', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'The play button is busy while an uncached preview renders (a Python process that loads a voice) and only one render runs at a time (phase 3).'),
  'src/components/storybible/GuideDetail.tsx::guideEdit#1': row('click', 'python', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Save and the alias buttons run one at a time through usePendingAction: the control that was pressed is busy, the others (and the category menu) are off until it ends, a failure is a toast (phase 3). A Save is one process (phase 4).'),
  'src/components/storybible/GuideDetail.tsx::ttsInstall#1': row('click', 'download', 'dialog', 'host', 'dialog', 'dialog', 'no', 'ok', 'The first-use dialog says Starting at once; the host joins a download that is already running for the same asset (S16), so a second press starts no second one. Real bytes, the check, Cancel while bytes arrive, and a failure sentence in the dialog, through useAssetInstall.'),
  'src/components/storybible/GuideDetail.tsx::ttsInstallState#1': row('timer', 'download', 'dialog', 'na', 'poll', 'dialog', 'no', 'ok', 'The one install-poll loop (useAssetInstall), every 400 ms: the dialog shows the bytes as they arrive, and a failed poll is shown in the dialog. The download outlives the dialog and ends with job:ended.'),
  'src/components/storybible/GuideDetail.tsx::ttsInstallCancel#1': row('click', 'download', 'dialog', 'dialog', 'dialog', 'dialog', 'no', 'ok', 'Cancel stops the download and the dialog says it was cancelled; it is drawn only while bytes arrive, and a failed cancel is shown in the dialog.'),
  'src/components/storybible/GuideDetail.tsx::guideCreate#1': row('click', 'python', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Choosing a category creates the entry through usePendingAction: one at a time, the category menu is off until it ends, a failure is a toast (phase 3).'),
  'src/components/storybible/GuideDetail.tsx::guideRescan#1': row('click', 'python', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Busy while it runs, one at a time (phase 3).'),
  'src/components/storybible/GuideDetail.tsx::guidePronounce#1': row('click', 'python', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', "Choosing CMU or eSpeak from the Generate/Replace menu runs pronounce() through usePendingAction: busy one at a time, a failure (e.g. the engine has nothing for the name) is a toast and the control stays usable to retry (story bible entries phase 3, D13)."),
  'src/components/storybible/GuideDetail.tsx::guidePronounceUser#1': row('click', 'python', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', "Use mine sets the narrator's own pronunciation through usePendingAction: busy one at a time, the other controls off until it ends, a failure is a toast (prep-depth P1)."),
  'src/components/storybible/GuideDetail.tsx::guidePronunciationUseAlternate#1': row('click', 'python', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Switching to the kept alternate: busy one at a time, a failure is a toast (prep-depth P1).'),
  'src/components/storybible/GuideDetail.tsx::guidePronunciationSetStatus#1': row('click', 'python', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Save status: busy one at a time, a failure is a toast and the typed note stays (prep-depth P1).'),
  'src/components/storybible/PronunciationQueries.tsx::guidePronunciationQueries#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'Loads when the panel opens and after each mark; a failure is an alert in the panel (prep-depth P3).'),
  'src/components/storybible/PronunciationQueries.tsx::guidePronunciationSetStatus#1': row('click', 'python', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Mark sent and Mark answered run one at a time through usePendingAction: the pressed button is busy, the others off, a failure (a locked entry) is a toast (prep-depth P3).'),
  'src/components/storybible/PronunciationQueries.tsx::pronunciationOnlineLookupBatch#1': row('click', 'download', 'dialog', 'pending', 'toast', 'toast', 'no', 'ok', 'Look up online asks first in a notice naming how many names it sends (Q11); the notice stays open and busy until the batch ends, then a toast counts what was looked up, or says why it stopped (prep-depth P9).'),
  'src/components/storybible/OnlinePronunciationLookup.tsx::pronunciationOnlineLookup#1': row('click', 'download', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Look up online is busy while Merriam-Webster answers (or this computer\'s copy does); the answer, or why there is none (no key, a refused key, no connection), shows under the button (prep-depth P9).'),
  'src/components/storybible/CommonsAudioLookup.tsx::pronunciationCommonsAudioOpen#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Listen on Commons is busy while the host resolves the word against the installed Wiktextract index and opens the browser; a word with no recorded audio, or an index not installed, shows why under the button (prep-depth P10).'),
  'src/components/storybible/PronunciationQueries.tsx::guidePronunciationQueriesCsv#1': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Export CSV is busy while the host writes the text, then the browser download starts and a toast says how many rows (prep-depth P3).'),
  'src/components/storybible/PronunciationQueries.tsx::guidePronunciationImportQueriesCsv#1': row('click', 'python', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Import answers reads the picked file in the browser and sends its text; busy until every matched row is applied, a toast names how many and any rows not used are listed inline, and the list reloads (prep-depth P6).'),
  'src/components/storybible/GuideDetail.tsx::guideSetLocked#1': row('click', 'python', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Busy while it runs, one at a time (phase 3).'),
  'src/components/storybible/GuideDetail.tsx::guideUnrelate#1': row('click', 'python', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Busy on the row that was pressed, one at a time (phase 3).'),
  'src/components/storybible/GuideDetail.tsx::guideRelate#1': row('click', 'python', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Busy while it runs, one at a time (phase 3).'),
  'src/components/storybible/GuideDetail.tsx::guideDelete#1': row('click', 'python', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'The confirm dialog stays open and busy until the delete ends and cannot be cancelled away (phase 3).'),
  'src/components/storybible/GuideDetail.tsx::guideMerge#1': row('click', 'python', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'The confirm dialog stays open and busy until the merge ends and cannot be cancelled away (phase 3).'),

  // Voice references and dialogue cue attribution (character-continuity-review.prd.md Phase 6, non-acoustic part; D87)
  'src/components/storybible/VoiceReferencesSection.tsx::characterListRegions#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'Loaded alongside the reference list on mount; a failure shows inline (mirrors guideEntities#1).'),
  'src/components/storybible/VoiceReferencesSection.tsx::characterReferences#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'Loaded alongside the region list (one Promise.all on mount); a failure shows inline.'),
  'src/components/storybible/VoiceReferencesSection.tsx::characterApprove#1': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Approve as reference is busy while it runs, one at a time with Revoke, through usePendingAction; a failure (e.g. the picked region is not in the saved project) is a toast.'),
  'src/components/storybible/VoiceReferencesSection.tsx::characterRevoke#1': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'Revoke is busy while it runs, one at a time with Approve, through usePendingAction; a failure is a toast.'),
  'src/components/storybible/DialogueCueAttribution.tsx::guideDialogueCues#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'Loaded on mount, independent of the entity edit form; a failure shows inline (mirrors guideEntities#1).'),
  'src/components/storybible/DialogueCueAttribution.tsx::guideCorrectCue#1': row('input', 'python', 'disabled', 'disabled', 'toast', 'toast', 'na', 'ok', 'Choosing a speaker corrects the cue through usePendingAction: every cue\'s speaker select disables while one correction runs, and a failure (e.g. the cue no longer exists) is a toast.'),
  'src/components/storybible/VoiceDataPanel.tsx::characterRemoveVoiceData#1': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'na', 'ok', 'The confirm dialog stays open and busy until Remove voice data ends and cannot be cancelled away; a failure is a toast.'),
};
