// The interaction feedback rows for the teleprompter call sites (see interactionFeedback.catalog.ts for what a row says).
import { type FeedbackRow, row, subscription } from './row';

// prettier-ignore
export const teleprompterFeedback: Record<string, FeedbackRow> = {
  // Teleprompter. Phase 2 (teleprompter-manuscript-integration.prd.md) extracted the session core into
  // `useTeleprompterSession` so the standalone page and the `ReadAloudDialog` modal share it; the rows below moved
  // with the calls they describe, and `TeleprompterPage.tsx` keeps only what stayed there (chapter selection).
  'src/components/teleprompter/TeleprompterPage.tsx::manuscriptChapters#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'An inline error.'),
  'src/components/teleprompter/TeleprompterPage.tsx::readerState#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Only picks the chapter the narrator last read; the first chapter is used without it.'),
  // Phase 11 of the input-devices PRD (ADR 0113): the REAPER suggestion is a hint beneath the picker, and the
  // session-state read only stops it moving a session already running.
  'src/components/teleprompter/TeleprompterPage.tsx::chapterSuggestion#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'A hint only: with no .rpp, or none chosen, the picker keeps its usual default and no hint shows.'),
  'src/components/teleprompter/TeleprompterPage.tsx::teleprompterState#1': row('mount', 'instant', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Only guards the REAPER preselection; the session hook reads and reports the state itself.'),
  'src/components/teleprompter/useResumeLocate.ts::teleprompterLocate#1': row('mount', 'python', 'inline', 'pending', 'ui', 'inline', 'no', 'ok', 'The read-aloud resume prompt (read-aloud-resume-from-daw.prd.md Phase 1, ADR 0187, amending ADR 0112) asks where the recording ends once when the dialog opens, and again on Try again or a finished model download: "Checking where REAPER and your last reading are…" (Phase 3 wording) shows at once and replaces the choices, and only the latest lookup may answer; a failure is an inline alert with Try again. It settles - and stays gone - the moment a choice is made or a session starts, for the rest of the dialog\'s open.'),
  'src/components/teleprompter/useResumeLocate.ts::whisperInstall#1': row('click', 'download', 'dialog', 'host', 'dialog', 'dialog', 'no', 'ok', 'Only after Download model... and the first-use confirm; the host joins a download already running for the same asset. Bytes, the check, Cancel and a failure sentence in the dialog, through useAssetInstall; a finished download runs the lookup again.'),
  'src/components/teleprompter/useResumeLocate.ts::whisperInstallState#1': row('timer', 'download', 'dialog', 'na', 'poll', 'dialog', 'no', 'ok', 'The one install-poll loop (useAssetInstall), every 400 ms, as for the Start reading download.'),
  'src/components/teleprompter/useResumeLocate.ts::whisperInstallCancel#1': row('click', 'download', 'dialog', 'dialog', 'dialog', 'dialog', 'no', 'ok', 'Cancel stops the download and the dialog says it was cancelled; drawn only while bytes arrive.'),
  'src/components/teleprompter/TeleprompterPage.tsx::creditsTemplates#1': row(
    'mount',
    'file-io',
    'na',
    'na',
    'ui',
    'silent',
    'na',
    'exempt',
    'Loads the credits template library so the picker can offer Opening and Closing credits (audiobook-credits-templates.prd.md Phase 4); a failed load leaves the credits out of the picker, like the Manuscript entries, and the chapters stay readable.',
  ),
  'src/components/teleprompter/TeleprompterPage.tsx::creditsPreview#1': row(
    'mount',
    'instant',
    'na',
    'na',
    'ui',
    'silent',
    'na',
    'exempt',
    'Renders the first opening- and closing-kind template (ADR 0093) with the project values for the credits in the picker, their text and the unresolved-token warning; a failed render leaves that credits out of the picker rather than a toast over the page.',
  ),
  'src/components/teleprompter/useTeleprompterSession.ts::subscribeTeleprompterEvent#1': subscription('The live session events.'),
  'src/components/teleprompter/useTeleprompterSession.ts::subscribeTeleprompterState#1': subscription('The live session state.'),
  'src/components/teleprompter/useTeleprompterSession.ts::teleprompterState#1': row('mount', 'instant', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Hydrates a session that was already running; the state event follows anyway.'),
  'src/components/teleprompter/useTeleprompterSession.ts::teleprompterDevices#1': row('effect', 'python', 'na', 'disabled', 'ui', 'inline', 'na', 'ok', 'Loads the device list on mount and again on a manual Refresh click in the picker (disabled while a listing is already in flight); a listing failure shows inline instead of blocking Start with a previously-chosen device (the host never fails this call outright).'),
  'src/components/teleprompter/useReadAloudReaperState.ts::readAloudReaperState#1': row(
    'effect',
    'file-io',
    'na',
    'none',
    'ui',
    'inline',
    'na',
    'ok',
    'Reads the chapter\'s REAPER state on mount and again on a manual Refresh click in the bar (read-aloud-control-bar.prd.md Phase 6, ADR 0249, never on a timer); the button\'s visible text and its tooltip show the last-known state or the reason it could not be read, and the Record in REAPER control stays disabled either way, since Phase 7\'s actionable toggle is not built yet.',
  ),
  'src/components/teleprompter/useTeleprompterSession.ts::settingsForScope#1': row('effect', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Loads the persisted microphone (docs/prds/teleprompter-engines-and-input-devices.prd.md Phase 2) and runs the one-time browser-storage migration on the standalone page; if it fails the field just starts empty, exactly as it did before Phase 2.'),
  'src/components/teleprompter/useTeleprompterSession.ts::manuscriptParagraphs#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'An inline error.'),
  'src/components/teleprompter/useTeleprompterSession.ts::teleprompterStart#1': row('click', 'job', 'disabled', 'host', 'ui', 'inline', 'no', 'ok', 'The state event moves the page to "starting" and disables Start; the host refuses a second session.'),
  'src/components/teleprompter/useTeleprompterSession.ts::teleprompterStop#1': row('click', 'job', 'none', 'none', 'ui', 'inline', 'no', 'ok', 'The state event moves the page on; an inline error otherwise.'),
  'src/components/teleprompter/useTeleprompterSession.ts::teleprompterPause#1': row(
    'click',
    'file-io',
    'none',
    'none',
    'event',
    'inline',
    'no',
    'ok',
    'Pause/resume on the control channel (read-aloud-control-bar.prd.md Phase 5, ADR 0248); the state event\'s `paused` flag moves the bar\'s toggle and status ("Paused"/"Listening"), an inline error otherwise.',
  ),
  'src/components/teleprompter/useInputLevel.ts::subscribeTeleprompterEvent#1': subscription('The bar and microphone-popover meter (Phase 4, ADR 0247): its own subscription, apart from the session model, so a burst of level events never re-renders the reader\'s rows.'),
  'src/components/teleprompter/useInputLevel.ts::teleprompterMeterStart#1': row(
    'effect',
    'python',
    'na',
    'host',
    'event',
    'inline',
    'na',
    'ok',
    'Starts the meter-only child while the microphone popover is open and no session is running; the meter itself shows it working, an inline alert under it otherwise (the host refuses a second meter or one during a session).',
  ),
  'src/components/teleprompter/useInputLevel.ts::teleprompterMeterStop#1': row(
    'effect',
    'python',
    'na',
    'na',
    'event',
    'silent',
    'na',
    'exempt',
    'Releases the meter-only child when the popover closes, a session starts, the device changes or the dialog unmounts; there is nothing left mounted to tell, and a session or the next popover open still works either way (SILENT_CATCHES).',
  ),
  'src/components/teleprompter/ReadAloudDialog.tsx::teleprompterSaveFlags#1': row(
    'effect',
    'file-io',
    'none',
    'none',
    'ui',
    'inline',
    'no',
    'ok',
    'Keeps the session’s suspected flags as findings when reading stops, when the dialog closes and on a dismiss after the session (ADR 0117); the Flags tab says they were kept, or shows the failure. Saving again is idempotent on the host, so there is nothing to guard.',
  ),
  'src/components/teleprompter/useTeleprompterSession.ts::teleprompterSeek#1': row('click', 'file-io', 'none', 'none', 'event', 'inline', 'no', 'ok', 'The tracker\'s next position event (jump: "restart") shows the move; an inline error otherwise. No caller triggers this yet (teleprompter-manuscript-integration.prd.md Phase 4 adds the word-click affordance); the seek channel itself is Phase 3.'),
  'src/components/teleprompter/useTeleprompterSession.ts::assetsInstall#1': row('click', 'download', 'dialog', 'host', 'dialog', 'dialog', 'no', 'ok', 'The first-use dialog says Starting at once; the host joins a download that is already running for the same asset (S16), so a second press starts no second one. The asset is the model of the chosen engine (Whisper or Moonshine), named by the gate. Real bytes, the check, Cancel while bytes arrive, and a failure sentence in the dialog, through useAssetInstall.'),
  'src/components/teleprompter/useTeleprompterSession.ts::assetsInstallState#1': row('timer', 'download', 'dialog', 'na', 'poll', 'dialog', 'no', 'ok', 'The one install-poll loop (useAssetInstall), every 400 ms: the dialog shows the bytes as they arrive, and a failed poll is shown in the dialog. The download outlives the dialog and ends with job:ended.'),
  'src/components/teleprompter/useTeleprompterSession.ts::assetsInstallCancel#1': row('click', 'download', 'dialog', 'dialog', 'dialog', 'dialog', 'no', 'ok', 'Cancel stops the download and the dialog says it was cancelled; it is drawn only while bytes arrive, and a failed cancel is shown in the dialog.'),
  'src/components/teleprompter/useTeleprompterSession.ts::saveSettings#1': row('effect', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'The one-time browser-storage-to-settings migration write (standalone page only); a failure leaves the device in local state for this visit and the migration is retried next load since the settings value never got marked set.'),
  'src/components/teleprompter/useTeleprompterSession.ts::saveSettings#2': row(
    'input',
    'file-io',
    'none',
    'none',
    'ui',
    'inline',
    'no',
    'ok',
    "The chosen microphone (global settings, docs/prds/teleprompter-engines-and-input-devices.prd.md Phase 2) is saved as it is picked or typed; a save failure shows as the inline error (the page's or the ReadAloudDialog modal's), and the value picked stays selected in the field either way.",
  ),

};
