// The interaction feedback rows for the tracks call sites (see interactionFeedback.catalog.ts for what a row says).
import { type FeedbackRow, row, startup, subscription } from './row';

// prettier-ignore
export const tracksFeedback: Record<string, FeedbackRow> = {
  // Tracks
  'src/components/tracks/TracksPage.tsx::tracksDiscover#1': row('mount', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'An inline error.'),
  'src/components/tracks/TracksPage.tsx::tracksList#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Parsing a 100 KB project file takes about 2 ms (docs/research/interaction-latency-baseline.md).'),
  'src/components/tracks/TracksPage.tsx::tracksSelect#1': row('click', 'file-io', 'none', 'none', 'ui', 'inline', 'na', 'ok', 'A small file write.'),
  'src/components/tracks/ChapterLinksTable.tsx::manuscriptChapters#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'Loaded beside the confirmed mappings to build the chapter-link list (evidence ledger PRD, Phase 7).'),
  'src/components/tracks/ChapterLinksTable.tsx::chapterTrackMapList#1': row('effect', 'file-io', 'na', 'na', 'ui', 'inline', 'na', 'ok', 'The confirmed links for the current manuscript document.'),
  'src/components/tracks/ChapterLinksTable.tsx::chapterTrackSet#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Confirm on a chapter\'s MappingConfirm; the row is busy until the link replaces the chapter\'s old one and is re-listed, and a refusal (an unknown chapter) is written inline.'),
  'src/components/tracks/ChapterLinksTable.tsx::chapterTrackUnlink#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Clear on a chapter\'s MappingConfirm; the row is busy until every link the chapter holds is removed and re-listed.'),
  'src/components/tracks/ChapterSyncPanel.tsx::chapterSyncPreview#1': row('effect', 'file-io', 'na', 'na', 'ui', 'toast', 'na', 'ok', 'Fills the Needs-you and not-chapters lists (daw-chapter-track-auto-sync.prd.md Phase 3, mockup 02), read again on mount and after each sync; a failed read is a toast and the panel keeps its last list.'),
  'src/components/tracks/ChapterSyncPanel.tsx::chapterSyncSetEnabled#1': row('click', 'file-io', 'pending', 'pending', 'ui', 'toast', 'na', 'ok', 'Turn on / Turn off on the panel; the button is busy until the state (and, turning on, the first sync) comes back, and a failure is a toast that leaves the switch as it was.'),
  'src/components/tracks/ChapterSyncPanel.tsx::chapterTrackSet#1': row('click', 'file-io', 'pending', 'pending', 'toast', 'toast', 'no', 'ok', 'Link on a Needs-you row, the same binding as Chapter links below; the row\'s Link button is busy until it returns, "Track linked." confirms it, and the list is read again.'),
  'src/components/tracks/TracksPage.tsx::manuscriptChapters#1': row('mount', 'file-io', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Only decides whether the "Link chapters…" button shows; without it the button is absent, same as a project with no chapters.'),
  'src/components/tracks/LinkChaptersDialog.tsx::lineIdentityState#1': row('mount', 'instant', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Hydrates whatever stamp or read was already in flight when the dialog reopened; the live event follows anyway.'),
  'src/components/tracks/LinkChaptersDialog.tsx::subscribeLineIdentity#1': subscription('The line-identity state event, shared by the Stamp and Read runs this dialog starts.'),
  'src/components/tracks/LinkChaptersDialog.tsx::lineIdentityStamp#1': row('click', 'job', 'pending', 'disabled', 'ui', 'inline', 'no', 'ok', 'Approve. The dialog cannot be closed while a stamp runs (Dialog\'s onClose is undefined then), so the result is always seen; a failure shows inline as an alert and in the phase message.'),
  'src/components/tracks/LinkChaptersDialog.tsx::lineIdentityRead#1': row('click', 'job', 'pending', 'disabled', 'ui', 'inline', 'no', 'ok', 'Read-only and idempotent; a failure shows inline in the "Currently stamped" section.'),
  'src/components/tracks/PickupsDialog.tsx::pickupsState#1': row('mount', 'instant', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Hydrates whatever run was already in flight when the dialog reopened; the live event follows anyway.'),
  'src/components/tracks/PickupsDialog.tsx::subscribePickups#1': subscription('The pickups state event, shared by every import, export, next, resolve and count run this dialog starts.'),
  'src/components/tracks/PickupsDialog.tsx::pickupsCount#1': row(
    'mount',
    'job',
    'na',
    'na',
    'ui',
    'silent',
    'na',
    'exempt',
    'An automatic refresh right after the hydrate above settles, so the remaining count is current without an extra press; a failure here just leaves the count at whatever the hydrate answered, and the narrator can still press Import, Next or Export, each of which shows its own failure inline.',
  ),
  'src/components/tracks/PickupsDialog.tsx::pickupsImport#1': row('input', 'job', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'Choosing a CSV file. Row errors and the import summary show inline; a request failure shows as an alert.'),
  'src/components/tracks/PickupsDialog.tsx::pickupsNext#1': row('click', 'job', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'A failure (no pickups remain) shows as an alert.'),
  'src/components/tracks/PickupsDialog.tsx::pickupsResolve#1': row('click', 'job', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'A failure (no open pickup at that position) shows as an alert.'),
  'src/components/tracks/PickupsDialog.tsx::pickupsExport#1': row('click', 'job', 'pending', 'pending', 'ui', 'inline', 'no', 'ok', 'A completed export triggers the browser file-save download; a failure shows as an alert.'),
  'src/components/tracks/RenderConfigDialog.tsx::renderConfigState#1': row('mount', 'instant', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Hydrates whatever configure run was already in flight when the dialog reopened; the live event follows anyway.'),
  'src/components/tracks/RenderConfigDialog.tsx::renderConfigSuggestFolder#1': row(
    'mount',
    'instant',
    'na',
    'na',
    'ui',
    'silent',
    'na',
    'exempt',
    'Only prefills the output folder field when nothing was configured yet; without it the narrator types the folder by hand.',
  ),
  'src/components/tracks/RenderConfigDialog.tsx::subscribeRenderConfig#1': subscription('The render-config state event, for the configure run this dialog starts.'),
  'src/components/tracks/RenderConfigDialog.tsx::renderConfigConfigure#1': row(
    'click',
    'job',
    'pending',
    'pending',
    'ui',
    'inline',
    'no',
    'ok',
    'Configuration only (Phase 11, Open Question 7): sets the render bounds, pattern and output folder, never triggers a render. A completed run shows the resulting file names and the manual-render instruction; a failure shows inline as an alert.',
  ),
  'src/components/tracks/CleanupToolsDialog.tsx::cleanupToolsState#1': row('mount', 'instant', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Hydrates whatever launch was already in flight when the dialog reopened; the live event follows anyway.'),
  'src/components/tracks/CleanupToolsDialog.tsx::subscribeCleanupTools#1': subscription('The cleanup-tools state event, for the launch this dialog starts.'),
  'src/components/tracks/CleanupToolsDialog.tsx::cleanupToolsLaunch#1': row(
    'click',
    'job',
    'pending',
    'pending',
    'ui',
    'inline',
    'no',
    'ok',
    'Opens an allow-listed repair dialog in REAPER (Phase 23, ADR 0146) and changes nothing itself. The pressed tool shows pending and the other is disabled until REAPER answers; the opened state or REAPER\'s refusal (no selection, not installed) shows inline.',
  ),
  'src/components/tracks/RetakeLanesDialog.tsx::subscribeRetakeLanes#1': subscription('The retake-lane state event, for the pick this dialog starts.'),
  'src/components/tracks/RetakeLanesDialog.tsx::retakeLanesState#1': row('mount', 'instant', 'na', 'na', 'ui', 'silent', 'na', 'exempt', 'Hydrates whatever pick was already in flight when the dialog reopened; the live event follows anyway.'),
  'src/components/tracks/RetakeLanesDialog.tsx::retakeLanesList#1': startup('Reads the saved .rpp for lines with retakes on fixed lanes; a failure shows inline as an alert instead of the list.'),
  'src/components/tracks/RetakeLanesDialog.tsx::retakeLanesPick#1': row(
    'click',
    'job',
    'pending',
    'pending',
    'ui',
    'inline',
    'no',
    'ok',
    'Makes one retake\'s lane the only one playing on its track (Phase 25, ADR 0147), one REAPER undo step and nothing else. The pressed lane shows pending and every other lane and Close are disabled until REAPER answers; the new play state or REAPER\'s refusal (stale retake, lanes off) shows inline.',
  ),
  'src/components/tracks/ChapterTagsDialog.tsx::chapterTagsPreview#1': row('mount', 'instant', 'na', 'na', 'ui', 'inline', 'na', 'exempt', 'Loads the known chapters from the last chapter render; a failure shows inline instead of the chapter list.'),
  'src/components/tracks/ChapterTagsDialog.tsx::chapterTagsEmbed#1': row(
    'click',
    'file-io',
    'disabled',
    'disabled',
    'ui',
    'inline',
    'no',
    'ok',
    'Phase 12: writes ID3 CHAP/CTOC tags into a new copy of the narrator-chosen file. Gated on the confirm checkbox and a non-blank destination; the button and the confirm checkbox stay disabled while it runs. A success shows the new file path, a failure shows inline as an alert.',
  ),

};
