// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Milestone is one dated checkpoint: a name, a calendar date "YYYY-MM-DD" and an optional note. Nothing beyond the
 * shape is validated here; internal/production checks a milestone before it is saved.
 */
export class Milestone {
    "name": string;
    "dueDate": string;
    "note"?: string;

    /** Creates a new Milestone instance. */
    constructor($$source: Partial<Milestone> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dueDate" in $$source)) {
            this["dueDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Milestone instance from a string or object.
     */
    static createFrom($$source: any = {}): Milestone {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Milestone($$parsedSource as Partial<Milestone>);
    }
}
