// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['Host']['Bootstrap']();
}

export function GuideBuild() {
  return window['go']['main']['Host']['GuideBuild']();
}

export function GuideBuildState() {
  return window['go']['main']['Host']['GuideBuildState']();
}

export function GuideCreate(arg1, arg2, arg3) {
  return window['go']['main']['Host']['GuideCreate'](arg1, arg2, arg3);
}

export function GuideDelete(arg1) {
  return window['go']['main']['Host']['GuideDelete'](arg1);
}

export function GuideEdit(arg1, arg2) {
  return window['go']['main']['Host']['GuideEdit'](arg1, arg2);
}

export function GuideEntities() {
  return window['go']['main']['Host']['GuideEntities']();
}

export function GuideExport() {
  return window['go']['main']['Host']['GuideExport']();
}

export function GuideMerge(arg1, arg2) {
  return window['go']['main']['Host']['GuideMerge'](arg1, arg2);
}

export function GuidePreview(arg1, arg2) {
  return window['go']['main']['Host']['GuidePreview'](arg1, arg2);
}

export function GuideRelate(arg1, arg2, arg3) {
  return window['go']['main']['Host']['GuideRelate'](arg1, arg2, arg3);
}

export function GuideRescan(arg1) {
  return window['go']['main']['Host']['GuideRescan'](arg1);
}

export function GuideSetLocked(arg1, arg2) {
  return window['go']['main']['Host']['GuideSetLocked'](arg1, arg2);
}

export function GuideUnrelate(arg1, arg2, arg3) {
  return window['go']['main']['Host']['GuideUnrelate'](arg1, arg2, arg3);
}

export function ManuscriptChapters() {
  return window['go']['main']['Host']['ManuscriptChapters']();
}

export function ManuscriptClearProjectData(arg1) {
  return window['go']['main']['Host']['ManuscriptClearProjectData'](arg1);
}

export function ManuscriptCreateBookmark(arg1) {
  return window['go']['main']['Host']['ManuscriptCreateBookmark'](arg1);
}

export function ManuscriptCreateNote(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['Host']['ManuscriptCreateNote'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ManuscriptDeleteBookmark(arg1) {
  return window['go']['main']['Host']['ManuscriptDeleteBookmark'](arg1);
}

export function ManuscriptDeleteNote(arg1) {
  return window['go']['main']['Host']['ManuscriptDeleteNote'](arg1);
}

export function ManuscriptImportCancel(arg1) {
  return window['go']['main']['Host']['ManuscriptImportCancel'](arg1);
}

export function ManuscriptImportCommit(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Host']['ManuscriptImportCommit'](arg1, arg2, arg3, arg4);
}

export function ManuscriptImportPreview(arg1, arg2) {
  return window['go']['main']['Host']['ManuscriptImportPreview'](arg1, arg2);
}

export function ManuscriptImportState(arg1) {
  return window['go']['main']['Host']['ManuscriptImportState'](arg1);
}

export function ManuscriptNotes(arg1) {
  return window['go']['main']['Host']['ManuscriptNotes'](arg1);
}

export function ManuscriptParagraphs(arg1) {
  return window['go']['main']['Host']['ManuscriptParagraphs'](arg1);
}

export function ManuscriptReader() {
  return window['go']['main']['Host']['ManuscriptReader']();
}

export function ManuscriptReaderState() {
  return window['go']['main']['Host']['ManuscriptReaderState']();
}

export function ManuscriptSaveReaderState(arg1, arg2, arg3) {
  return window['go']['main']['Host']['ManuscriptSaveReaderState'](arg1, arg2, arg3);
}

export function ManuscriptSearch(arg1) {
  return window['go']['main']['Host']['ManuscriptSearch'](arg1);
}

export function ManuscriptSelectFile() {
  return window['go']['main']['Host']['ManuscriptSelectFile']();
}

export function ManuscriptSetChapterStatus(arg1, arg2) {
  return window['go']['main']['Host']['ManuscriptSetChapterStatus'](arg1, arg2);
}

export function Ready() {
  return window['go']['main']['Host']['Ready']();
}

export function SystemReportDiagnostic(arg1, arg2) {
  return window['go']['main']['Host']['SystemReportDiagnostic'](arg1, arg2);
}

export function SystemSaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['Host']['SystemSaveSettings'](arg1, arg2, arg3);
}

export function SystemSettingsForScope(arg1) {
  return window['go']['main']['Host']['SystemSettingsForScope'](arg1);
}

export function TranscriptAddEquivalence(arg1) {
  return window['go']['main']['Host']['TranscriptAddEquivalence'](arg1);
}

export function TranscriptCancel() {
  return window['go']['main']['Host']['TranscriptCancel']();
}

export function TranscriptExportMarkers() {
  return window['go']['main']['Host']['TranscriptExportMarkers']();
}

export function TranscriptHints() {
  return window['go']['main']['Host']['TranscriptHints']();
}

export function TranscriptJump(arg1) {
  return window['go']['main']['Host']['TranscriptJump'](arg1);
}

export function TranscriptLastCompleted() {
  return window['go']['main']['Host']['TranscriptLastCompleted']();
}

export function TranscriptReset() {
  return window['go']['main']['Host']['TranscriptReset']();
}

export function TranscriptSaveHints(arg1) {
  return window['go']['main']['Host']['TranscriptSaveHints'](arg1);
}

export function TranscriptStart(arg1) {
  return window['go']['main']['Host']['TranscriptStart'](arg1);
}

export function TranscriptSuggestHints() {
  return window['go']['main']['Host']['TranscriptSuggestHints']();
}

export function TtsCatalog() {
  return window['go']['main']['Host']['TtsCatalog']();
}

export function TtsInstall(arg1) {
  return window['go']['main']['Host']['TtsInstall'](arg1);
}

export function TtsInstallCancel(arg1) {
  return window['go']['main']['Host']['TtsInstallCancel'](arg1);
}

export function TtsInstallState(arg1) {
  return window['go']['main']['Host']['TtsInstallState'](arg1);
}

export function TtsRemove(arg1) {
  return window['go']['main']['Host']['TtsRemove'](arg1);
}
