// Builds the index table of docs/adr/README.md from the ADR files themselves, so the table can never disagree with them.
//
// A row is the ADR's number (linking to its file), the title from its `# NNNN. Title` heading, and its Status line as written:
// a link reads as its text and a backslash or pipe is escaped, so every row stays one table row. The ADR's Status line is where a change of
// status is recorded (docs/adr/README.md, rule 2), so a superseded ADR shows it here once its own file says so.
//
//   node scripts/ci/adr-index.mjs           exits 1 when the table in the README is stale
//   node scripts/ci/adr-index.mjs --write   rewrites the table between the markers
//
// scripts/ci/adr-index.test.mjs (repo-scripts:test-node, so `pnpm check` and quick-ubuntu) fails on a stale table.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { REPO_ROOT } from './layout.mjs';

export const ADR_DIR = 'docs/adr';
export const INDEX_START = '<!-- adr-index:start (generated by scripts/ci/adr-index.mjs --write; edit the ADRs, not this table) -->';
export const INDEX_END = '<!-- adr-index:end -->';

const ADR_FILE = /^(\d{4})-.+\.md$/;
const HEADING = /^# (\d{4})\. (.+)$/m;
// `**Status:** Accepted` (the template), or `- Status: accepted` (the first ADRs).
const STATUS = /^(?:\*\*Status:\*\*|- Status:)[ \t]*(.+)$/m;
const LINK = /\[([^\]]+)\]\([^)]+\)/g;

// Backslashes first, so a backslash in the text cannot unescape the pipe after it.
const cell = (text) => text.replace(LINK, '$1').replace(/\\/g, '\\\\').replace(/\|/g, '\\|').trim();

/** One ADR's row: its number, file, title and status, as the index shows them. */
export function adrEntry(file, text) {
  const number = file.match(ADR_FILE)?.[1];
  if (!number) throw new Error(`${file} is not named NNNN-title.md`);
  const heading = text.match(HEADING);
  if (!heading) throw new Error(`${file} has no "# ${number}. Title" heading`);
  if (heading[1] !== number) throw new Error(`${file}: its heading says ${heading[1]}`);
  const status = text.match(STATUS);
  if (!status) throw new Error(`${file} has no Status line`);
  const statusText = cell(status[1]);
  return { number, file, title: cell(heading[2]), status: statusText.charAt(0).toUpperCase() + statusText.slice(1) };
}

/** Every numbered ADR in `dir`, read into its row. */
export function readAdrs(dir) {
  return readdirSync(dir)
    .filter((file) => ADR_FILE.test(file))
    .map((file) => adrEntry(file, readFileSync(join(dir, file), 'utf8')));
}

/** The index table, in number order. */
export function renderIndex(adrs) {
  const rows = [...adrs].sort((a, b) => a.number.localeCompare(b.number)).map((adr) => `| [${adr.number}](${adr.file}) | ${adr.title} | ${adr.status} |`);
  return ['| # | Title | Status |', '| --- | --- | --- |', ...rows].join('\n');
}

/** The README with the table between the markers replaced by `table`. */
export function replaceIndex(readme, table) {
  const start = readme.indexOf(INDEX_START);
  const end = readme.indexOf(INDEX_END);
  if (start === -1 || end === -1 || end < start) throw new Error(`${ADR_DIR}/README.md has no index markers (${INDEX_START} ... ${INDEX_END})`);
  return `${readme.slice(0, start + INDEX_START.length)}\n${table}\n${readme.slice(end)}`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const dir = join(REPO_ROOT, ADR_DIR);
  const path = join(dir, 'README.md');
  const readme = readFileSync(path, 'utf8');
  const next = replaceIndex(readme, renderIndex(readAdrs(dir)));
  if (process.argv.includes('--write')) {
    if (next !== readme) writeFileSync(path, next);
    console.log(next === readme ? `${ADR_DIR}/README.md: the index is current.` : `${ADR_DIR}/README.md: the index was rewritten.`);
  } else if (next !== readme) {
    console.error(`${ADR_DIR}/README.md: the index is stale. Run: node scripts/ci/adr-index.mjs --write`);
    process.exit(1);
  } else {
    console.log(`${ADR_DIR}/README.md: the index is current.`);
  }
}
