// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Host is the Wails binding boundary. The frontend invokes only this bound
 * object; it never receives a loopback port or an HTTP capability.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as liveflags$0 from "./internal/liveflags/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AssetsInstall starts installing one asset, or repairs it when it is damaged, and answers with its job. A second call for an asset that is
 * already downloading joins that job. The narrator asked for it: nothing else starts a download.
 */
export function AssetsInstall(kind: string, id: string): $CancellablePromise<string> {
    return $Call.ByID(3032187698, kind, id);
}

export function AssetsInstallCancel(jobID: string): $CancellablePromise<string> {
    return $Call.ByID(1546584672, jobID);
}

export function AssetsInstallState(jobID: string): $CancellablePromise<string> {
    return $Call.ByID(4222710679, jobID);
}

/**
 * AssetsList is every approved asset of every kind with its state, size, publisher, licence and provenance links, where it is installed,
 * when, and the download that is running for it (so a page opened while one runs can follow it). It reads no file contents.
 */
export function AssetsList(): $CancellablePromise<string> {
    return $Call.ByID(2175855371);
}

/**
 * AssetsRemove deletes one asset. It refuses while the asset is downloading, and touches nothing else: not another asset, not a setting,
 * not a project.
 */
export function AssetsRemove(kind: string, id: string): $CancellablePromise<string> {
    return $Call.ByID(3574252271, kind, id);
}

/**
 * AssetsVerify reads every byte of one asset and answers with its state: installed, damaged (verification_failed) or absent.
 */
export function AssetsVerify(kind: string, id: string): $CancellablePromise<string> {
    return $Call.ByID(2412149070, kind, id);
}

export function Bootstrap(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2880307428).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ChapterRegionsCreate(openingTrackGUID: string, closingTrackGUID: string, update: boolean): $CancellablePromise<string> {
    return $Call.ByID(3672636080, openingTrackGUID, closingTrackGUID, update);
}

/**
 * ChapterRegionsPreview and ChapterRegionsCreate are the chapter and credits
 * regions (reaper-automation-follow-through PRD Phase 7, credits-in-chapter-
 * table PRD Phase 4; chapterregions.go): Preview plans one region per linked
 * chapter, plus the opening and closing credits when their tracks are given
 * (empty leaves them out), from the saved .rpp and writes nothing; Create
 * recomputes the same plan and sends it to REAPER's create_regions in one
 * undo step, moving a region whose title already exists with other bounds
 * only when update is true.
 */
export function ChapterRegionsPreview(openingTrackGUID: string, closingTrackGUID: string): $CancellablePromise<string> {
    return $Call.ByID(2311254464, openingTrackGUID, closingTrackGUID);
}

/**
 * ChapterSuggestion suggests the chapter the narrator is recording from the
 * selected .rpp's record-armed (else selected) track as of its last save
 * (teleprompter-engines-and-input-devices PRD Phase 11, ADR 0113): the matcher's
 * other direction, track to chapter, with the same statuses. Read-only.
 */
export function ChapterSuggestion(): $CancellablePromise<string> {
    return $Call.ByID(677537319);
}

/**
 * ChapterSyncPreview plans a sync without writing anything: the consent dialog's preview.
 */
export function ChapterSyncPreview(): $CancellablePromise<string> {
    return $Call.ByID(2662742132);
}

/**
 * ChapterSyncSetEnabled stores the narrator's answer (Sync is true, Not now is false, and the Tracks page's toggle
 * uses the same call) and, when on, runs the first sync. It returns the new state with the sync's batch.
 */
export function ChapterSyncSetEnabled(on: boolean): $CancellablePromise<string> {
    return $Call.ByID(1374797281, on);
}

/**
 * ChapterSyncState reads the consent, whether to ask, and the last sync. It only reads.
 */
export function ChapterSyncState(): $CancellablePromise<string> {
    return $Call.ByID(2066232613);
}

/**
 * ChapterSyncUndo removes one automatic link and remembers the pair so no later sync makes it again (ADR 0203). A
 * manual link is refused. It returns the new state.
 */
export function ChapterSyncUndo(trackGUID: string): $CancellablePromise<string> {
    return $Call.ByID(2733438718, trackGUID);
}

/**
 * ChapterTagsEmbed builds the chapter timeline from Phase 11's known per-chapter files and writes ID3v2 CHAP and
 * CTOC frames into a NEW copy of destPath (the narrator-supplied combined-book MP3), returning that new file's
 * path. destPath is never modified. The narrator confirms this explicitly in the UI before it is called.
 */
export function ChapterTagsEmbed(destPath: string): $CancellablePromise<string> {
    return $Call.ByID(2013283223, destPath);
}

/**
 * ChapterTagsPreview reports the chapters Phase 11's last successful render configuration knows about (title,
 * source file, and whether that file exists on disk yet - it may not, if the narrator has not pressed Render
 * since configuring), so the UI can show what will be embedded and disable the action until every file is ready.
 */
export function ChapterTagsPreview(): $CancellablePromise<string> {
    return $Call.ByID(800337126);
}

export function ChapterTrackLinks(): $CancellablePromise<string> {
    return $Call.ByID(488920311);
}

export function ChapterTrackMapClear(trackGUID: string): $CancellablePromise<string> {
    return $Call.ByID(3648043981, trackGUID);
}

export function ChapterTrackMapConfirm(trackGUID: string, chapterID: string): $CancellablePromise<string> {
    return $Call.ByID(784242736, trackGUID, chapterID);
}

/**
 * ChapterTrackMapList, ChapterTrackMapConfirm and ChapterTrackMapClear are
 * the narrator-confirmed chapter-track mapping's bindings (analysis
 * evidence ledger PRD, Phase 5, Q6/Q7): the mapping-confirm UI itself is
 * Phase 7 (not built here), but the store it will call is bound now.
 */
export function ChapterTrackMapList(): $CancellablePromise<string> {
    return $Call.ByID(20566568);
}

/**
 * ChapterTrackMatch finds the track holding chapterID and where its recorded
 * audio ends (teleprompter-manuscript-integration PRD Phase 8, ADR 0110): a
 * confirmed link first, then the shared chapter-to-track matcher over track
 * and region names. It only reads; it never creates a track or a link.
 */
export function ChapterTrackMatch(chapterID: string): $CancellablePromise<string> {
    return $Call.ByID(963672143, chapterID);
}

/**
 * ChapterTrackSet, ChapterTrackUnlink and ChapterTrackLinks are the chapter
 * track link control's host half (chapter-track-link-control PRD Phase 1): Set
 * makes a track the chapter's one link, replacing its old one and saying which
 * chapter the track was taken from; Unlink clears every link a chapter holds;
 * Links reads every narration chapter's link state and track facts from one
 * parse of the saved .rpp.
 */
export function ChapterTrackSet(chapterID: string, trackGUID: string): $CancellablePromise<string> {
    return $Call.ByID(2127223998, chapterID, trackGUID);
}

export function ChapterTrackUnlink(chapterID: string): $CancellablePromise<string> {
    return $Call.ByID(2391887305, chapterID);
}

/**
 * ChaptersForTracks is ForTrack (ADR 0113) run over every GUID in guids: the
 * Review page's chapter grouping (diagnostics-delivery-and-cleanup-tools PRD
 * Phase 8 remainder) for findings that carry only a track, item or take GUID
 * rather than a manuscript-anchored chapter. One GUID the project no longer
 * has is reported as an error alongside the others, never as a failed call.
 * Read-only.
 */
export function ChaptersForTracks(guids: string[]): $CancellablePromise<string> {
    return $Call.ByID(1946035715, guids);
}

/**
 * CleanupToolsLaunch asks REAPER to open an allow-listed cleanup tool (cleanuptools.Tools: "repair_pops_clicks" or
 * "magnolius_declick") on the selected items. It changes nothing itself; the dialog it opens is the narrator's.
 */
export function CleanupToolsLaunch(tool: string): $CancellablePromise<string> {
    return $Call.ByID(4285613458, tool);
}

/**
 * CleanupToolsState answers the last launch's state (idle before any).
 */
export function CleanupToolsState(): $CancellablePromise<string> {
    return $Call.ByID(1749389626);
}

/**
 * CoverageCancel asks a running check to stop; the items it finished stay cached. With nothing running it does nothing.
 */
export function CoverageCancel(): $CancellablePromise<string> {
    return $Call.ByID(3481046670);
}

/**
 * CoverageResult reads a chapter's newest complete check back and says whether it is current, stale or never, with
 * reasons (coverage.ResultView). It never runs anything (Q14).
 */
export function CoverageResult(chapterID: string): $CancellablePromise<string> {
    return $Call.ByID(1771519125, chapterID);
}

/**
 * CoverageStart starts a recording check of one chapter with the narrator's Transcript Compare model (Q7 A). It
 * answers {status: "started", state}; {status: "refused", reason, message} when the chapter cannot be measured as the
 * saved project stands (nothing was run or written); or {status: "asset_required", ...} when the model is not
 * installed yet (the first-use gate TranscriptStart has). Anything else (a file that could not be written, a sidecar
 * that did not start) is a rejected promise.
 */
export function CoverageStart(chapterID: string): $CancellablePromise<string> {
    return $Call.ByID(2486826976, chapterID);
}

/**
 * CoverageState is the current check, or the last one that ended.
 */
export function CoverageState(): $CancellablePromise<string> {
    return $Call.ByID(2570420881);
}

/**
 * CreditsChapterAnnouncements renders body once per narration chapter, with the project's own tokens plus the chapter's
 * [Chapter] and [Chapter Title]. The Settings preview shows the first; the estimate times them all.
 */
export function CreditsChapterAnnouncements(body: string): $CancellablePromise<string> {
    return $Call.ByID(1178349043, body);
}

/**
 * CreditsDeleteTemplate removes a template from the library. The narrator
 * owns this library, so a shipped default may be deleted like any other.
 */
export function CreditsDeleteTemplate(id: string): $CancellablePromise<string> {
    return $Call.ByID(2098781057, id);
}

/**
 * CreditsDuplicateTemplate copies an existing template (including a shipped
 * default) as a new, editable entry.
 */
export function CreditsDuplicateTemplate(id: string): $CancellablePromise<string> {
    return $Call.ByID(3571604671, id);
}

/**
 * CreditsPreview renders text (a template body, or an unsaved draft the
 * narrator is still editing) with this project's own credit values, falling
 * back to the global narrator default for [Narrator] (C2), exactly as the
 * estimate and the teleprompter will render it in later phases (one
 * renderer, PRD "Technical Approach").
 */
export function CreditsPreview(body: string): $CancellablePromise<string> {
    return $Call.ByID(1805286028, body);
}

/**
 * CreditsProjectValues returns the current project's own credit token
 * values, the global narrator default, and suggestions seeded from the
 * imported manuscript's front matter and file metadata (C3, amended by
 * credits-token-setup-and-front-matter-detection.prd.md Phase 1) for any
 * field the project has not set yet. It never writes anything: suggestions
 * are for the narrator to accept or ignore. detected carries the same
 * candidates with their source and confidence (additive; suggestions alone
 * stays wire-compatible with what this always returned).
 */
export function CreditsProjectValues(): $CancellablePromise<string> {
    return $Call.ByID(1465719907);
}

/**
 * CreditsRetailSample reads this project's retail sample and measures it against the current manuscript. A saved range
 * whose lines are gone (the manuscript was replaced) is kept and reported as a problem rather than failing the read.
 */
export function CreditsRetailSample(): $CancellablePromise<string> {
    return $Call.ByID(1113046541);
}

/**
 * CreditsSaveProjectValues saves this project's own credit token values onto
 * the project manifest (C12: the manifest directly, now that it exists).
 */
export function CreditsSaveProjectValues(title: string, subtitle: string, author: string, series: string, bookNumber: string, copyrightText: string, year: string, copyrightHolder: string, publisher: string, narrator: string): $CancellablePromise<string> {
    return $Call.ByID(4267966884, title, subtitle, author, series, bookNumber, copyrightText, year, copyrightHolder, publisher, narrator);
}

/**
 * CreditsSaveRetailSample picks startParagraphID..endParagraphID (both included) as the retail sample, refusing a range
 * over 5 minutes (C10) and keeping the previous one when it does. Two empty ids clear it.
 */
export function CreditsSaveRetailSample(startParagraphID: string, endParagraphID: string): $CancellablePromise<string> {
    return $Call.ByID(2705978648, startParagraphID, endParagraphID);
}

/**
 * CreditsSaveTemplate creates a template (id empty) or updates one in place
 * (id set). kind is "opening", "closing" or "chapter_announcement" (C8).
 */
export function CreditsSaveTemplate(id: string, kind: string, name: string, body: string): $CancellablePromise<string> {
    return $Call.ByID(1424795947, id, kind, name, body);
}

/**
 * CreditsSetStatus sets kind ("opening" or "closing") to status (one of the five chapter statuses), refusing either an
 * unknown kind or an unknown status without writing anything.
 */
export function CreditsSetStatus(kind: string, status: string): $CancellablePromise<string> {
    return $Call.ByID(1128427018, kind, status);
}

/**
 * CreditsSetupDismiss records the narrator's answer to the prompt: "session" for "Not now" (this run of the app only)
 * or "project" for "Don't ask for this project" (stored on the manifest for this manuscript). It returns the new state.
 */
export function CreditsSetupDismiss(scope: string): $CancellablePromise<string> {
    return $Call.ByID(2480637187, scope);
}

/**
 * CreditsSetupSave fills the project's empty credits values from the prompt's fields (Values JSON keys to values)
 * and never replaces one already set, so an empty or stale prompt field cannot clear or overwrite the narrator's
 * own value. It returns the new state. "Use for all my projects" saves the global narrator through the settings
 * binding instead, with no narrator field here.
 */
export function CreditsSetupSave(fields: { [_ in string]?: string }): $CancellablePromise<string> {
    return $Call.ByID(829535288, fields);
}

/**
 * CreditsSetupState says whether to ask for the credits values and what to ask for. It only reads.
 */
export function CreditsSetupState(): $CancellablePromise<string> {
    return $Call.ByID(2742126118);
}

/**
 * CreditsStatuses reads this project's credits row statuses. A kind never set is simply absent from the map; the UI
 * treats that the same way it treats a manuscript chapter with no note: "not_started".
 */
export function CreditsStatuses(): $CancellablePromise<string> {
    return $Call.ByID(4098810442);
}

/**
 * CreditsTemplates lists the narrator's credit template library, seeding the
 * shipped defaults on first use.
 */
export function CreditsTemplates(): $CancellablePromise<string> {
    return $Call.ByID(2043422899);
}

/**
 * DawCatalogList answers today's DAW catalog (REAPER only) with each entry's
 * detection state, so a narrator with nothing installed can see what to get
 * and a narrator who already has REAPER sees it confirmed. Detection runs
 * fresh on every call (on demand, not polled - PRD Open Question A7); it
 * never blocks and never claims more certainty than
 * dawcatalog.Detect/DetectAll already give it (any detector error or empty
 * path is "not detected").
 */
export function DawCatalogList(): $CancellablePromise<string> {
    return $Call.ByID(4009222857);
}

/**
 * DawCatalogOpenDownloadPage opens the catalog entry id's official download
 * page in the narrator's default browser, and nothing else: it never
 * downloads, verifies or executes an installer (PRD "What We're NOT
 * Building"). id crosses the Wails boundary, never a URL - the destination
 * is always looked up server-side in the hardcoded dawcatalog.Catalog by
 * dawcatalog.Lookup, so nothing UI-supplied can pick an arbitrary
 * destination (PRD architecture notes; mirrors update.go's
 * openReleaseNotes, the same trusted-URL discipline for the same reason).
 */
export function DawCatalogOpenDownloadPage(id: string): $CancellablePromise<string> {
    return $Call.ByID(3237751086, id);
}

/**
 * DawLaunch starts REAPER on the current project's linked DAW file (Phase 8,
 * docs/prds/project-workspace-and-daw-link.prd.md): it resolves reaper.exe (a
 * Settings override always wins, otherwise auto-detect - daw.Resolve /
 * daw.LocateReaperExecutable, ADR 0092 W11), and passes the linked .rpp,
 * plus, when the DAW.auto_start_launcher setting is on (owner decision D10,
 * default OFF), the launcher script too - the exact
 * `reaper.exe "<project.rpp>" "<script.lua>"` form spike S6 confirmed REAPER
 * runs automatically at startup (ADR 0092 W12), so the bridge is live
 * without the narrator running the action by hand. The launch is detached
 * (daw.Launch): never through the sidecar supervisor's kill-on-close job
 * object (internal/process/job_windows.go), so REAPER outlives the app when
 * the narrator closes it.
 */
export function DawLaunch(): $CancellablePromise<string> {
    return $Call.ByID(739370161);
}

/**
 * DeliveryDeleteProfile deletes a custom profile and answers the profiles again; a project that chose it is judged
 * against the Global default from then on, with a notice.
 */
export function DeliveryDeleteProfile(id: string): $CancellablePromise<string> {
    return $Call.ByID(2497531970, id);
}

/**
 * DeliveryDuplicateProfile copies a profile (a built-in at version, or a custom one) into a new custom profile and
 * answers it (Phase 4).
 */
export function DeliveryDuplicateProfile(id: string, version: string): $CancellablePromise<string> {
    return $Call.ByID(3290179432, id, version);
}

/**
 * DeliveryExportReport writes the report of the last measurement and diagnostics check (Phase 7) as an HTML and a JSON
 * file in the project's narration-utils/delivery folder, and answers where. includePaths is the narrator's choice to
 * write each file's full path; off, only file names are written. It refuses without a project, while a measurement or a
 * check runs, or when nothing has been measured or checked.
 */
export function DeliveryExportReport(includePaths: boolean): $CancellablePromise<string> {
    return $Call.ByID(54436238, includePaths);
}

/**
 * DeliveryProfiles answers every delivery profile the narrator can choose (the built-ins first, then their custom
 * profiles), the Global default, the current project's own choice and the profile it is judged against
 * (delivery-platform-profiles.prd.md Phase 2, ADR 0179).
 */
export function DeliveryProfiles(): $CancellablePromise<string> {
    return $Call.ByID(1745272024);
}

/**
 * DeliverySaveProfile saves a custom profile's name, numbers and rules turned off (Phase 4), from the editor's JSON
 * ({id, name, rules: [{id, off, min, max}]}), and answers it with its revision bumped. A built-in is never written.
 */
export function DeliverySaveProfile(edit: string): $CancellablePromise<string> {
    return $Call.ByID(1460317916, edit);
}

/**
 * DeliverySelectProfile saves a choice of profile and answers the profiles again: scope "global" sets the Global
 * default, scope "project" the current project's own choice (an empty id clears it, so the Global default judges it).
 * A built-in is chosen at its version; a custom profile always judges with its latest revision.
 */
export function DeliverySelectProfile(scope: string, id: string, version: string): $CancellablePromise<string> {
    return $Call.ByID(122359795, scope, id, version);
}

/**
 * DiagnosticsAnalyze checks picked files as a job and answers it. sourceKind is raw_recording or processed_render, as
 * the narrator says; it refuses anything else, a path that was not picked, more than maxMeasureFiles files, or a second
 * check while one runs.
 */
export function DiagnosticsAnalyze(paths: string[], sourceKind: string): $CancellablePromise<string> {
    return $Call.ByID(522143006, paths, sourceKind);
}

/**
 * DiagnosticsCancel stops a running check; files already checked keep their results. With none running it changes
 * nothing.
 */
export function DiagnosticsCancel(): $CancellablePromise<string> {
    return $Call.ByID(163956788);
}

/**
 * DiagnosticsState answers the check: idle with the thresholds it would use, running with real progress, or how it
 * ended with every file's summary and findings.
 */
export function DiagnosticsState(): $CancellablePromise<string> {
    return $Call.ByID(2198027203);
}

/**
 * FindingsAddMarker adds one take marker in REAPER at an accepted finding's spot, on its take, named like the marker
 * Transcript Compare's export adds (approvedMarker). A finding not accepted, one with no item or no time in its audio,
 * and a REAPER that is not listening are refused before anything is sent.
 */
export function FindingsAddMarker(id: string): $CancellablePromise<string> {
    return $Call.ByID(1612469037, id);
}

/**
 * FindingsGet answers the finding with id, or an error when the store no longer has it (an analyzer
 * re-run or a manuscript replacement can remove it while the page shows it).
 */
export function FindingsGet(id: string): $CancellablePromise<string> {
    return $Call.ByID(795298128, id);
}

/**
 * FindingsGoTo selects the finding's item in REAPER and puts the edit cursor on its spot (its item's start when it has
 * no time in its audio).
 */
export function FindingsGoTo(id: string): $CancellablePromise<string> {
    return $Call.ByID(1353036263, id);
}

/**
 * FindingsGoToRead is FindingsGoTo for one read of a finding that groups several (a take-review pickup or duplicate
 * read, take-review-pickups-duplicates-take-intelligence.prd.md Phase 5): read is the index in its evidence.members,
 * and REAPER goes to that read's own item and take, at the start of its range in its own source. A read index the
 * finding does not have is an error, not a refusal: the page only offers the reads it was sent.
 */
export function FindingsGoToRead(id: string, read: number): $CancellablePromise<string> {
    return $Call.ByID(2921722827, id, read);
}

/**
 * FindingsList answers one page of the findings that match query, and how many matched in all.
 */
export function FindingsList(query: $models.FindingsQuery): $CancellablePromise<string> {
    return $Call.ByID(2015341116, query);
}

/**
 * FindingsLoop loops the finding's context in REAPER: the time selection and loop points around it, repeat on, and
 * Play (Q6). The narrator's own selection and repeat come back with FindingsStopLoop.
 */
export function FindingsLoop(id: string): $CancellablePromise<string> {
    return $Call.ByID(499300970, id);
}

/**
 * FindingsLoopRead loops one read of a finding in REAPER, as FindingsLoop does, over that read's own range. The loop is
 * the finding's, so FindingsReaperStatus names the finding and FindingsStopLoop stops it. REAPER plays the item's
 * active take: a read that is another take of its item is heard as itself through the in-app audition instead.
 */
export function FindingsLoopRead(id: string, read: number): $CancellablePromise<string> {
    return $Call.ByID(3171307890, id, read);
}

/**
 * FindingsReaperStatus answers whether REAPER is there for Go to and Loop, without sending REAPER anything: it reads
 * the heartbeat REAPER's script already broadcasts (daw.Reachability, ADR 0092), so the page can poll it.
 */
export function FindingsReaperStatus(): $CancellablePromise<string> {
    return $Call.ByID(1717933253);
}

/**
 * FindingsReview records the narrator's decision on a finding, made against evidenceVersion (the
 * finding's evidence_version as the page showed it), and answers the finding as the store now holds it.
 * It refuses a finding whose evidence changed since it was shown, so a decision is never applied to
 * evidence the narrator did not see; the page reloads it and the narrator decides again. status may be
 * "unreviewed" to reopen a decision. The history stays append-only (findings.Store.RecordDecision).
 */
export function FindingsReview(id: string, evidenceVersion: string, status: string, note: string): $CancellablePromise<string> {
    return $Call.ByID(2720723528, id, evidenceVersion, status, note);
}

/**
 * FindingsStopLoop stops the loop and puts back the time selection, loop points and repeat the narrator had, keeping
 * any they changed while it played. With no loop of this app's running it changes nothing.
 */
export function FindingsStopLoop(): $CancellablePromise<string> {
    return $Call.ByID(957107010);
}

/**
 * FindingsSummary answers the review queue at a glance: counts by status (the navigation badge is the
 * unreviewed count) and the analyzers, categories and chapters present, for the page's filters.
 */
export function FindingsSummary(): $CancellablePromise<string> {
    return $Call.ByID(2119633852);
}

/**
 * GuideBuild starts the Story Bible build, or asks for the language model it needs first (see startGuideBuild). rulesOnly builds without one
 * for this run.
 */
export function GuideBuild(rulesOnly: boolean): $CancellablePromise<string> {
    return $Call.ByID(2237994534, rulesOnly);
}

export function GuideBuildState(): $CancellablePromise<string> {
    return $Call.ByID(1236161883);
}

export function GuideCreate(name: string, category: string, aliases: string[]): $CancellablePromise<string> {
    return $Call.ByID(4087272090, name, category, aliases);
}

export function GuideDelete(id: string): $CancellablePromise<string> {
    return $Call.ByID(2382640937, id);
}

export function GuideEdit(id: string, values: { [_ in string]?: string }): $CancellablePromise<string> {
    return $Call.ByID(275232098, id, values);
}

export function GuideEntities(): $CancellablePromise<string> {
    return $Call.ByID(1537717617);
}

export function GuideMerge(sourceID: string, targetID: string): $CancellablePromise<string> {
    return $Call.ByID(98047630, sourceID, targetID);
}

export function GuidePreview(id: string, aliasIndex: number | null): $CancellablePromise<string> {
    return $Call.ByID(2311298802, id, aliasIndex);
}

export function GuidePronounce(id: string, aliasIndex: number | null, source: string): $CancellablePromise<string> {
    return $Call.ByID(1577834145, id, aliasIndex, source);
}

export function GuideRelate(id: string, otherID: string, label: string): $CancellablePromise<string> {
    return $Call.ByID(761657167, id, otherID, label);
}

export function GuideRescan(id: string): $CancellablePromise<string> {
    return $Call.ByID(2984124370, id);
}

export function GuideSetLocked(id: string, locked: boolean): $CancellablePromise<string> {
    return $Call.ByID(2024869160, id, locked);
}

export function GuideUnrelate(id: string, otherID: string, label: string): $CancellablePromise<string> {
    return $Call.ByID(171684836, id, otherID, label);
}

export function LineIdentityRead(): $CancellablePromise<string> {
    return $Call.ByID(113499758);
}

export function LineIdentityStamp(rows: $models.LineIdentityStampRow[], overwrite: boolean): $CancellablePromise<string> {
    return $Call.ByID(1181172373, rows, overwrite);
}

export function LineIdentityState(): $CancellablePromise<string> {
    return $Call.ByID(1026083755);
}

/**
 * ManuscriptBeginImport starts an import for the manuscript file Bootstrap
 * offered in the project folder. Only that exact file is accepted.
 */
export function ManuscriptBeginImport(path: string): $CancellablePromise<string> {
    return $Call.ByID(3813124518, path);
}

export function ManuscriptChapters(): $CancellablePromise<string> {
    return $Call.ByID(3512984248);
}

export function ManuscriptClearProjectData(confirmed: boolean): $CancellablePromise<string> {
    return $Call.ByID(3870475648, confirmed);
}

export function ManuscriptCreateBookmark(values: { [_ in string]?: any }): $CancellablePromise<string> {
    return $Call.ByID(322983534, values);
}

export function ManuscriptCreateNote(chapterID: string, paragraphID: string, text: string, anchorText: string, anchorStart: number | null, anchorEnd: number | null): $CancellablePromise<string> {
    return $Call.ByID(3408945682, chapterID, paragraphID, text, anchorText, anchorStart, anchorEnd);
}

export function ManuscriptDeleteBookmark(id: string): $CancellablePromise<string> {
    return $Call.ByID(3257770689, id);
}

export function ManuscriptDeleteNote(id: string): $CancellablePromise<string> {
    return $Call.ByID(612332533, id);
}

export function ManuscriptImportCancel(jobID: string): $CancellablePromise<string> {
    return $Call.ByID(2367548281, jobID);
}

/**
 * ManuscriptImportCommit writes the previewed manuscript with the narrator's review choices: each section's kind, the character
 * suggestions to seed, and, for a section with a subtitle, whether it is one (subtitleOverrides, keyed by section id; false joins
 * the line to the title or returns it to the body, story-bible-and-import-ux-briefs PRD, Phase 5).
 */
export function ManuscriptImportCommit(jobID: string, confirmedReset: boolean, sectionKinds: { [_ in string]?: string }, characterCandidateIDs: string[], subtitleOverrides: { [_ in string]?: boolean }): $CancellablePromise<string> {
    return $Call.ByID(1010816278, jobID, confirmedReset, sectionKinds, characterCandidateIDs, subtitleOverrides);
}

export function ManuscriptImportPreview(jobID: string, markdownHeadingLevel: number): $CancellablePromise<string> {
    return $Call.ByID(3597275209, jobID, markdownHeadingLevel);
}

export function ManuscriptImportState(jobID: string): $CancellablePromise<string> {
    return $Call.ByID(1705148176, jobID);
}

export function ManuscriptNotes(chapter: string): $CancellablePromise<string> {
    return $Call.ByID(26775399, chapter);
}

export function ManuscriptParagraphs(chapter: string): $CancellablePromise<string> {
    return $Call.ByID(3533633545, chapter);
}

export function ManuscriptReader(): $CancellablePromise<string> {
    return $Call.ByID(3976609117);
}

export function ManuscriptReaderState(): $CancellablePromise<string> {
    return $Call.ByID(3073538398);
}

export function ManuscriptSaveReaderState(activeChapter: string, activeSourceLine: number | null, expandedChapters: string[]): $CancellablePromise<string> {
    return $Call.ByID(574229509, activeChapter, activeSourceLine, expandedChapters);
}

export function ManuscriptSearch(query: string): $CancellablePromise<string> {
    return $Call.ByID(2029600330, query);
}

export function ManuscriptSelectFile(): $CancellablePromise<string> {
    return $Call.ByID(258840892);
}

/**
 * ManuscriptSetChapterKind reclassifies a chapter after import (chapter-track-link-control PRD Phase 3):
 * "reference" or "opening" removes it from recording, "narration" restores it. A removal clears the chapter's
 * track links (TL5 A). See manuscriptSetChapterKind.
 */
export function ManuscriptSetChapterKind(chapterID: string, kind: string): $CancellablePromise<string> {
    return $Call.ByID(3035504737, chapterID, kind);
}

export function ManuscriptSetChapterStatus(chapter: string, status: string): $CancellablePromise<string> {
    return $Call.ByID(2496889981, chapter, status);
}

/**
 * MeasureAnalyze measures picked files as a job and answers it; it refuses a path that was not picked, more than
 * maxMeasureFiles files, or a second measurement while one runs.
 */
export function MeasureAnalyze(paths: string[]): $CancellablePromise<string> {
    return $Call.ByID(877462154, paths);
}

/**
 * MeasureCancel stops a running measurement; files already measured keep their results. With none running it changes
 * nothing.
 */
export function MeasureCancel(): $CancellablePromise<string> {
    return $Call.ByID(3503540504);
}

/**
 * MeasurePickFiles opens the operating system's picker for the audio files to measure and answers the chosen paths
 * (none when the narrator closes it). Only paths chosen here can be measured.
 */
export function MeasurePickFiles(): $CancellablePromise<string> {
    return $Call.ByID(1366133682);
}

/**
 * MeasureState answers the measurement job: idle, running with real progress, or how it ended with every file's result,
 * each measured file judged against the project's delivery profile as it is now.
 */
export function MeasureState(): $CancellablePromise<string> {
    return $Call.ByID(2552163807);
}

export function PickupsCount(): $CancellablePromise<string> {
    return $Call.ByID(3462748130);
}

export function PickupsExport(): $CancellablePromise<string> {
    return $Call.ByID(2172891289);
}

/**
 * PickupsImport parses and validates csvText (start,note,tag; a header row is optional) entirely in Go before
 * anything is sent to REAPER. A row that cannot be used is reported, not dropped; when every row is unusable
 * nothing is sent and the row report is the error.
 */
export function PickupsImport(csvText: string): $CancellablePromise<string> {
    return $Call.ByID(2264841114, csvText);
}

export function PickupsNext(): $CancellablePromise<string> {
    return $Call.ByID(1607807066);
}

export function PickupsResolve(position: number): $CancellablePromise<string> {
    return $Call.ByID(695766573, position);
}

export function PickupsState(): $CancellablePromise<string> {
    return $Call.ByID(2662291732);
}

/**
 * ProjectCreateIn makes a new project.json-manifested folder named name under
 * parent (the PRD's "Visual Studio model": a name plus a location) and
 * attaches it, replacing the old full-path ProjectCreate (PRD W9). An empty
 * parent defaults to the Phase 1 projects directory (project.ResolveDir), so
 * the picker's default "Create new" needs only a name. name is validated
 * (project.ValidateName: non-empty, no illegal or control characters, not a
 * Windows reserved device name) before parent is even resolved, and the busy
 * check comes before any MkdirAll, so a refused or invalid create leaves no
 * folder behind; the check is a pre-check only, ProjectSwitch asks again
 * under the write lock, so a lost race at worst leaves an empty folder.
 */
export function ProjectCreateIn(parent: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(2967277492, parent, name);
}

/**
 * ProjectLinkDawFile is the one shared binding behind the header pill, the
 * Tracks page and Settings' DAW category (PRD project-workspace-and-daw-
 * link.prd.md, Open Question W19): it opens a native "*.rpp" file dialog and
 * links the chosen file to the current project through the manifest storage
 * Phase 1-3 already built (project.BuildDawLink, Manifest.Save). Cancelling
 * the dialog is not an error: the result says so instead.
 */
export function ProjectLinkDawFile(): $CancellablePromise<string> {
    return $Call.ByID(3697640847);
}

export function ProjectRecents(): $CancellablePromise<string> {
    return $Call.ByID(535019029);
}

/**
 * ProjectRemoveRecent drops path from the recent-projects list and returns
 * the updated list, so the caller can re-render from the response instead of
 * making a second round trip.
 */
export function ProjectRemoveRecent(path: string): $CancellablePromise<string> {
    return $Call.ByID(614385112, path);
}

export function ProjectSelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(3945872051);
}

/**
 * ProjectStateChangedSince reports whether current differs from baseline (REAPER's edit counter only ever
 * increases while a project stays open): a pure comparison, so a caller with its own baseline never needs a
 * fresh Check just to compare two counts it already has.
 */
export function ProjectStateChangedSince(current: number, baseline: number): $CancellablePromise<string> {
    return $Call.ByID(1874672174, current, baseline);
}

/**
 * ProjectStateCheck asks REAPER (when it is open from this app) for its live change count and the current
 * project's saved-file path. The result (ProjectStateState's changeCount, projectFile and savedModifiedAt) comes
 * back once REAPER answers; with no bridge it fails immediately, so a caller can fall back to a saved-file-mtime
 * basis without waiting.
 */
export function ProjectStateCheck(): $CancellablePromise<string> {
    return $Call.ByID(4248506512);
}

export function ProjectStateState(): $CancellablePromise<string> {
    return $Call.ByID(1931134061);
}

/**
 * ProjectSwitch is the single choke point for attaching a picker-chosen
 * project: both "open recent" and post-browse/create-new flows call this, so
 * system:attached emission and recents-touching happen in exactly one place.
 */
export function ProjectSwitch(path: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(633630375, path, name);
}

/**
 * ReadAloudReaperState answers whether REAPER is ready to record chapterID with reading
 * (read-aloud-control-bar.prd.md Phase 6): its linked track the one track armed, and REAPER not already recording. A
 * chapter with no link, a REAPER that is not there and the experimental switch being off are answers, not errors; only
 * a chapter the manuscript does not have is an error. It reads, and changes nothing in REAPER.
 */
export function ReadAloudReaperState(chapterID: string): $CancellablePromise<string> {
    return $Call.ByID(1177651655, chapterID);
}

export function Ready(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3393741589).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RenderConfigConfigure asks REAPER to set the render bounds to all regions, the naming pattern to the region
 * name, and the output folder to outputFolder. It never renders anything: the narrator presses Render themselves
 * once the resulting file names (RenderConfigState's targets, once the run succeeds) look right.
 */
export function RenderConfigConfigure(outputFolder: string): $CancellablePromise<string> {
    return $Call.ByID(2148728528, outputFolder);
}

export function RenderConfigState(): $CancellablePromise<string> {
    return $Call.ByID(2252557001);
}

/**
 * RenderConfigSuggestFolder answers a default output folder (a "renders" subfolder of the project) for the UI to
 * prefill; the narrator can change it before configuring.
 */
export function RenderConfigSuggestFolder(): $CancellablePromise<string> {
    return $Call.ByID(2955207070);
}

/**
 * RetakeLanesList lists, from the saved REAPER project the Tracks page reads, every manuscript line whose retakes sit
 * on more than one fixed lane of a track, and which lane plays.
 */
export function RetakeLanesList(): $CancellablePromise<string> {
    return $Call.ByID(1618739891);
}

/**
 * RetakeLanesPick asks REAPER to make the retake named by lineID and itemGUID the only lane playing on its track, in
 * one undo step. Only a retake RetakeLanesList lists can be picked; nothing else in the project changes.
 */
export function RetakeLanesPick(lineID: string, itemGUID: string): $CancellablePromise<string> {
    return $Call.ByID(3760905438, lineID, itemGUID);
}

/**
 * RetakeLanesState answers the last pick's state (idle before any).
 */
export function RetakeLanesState(): $CancellablePromise<string> {
    return $Call.ByID(523795916);
}

/**
 * StageConfirm sets the chapter's status to target and records the basis the narrator saw, if basisKey is still the one
 * the evidence gives. It answers {status: "ok", chapter} or {status: "refused", reason, message}.
 */
export function StageConfirm(chapterID: string, target: string, basisKey: string): $CancellablePromise<string> {
    return $Call.ByID(2562262688, chapterID, target, basisKey);
}

/**
 * StageDismiss hides the chapter's suggestion of target until its basis changes (Q7); the status is untouched.
 */
export function StageDismiss(chapterID: string, target: string, basisKey: string): $CancellablePromise<string> {
    return $Call.ByID(962870692, chapterID, target, basisKey);
}

/**
 * StageRecommendations assesses every narration chapter of the manuscript. It reads stored evidence only.
 */
export function StageRecommendations(): $CancellablePromise<string> {
    return $Call.ByID(3890515400);
}

/**
 * StageRevert returns a chapter with a live confirmation to the stage it was confirmed from.
 */
export function StageRevert(chapterID: string): $CancellablePromise<string> {
    return $Call.ByID(1764017358, chapterID);
}

/**
 * SystemLookup looks one word from the manuscript reader up in the offline dictionary (ADR 0097: the Open English WordNet, read from Go in
 * this process; no cloud API and no server). The answer is one of:
 * 
 *   - "ok": the word the lookup used (normalised: lower case, surrounding punctuation removed), one entry per headword and part of speech
 *     (none when the dictionary does not have the word), and the dictionary with the attribution its licence requires the UI to show;
 *   - "asset_required": the dictionary is not installed (or did not verify), with its sizes, licence and where it would be stored, so the UI
 *     offers the standard first-use download. Nothing is downloaded here: only AssetsInstall("dictionary", id), which the narrator confirms,
 *     does that.
 * 
 * A selection that is not one word is an error the UI shows as it is. The dictionary is not project-scoped: it is read through the
 * set-once asset registry, not the project services (so there is no h.services() snapshot to take).
 */
export function SystemCopyDiagnostics(scope: string): $CancellablePromise<string> {
    return $Call.ByID(399038062, scope);
}

export function SystemLookup(word: string): $CancellablePromise<string> {
    return $Call.ByID(3310775553, word);
}

/**
 * SystemNotify raises one OS notification when General.notifications is on (N1-N4). It never surfaces an error to the
 * caller: a notification is a courtesy, never load-bearing, so a failed or unavailable sender is logged and swallowed
 * (docs/architecture/notifications.md). Which job qualifies (the window must be unfocused and the job must have taken
 * about 10s or more) is decided in the webview, which is the only side that knows whether the window has focus
 * (N1: this is still so on Wails v3, whose window focus is not asked for here).
 * 
 * The Wails notification service is initialized lazily, on the first call that reaches here with the setting on, so a
 * narrator who has notifications off never gets the per-user registry key Windows notifications need (N2).
 */
export function SystemNotify(kind: string, title: string, body: string): $CancellablePromise<string> {
    return $Call.ByID(529278034, kind, title, body);
}

export function SystemOpenLogFolder(): $CancellablePromise<string> {
    return $Call.ByID(2499200111);
}

export function SystemReportDiagnostic(kind: string, message: string): $CancellablePromise<string> {
    return $Call.ByID(4083438554, kind, message);
}

export function SystemSaveSettings(tool: string, scope: string, values: { [_ in string]?: string | null }): $CancellablePromise<string> {
    return $Call.ByID(2824066503, tool, scope, values);
}

export function SystemSettingsForScope(scope: string): $CancellablePromise<string> {
    return $Call.ByID(675135303, scope);
}

/**
 * TakeComparisonCancel stops a running comparison; nothing is saved. With none running it changes nothing.
 */
export function TakeComparisonCancel(): $CancellablePromise<string> {
    return $Call.ByID(1970715310);
}

/**
 * TakeComparisonStart compares the takes of one take-review group as a job (take-review phase 10, ADR 0165): findingID
 * names the group; the reads, their audio and the manuscript span all come from the store and the saved project. It
 * answers the job; TakeComparisonState reports its real progress and TakeComparisonCancel stops it. The comparison is a
 * take_comparison finding, read and decided through the generic findings bindings.
 */
export function TakeComparisonStart(findingID: string): $CancellablePromise<string> {
    return $Call.ByID(166408064, findingID);
}

/**
 * TakeComparisonState answers the comparison job: idle, running, or how it ended (with the comparison's finding id).
 */
export function TakeComparisonState(): $CancellablePromise<string> {
    return $Call.ByID(250001969);
}

/**
 * TakeReviewCreateTake adds a narrator-approved candidate's source range as a
 * new take on the target item (take-review phase 6): findingID is the
 * finding this candidate came from (provenance, ADR 0098); targetItemGUID
 * is the item the narrator explicitly chose (never preselected);
 * candidateItemGUID is the candidate's own item GUID when it has one (empty
 * skips that extra staleness check); sourceFile, sourceRangeStart and
 * sourceRangeEnd (seconds, source-file-relative) locate the candidate's
 * matched span within its own source. The previously active take and the
 * item's length are never touched (the phase 1 spike).
 */
export function TakeReviewCreateTake(findingID: string, targetItemGUID: string, candidateItemGUID: string, sourceFile: string, sourceRangeStart: number, sourceRangeEnd: number): $CancellablePromise<string> {
    return $Call.ByID(3742993354, findingID, targetItemGUID, candidateItemGUID, sourceFile, sourceRangeStart, sourceRangeEnd);
}

/**
 * TakeReviewScanCancel stops a running scan; nothing it found is saved. With no scan running it changes nothing.
 */
export function TakeReviewScanCancel(): $CancellablePromise<string> {
    return $Call.ByID(2539611526);
}

/**
 * TakeReviewScanStart starts a pickup and duplicate scan of scope as a job (take-review phase 5): the chapter track's
 * items and takes, plus at most one pickup track or time range (Q3). It answers the job; TakeReviewScanState reports
 * its real progress (ADR 0015) and TakeReviewScanCancel stops it. The findings it saves are read and decided through
 * the Review page's generic findings bindings (ADR 0120), like every other analyzer's.
 */
export function TakeReviewScanStart(scope: $models.TakeReviewScanScope): $CancellablePromise<string> {
    return $Call.ByID(2149397544, scope);
}

/**
 * TakeReviewScanState answers the scan job: idle (with the project's saved pickup scope to offer), running, or how it
 * ended.
 */
export function TakeReviewScanState(): $CancellablePromise<string> {
    return $Call.ByID(1696107641);
}

/**
 * TeleprompterDevices lists the input devices the teleprompter's capture path can open, by the name it opens them
 * under (docs/prds/teleprompter-engines-and-input-devices.prd.md Phase 1). It never fails Start-style: a listing
 * problem comes back as `{"devices": [], "error": "..."}`, not a rejected promise, so a caller can always still try
 * to start with a device the narrator picked before.
 */
export function TeleprompterDevices(): $CancellablePromise<string> {
    return $Call.ByID(122676926);
}

/**
 * TeleprompterLocate finds where to resume reading chapterID from what is already recorded (teleprompter-manuscript-
 * integration PRD Phase 9, ADR 0111): the chapter's track (the matcher's confident track, or trackGUID when the
 * narrator picked one), where its audio ends as of the .rpp's last save (Phase 8), and the last
 * teleprompter.DefaultTailSeconds before that end transcribed and placed in the chapter by the sidecar. model is the
 * Whisper model id ("" for the teleprompter's default); like TeleprompterStart it answers asset_required instead of
 * downloading one, but only once there is audio to read. Every other answer carries the prompter's last reading and the
 * reconciled verdict (PRD Phase 3). It only reads: nothing is recorded, moved or linked.
 */
export function TeleprompterLocate(chapterID: string, trackGUID: string, model: string): $CancellablePromise<string> {
    return $Call.ByID(379348061, chapterID, trackGUID, model);
}

/**
 * TeleprompterMeterStart shows the chosen microphone's level before reading starts (read-aloud-control-bar.prd.md Phase 4):
 * a separate `--meter` sidecar child that loads no model and prints only `level` events, relayed as "teleprompter:event"
 * like a session's own, then one `meter_stopped` when it ends. It replaces a meter already running, and is refused while a
 * session runs (the session reports its own levels) or with no microphone chosen.
 */
export function TeleprompterMeterStart(device: string): $CancellablePromise<string> {
    return $Call.ByID(2550739876, device);
}

/**
 * TeleprompterMeterStop ends the level meter (the microphone popover closed); it does nothing when none runs.
 */
export function TeleprompterMeterStop(): $CancellablePromise<string> {
    return $Call.ByID(3642172832);
}

/**
 * TeleprompterPause stops (true) or restarts (false) a running session's listening without ending it
 * (read-aloud-control-bar.prd.md Phase 5, ADR 0248): the microphone stays open and its level still shows, the recognizer
 * hears nothing and the tracker holds its word. The state keeps phase "running" with `paused` set. It errors when no
 * session is running.
 */
export function TeleprompterPause(paused: boolean): $CancellablePromise<string> {
    return $Call.ByID(3709351835, paused);
}

/**
 * TeleprompterReaperInput answers which of the teleprompter's microphones REAPER records from, so the picker can
 * preselect it with a reason (teleprompter-manuscript-integration.prd.md Phase 11). It asks REAPER once, read-only,
 * and never on a timer; a REAPER that is not there or cannot say is an answer, and the picker then keeps its list.
 */
export function TeleprompterReaperInput(): $CancellablePromise<string> {
    return $Call.ByID(3054312412);
}

/**
 * TeleprompterSaveFlags writes a read-aloud session's suspected flags into the project's findings store as unreviewed
 * findings (teleprompter-manuscript-integration.prd.md Phase 7, ADR 0117): a misread, extra or skip as a
 * transcript_discrepancy, a restart as a pickup. The dialog calls it when a session ends and when it closes, so it is
 * idempotent: a finding's id comes from the manuscript words, a repeat is one finding, and a flag the narrator dismissed
 * is recorded once as a dismissed decision, never deleted. It answers one finding per flag, in order, as stored, so the
 * dialog learns which flags an earlier session already dismissed.
 */
export function TeleprompterSaveFlags(chapterID: string, flags: liveflags$0.Flag[]): $CancellablePromise<string> {
    return $Call.ByID(3452602057, chapterID, flags);
}

/**
 * TeleprompterSeek moves a running session's tracker straight to script word `word` (the read-aloud modal's "Start
 * here"/"Go back to here", teleprompter-manuscript-integration.prd.md Phase 3): one line appended to the session's
 * control file, the sentinel-file pattern service.Seek documents. Errors (no service, no running session, a write
 * failure) come back as a rejected promise, the same shape as every other teleprompter binding failure.
 */
export function TeleprompterSeek(word: number): $CancellablePromise<string> {
    return $Call.ByID(4028463423, word);
}

/**
 * TeleprompterStart begins a live teleprompter session for one manuscript
 * chapter with the engine the request names (Whisper when it names none). Like
 * TranscriptStart it stops at the first-use gate when that engine's model is not
 * installed and reports it as asset_required, tagged with the engine so the UI
 * installs it through the right asset kind; once running, the sidecar's events
 * arrive as "teleprompter:event" and phase changes as "teleprompter:state".
 */
export function TeleprompterStart(options: { [_ in string]?: string }): $CancellablePromise<string> {
    return $Call.ByID(2257611617, options);
}

export function TeleprompterState(): $CancellablePromise<string> {
    return $Call.ByID(1904987428);
}

export function TeleprompterStop(): $CancellablePromise<string> {
    return $Call.ByID(1610168667);
}

export function TracksDiscover(): $CancellablePromise<string> {
    return $Call.ByID(1450079861);
}

export function TracksList(): $CancellablePromise<string> {
    return $Call.ByID(3388241406);
}

export function TracksSelect(path: string): $CancellablePromise<string> {
    return $Call.ByID(2374312442, path);
}

export function TranscriptAddEquivalence(id: string): $CancellablePromise<string> {
    return $Call.ByID(196067889, id);
}

export function TranscriptCancel(): $CancellablePromise<string> {
    return $Call.ByID(2396207262);
}

export function TranscriptExportMarkers(): $CancellablePromise<string> {
    return $Call.ByID(3516243881);
}

export function TranscriptHints(): $CancellablePromise<string> {
    return $Call.ByID(1808960066);
}

export function TranscriptJump(id: string): $CancellablePromise<string> {
    return $Call.ByID(275761128, id);
}

export function TranscriptLastCompleted(): $CancellablePromise<string> {
    return $Call.ByID(695536997);
}

export function TranscriptReset(): $CancellablePromise<string> {
    return $Call.ByID(626775787);
}

export function TranscriptSaveHints(accepted: string[]): $CancellablePromise<string> {
    return $Call.ByID(1025447533, accepted);
}

export function TranscriptStart(options: { [_ in string]?: string }): $CancellablePromise<string> {
    return $Call.ByID(2849953296, options);
}

export function TranscriptSuggestHints(): $CancellablePromise<string> {
    return $Call.ByID(3967109440);
}

export function TtsCatalog(): $CancellablePromise<string> {
    return $Call.ByID(29725922);
}

export function TtsInstall(voiceID: string): $CancellablePromise<string> {
    return $Call.ByID(689160454, voiceID);
}

export function TtsInstallCancel(jobID: string): $CancellablePromise<string> {
    return $Call.ByID(725365980, jobID);
}

export function TtsInstallState(jobID: string): $CancellablePromise<string> {
    return $Call.ByID(2657027067, jobID);
}

export function TtsRemove(voiceID: string): $CancellablePromise<string> {
    return $Call.ByID(2665374435, voiceID);
}

/**
 * UpdateCheck asks GitHub for the release list now (the Check now button). Whatever happens, the answer is the status: a check that
 * failed says why in `failure`.
 */
export function UpdateCheck(): $CancellablePromise<string> {
    return $Call.ByID(3860930353);
}

/**
 * UpdateDownload starts downloading the release the last check found, when this program can install it. It is the narrator's explicit
 * action and the only thing that downloads the update; progress is polled with UpdateJobState.
 */
export function UpdateDownload(): $CancellablePromise<string> {
    return $Call.ByID(252013003);
}

/**
 * UpdateInstall replaces the running program with the downloaded update and starts it: the narrator's explicit action, refused while
 * an import, a Story Bible build, a download, a comparison or a teleprompter session is running. On success the app closes a moment
 * after this answers; on failure the running version is unchanged and the answer is an error to read.
 */
export function UpdateInstall(jobID: string): $CancellablePromise<string> {
    return $Call.ByID(408381510, jobID);
}

/**
 * UpdateJobCancel stops the download. What was fetched is removed while the file is still arriving; a zip that had arrived and been
 * verified is kept, so trying again does not fetch it a second time.
 */
export function UpdateJobCancel(jobID: string): $CancellablePromise<string> {
    return $Call.ByID(855676764, jobID);
}

/**
 * UpdateJobState is the download's phase and its real bytes.
 */
export function UpdateJobState(jobID: string): $CancellablePromise<string> {
    return $Call.ByID(40937339, jobID);
}

/**
 * UpdateOpenNotes opens the release notes of the release the last check found in the narrator's browser. It takes no address.
 */
export function UpdateOpenNotes(): $CancellablePromise<string> {
    return $Call.ByID(2060363696);
}

/**
 * UpdateShowDownload opens the folder that holds the downloaded update, for an install the app is not allowed to replace itself in.
 */
export function UpdateShowDownload(): $CancellablePromise<string> {
    return $Call.ByID(3005300290);
}

/**
 * UpdateStatus is the running version, the update channel, when the last check was and whether the newest release on the channel is
 * newer than the running version. It answers from what the last check remembered and makes no request.
 */
export function UpdateStatus(): $CancellablePromise<string> {
    return $Call.ByID(2410778633);
}

export function WhisperCatalog(): $CancellablePromise<string> {
    return $Call.ByID(2492386831);
}

export function WhisperInstall(modelID: string): $CancellablePromise<string> {
    return $Call.ByID(477322835, modelID);
}

export function WhisperInstallCancel(jobID: string): $CancellablePromise<string> {
    return $Call.ByID(2313111477, jobID);
}

export function WhisperInstallState(jobID: string): $CancellablePromise<string> {
    return $Call.ByID(288841540, jobID);
}

export function WhisperRemove(modelID: string): $CancellablePromise<string> {
    return $Call.ByID(1246245112, modelID);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
