// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FindingsQuery is FindingsList's filter, sort and page, as the UI sends it. Every field is optional:
 * an empty filter matches everything, an empty sort is chapter order, a zero limit is no limit. New
 * filters are added here as optional fields, so an older UI keeps working.
 */
export class FindingsQuery {
    "analyzer"?: string;
    "category"?: string;
    "severity"?: string;
    "status"?: string;
    "chapterId"?: string;
    "minConfidence"?: number | null;
    "includeNotInLatestRun"?: boolean;

    /**
     * Sort is "chapter" (the default), "time", "confidence" or "severity"; see findings.SortKey.
     */
    "sort"?: string;
    "descending"?: boolean;
    "limit"?: number;
    "offset"?: number;

    /** Creates a new FindingsQuery instance. */
    constructor($$source: Partial<FindingsQuery> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FindingsQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): FindingsQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FindingsQuery($$parsedSource as Partial<FindingsQuery>);
    }
}

/**
 * LineIdentityStampRow is one row of LineIdentityStamp's input: an item GUID, the manuscript entity ID it
 * should carry (a paragraph or chapter ID), and that entity's current text.
 */
export class LineIdentityStampRow {
    "itemGuid": string;
    "lineId": string;
    "text": string;

    /** Creates a new LineIdentityStampRow instance. */
    constructor($$source: Partial<LineIdentityStampRow> = {}) {
        if (!("itemGuid" in $$source)) {
            this["itemGuid"] = "";
        }
        if (!("lineId" in $$source)) {
            this["lineId"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LineIdentityStampRow instance from a string or object.
     */
    static createFrom($$source: any = {}): LineIdentityStampRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LineIdentityStampRow($$parsedSource as Partial<LineIdentityStampRow>);
    }
}

/**
 * TakeReviewScanScope is what the narrator chose to scan: a chapter track, and at most one pickup addition, a pickup
 * track or a time range in project seconds (Q3). The idle job carries the project's saved pickup addition (the
 * TakeReview settings) with no chapter track, for the dialog to offer.
 */
export class TakeReviewScanScope {
    "chapterTrackName": string;
    "pickupTrackName"?: string;
    "pickupRangeStart"?: number | null;
    "pickupRangeEnd"?: number | null;

    /** Creates a new TakeReviewScanScope instance. */
    constructor($$source: Partial<TakeReviewScanScope> = {}) {
        if (!("chapterTrackName" in $$source)) {
            this["chapterTrackName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TakeReviewScanScope instance from a string or object.
     */
    static createFrom($$source: any = {}): TakeReviewScanScope {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TakeReviewScanScope($$parsedSource as Partial<TakeReviewScanScope>);
    }
}
