// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ExportItem is one rendered WAV to master and encode: its place in the eventual package (one of packager.Kind's own
 * values, kept a plain string on the wire so the UI's contract does not depend on a Go enum type) and, for a
 * chapter, its title (packager.Assemble needs it to name the file; ignored for the other kinds).
 */
export class ExportItem {
    "kind": string;
    "title": string;
    "path": string;

    /** Creates a new ExportItem instance. */
    constructor($$source: Partial<ExportItem> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportItem($$parsedSource as Partial<ExportItem>);
    }
}

/**
 * ExportRequest is what ExportStart is asked to master (optionally) and encode.
 */
export class ExportRequest {
    "items": ExportItem[];
    "master": boolean;
    "format": string;

    /** Creates a new ExportRequest instance. */
    constructor($$source: Partial<ExportRequest> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("master" in $$source)) {
            this["master"] = false;
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportRequest {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new ExportRequest($$parsedSource as Partial<ExportRequest>);
    }
}

/**
 * FindingsQuery is FindingsList's filter, sort and page, as the UI sends it. Every field is optional:
 * an empty filter matches everything, an empty sort is chapter order, a zero limit is no limit. New
 * filters are added here as optional fields, so an older UI keeps working.
 */
export class FindingsQuery {
    "analyzer"?: string;
    "category"?: string;
    "severity"?: string;
    "status"?: string;
    "chapterId"?: string;
    "minConfidence"?: number | null;
    "includeNotInLatestRun"?: boolean;

    /**
     * Sort is "chapter" (the default), "time", "confidence" or "severity"; see findings.SortKey.
     */
    "sort"?: string;
    "descending"?: boolean;
    "limit"?: number;
    "offset"?: number;

    /** Creates a new FindingsQuery instance. */
    constructor($$source: Partial<FindingsQuery> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FindingsQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): FindingsQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FindingsQuery($$parsedSource as Partial<FindingsQuery>);
    }
}

/**
 * LineIdentityStampRow is one row of LineIdentityStamp's input: an item GUID, the manuscript entity ID it
 * should carry (a paragraph or chapter ID), and that entity's current text.
 */
export class LineIdentityStampRow {
    "itemGuid": string;
    "lineId": string;
    "text": string;

    /** Creates a new LineIdentityStampRow instance. */
    constructor($$source: Partial<LineIdentityStampRow> = {}) {
        if (!("itemGuid" in $$source)) {
            this["itemGuid"] = "";
        }
        if (!("lineId" in $$source)) {
            this["lineId"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LineIdentityStampRow instance from a string or object.
     */
    static createFrom($$source: any = {}): LineIdentityStampRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LineIdentityStampRow($$parsedSource as Partial<LineIdentityStampRow>);
    }
}

/**
 * PackageItem is one already-encoded file (an ExportJob file's own EncodedPath) ready to package. Kind is one of
 * packager.Kind's own values, kept a plain string on the wire so the UI's contract does not depend on a Go enum type.
 */
export class PackageItem {
    "kind": string;
    "title": string;
    "path": string;

    /** Creates a new PackageItem instance. */
    constructor($$source: Partial<PackageItem> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageItem instance from a string or object.
     */
    static createFrom($$source: any = {}): PackageItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackageItem($$parsedSource as Partial<PackageItem>);
    }
}

/**
 * PackageRequest is what PackageStart is asked to assemble: one profile's book checklist, the encoded items ready,
 * and (once the folder picker answers) where to write it.
 */
export class PackageRequest {
    "profileId": string;
    "profileVersion": string;
    "items": PackageItem[];

    /** Creates a new PackageRequest instance. */
    constructor($$source: Partial<PackageRequest> = {}) {
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("profileVersion" in $$source)) {
            this["profileVersion"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PackageRequest {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField2_0($$parsedSource["items"]);
        }
        return new PackageRequest($$parsedSource as Partial<PackageRequest>);
    }
}

/**
 * TakeReviewScanScope is what the narrator chose to scan: a chapter track, and at most one pickup addition, a pickup
 * track or a time range in project seconds (Q3). The idle job carries the project's saved pickup addition (the
 * TakeReview settings) with no chapter track, for the dialog to offer.
 */
export class TakeReviewScanScope {
    "chapterTrackName": string;
    "pickupTrackName"?: string;
    "pickupRangeStart"?: number | null;
    "pickupRangeEnd"?: number | null;

    /** Creates a new TakeReviewScanScope instance. */
    constructor($$source: Partial<TakeReviewScanScope> = {}) {
        if (!("chapterTrackName" in $$source)) {
            this["chapterTrackName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TakeReviewScanScope instance from a string or object.
     */
    static createFrom($$source: any = {}): TakeReviewScanScope {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TakeReviewScanScope($$parsedSource as Partial<TakeReviewScanScope>);
    }
}

// Private type creation functions
const $$createType0 = ExportItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = PackageItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
