// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Flag is one flag as the read-aloud dialog sends it. WordStart and WordEnd are the flag's words within the paragraph,
 * [WordStart, WordEnd), counted the way the reader splits the text (runs of non-whitespace). An extra covers exactly the one
 * word it was heard before. ScriptStart and ScriptEnd are the event's own chapter word indices, kept only as evidence.
 */
export class Flag {
    "kind": string;
    "paragraphId": string;
    "wordStart": number;
    "wordEnd": number;
    "scriptStart": number;
    "scriptEnd": number;
    "heard": string;

    /**
     * Dismissed is the narrator's call in the dialog's review panel; the host records it as a decision, it never deletes.
     */
    "dismissed": boolean;

    /** Creates a new Flag instance. */
    constructor($$source: Partial<Flag> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("paragraphId" in $$source)) {
            this["paragraphId"] = "";
        }
        if (!("wordStart" in $$source)) {
            this["wordStart"] = 0;
        }
        if (!("wordEnd" in $$source)) {
            this["wordEnd"] = 0;
        }
        if (!("scriptStart" in $$source)) {
            this["scriptStart"] = 0;
        }
        if (!("scriptEnd" in $$source)) {
            this["scriptEnd"] = 0;
        }
        if (!("heard" in $$source)) {
            this["heard"] = "";
        }
        if (!("dismissed" in $$source)) {
            this["dismissed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Flag instance from a string or object.
     */
    static createFrom($$source: any = {}): Flag {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Flag($$parsedSource as Partial<Flag>);
    }
}
