// Writes the generated tables of docs/architecture/model-provenance.md from the five asset catalogs, and checks that they are current.
//
//   node scripts/licenses/models.mjs           rewrite the tables between the markers
//   node scripts/licenses/models.mjs --check   exit 1 when they are out of date (the repo-scripts test runs this in `pnpm check`)
//
// The catalogs (`config/whisper-assets.json`, `tts-assets.json`, `spacy-assets.json`, `moonshine-assets.json`, `dictionary-assets.json`) are
// what the app downloads, so the table cannot disagree with them. What no catalog says (is it fine for a commercial audiobook, and what did
// a person decide) is written by hand in `scripts/licenses/model-review.json`; a catalog artifact with no review row, or a row for an
// artifact that is gone, is an error.

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

import { REPO_ROOT } from '../ci/layout.mjs';

export const BEGIN = '<!-- models:begin (generated by scripts/licenses/models.mjs; edit scripts/licenses/model-review.json, not this table) -->';
export const END = '<!-- models:end -->';
const CATALOGS = [
  ['whisper', 'whisper-assets.json', 'models'],
  ['tts', 'tts-assets.json', 'voices'],
  ['spacy', 'spacy-assets.json', 'models'],
  ['moonshine', 'moonshine-assets.json', 'models'],
  ['dictionary', 'dictionary-assets.json', 'dictionaries'],
];

export function loadCatalogs(configDir) {
  return CATALOGS.flatMap(([kind, file, key]) => (JSON.parse(readFileSync(join(configDir, file), 'utf8'))[key] ?? []).map((item) => ({ ...item, kind })));
}

const artifactKey = (item) => `${item.provider}/${item.id}`;
const cell = (text) => String(text ?? '').replaceAll('|', '\\|').replaceAll('\n', ' ');
const bytes = (value) => value.toLocaleString('en-US');

function size(total) {
  const mebibytes = total / 1024 ** 2;
  return mebibytes >= 1024 ? `${(mebibytes / 1024).toFixed(2)} GiB` : `${mebibytes.toFixed(1)} MiB`;
}

const pinned = (version) => (/^[0-9a-f]{40}$/.test(version) ? version.slice(0, 12) : version);

export function renderTables(items, review) {
  const catalogued = review.catalogued ?? {};
  const missing = items.map(artifactKey).filter((key) => !catalogued[key]);
  if (missing.length) throw new Error(`no review row in scripts/licenses/model-review.json for: ${missing.join(', ')} (record its commercial-use finding and status)`);
  const stale = Object.keys(catalogued).filter((key) => !items.some((item) => artifactKey(item) === key));
  if (stale.length) throw new Error(`scripts/licenses/model-review.json reviews artifacts that are not in a catalog: ${stale.join(', ')}`);

  const lines = ['### Artifacts in the catalogs', '', '| Artifact | Publisher | Licence | Pinned | Download | Commercial use | Status | Note |', '| --- | --- | --- | --- | --- | --- | --- | --- |'];
  for (const item of items) {
    const row = catalogued[artifactKey(item)];
    const total = item.files.reduce((sum, file) => sum + file.size, 0);
    lines.push(
      `| ${artifactKey(item)} | ${cell(item.publisher)} | [${cell(item.license)}](${item.licenseUrl}) | \`${pinned(item.version)}\` | ${size(total)} | ${cell(row.commercialUse)} | ${cell(row.status)} | ${cell(row.note)} |`,
    );
  }
  lines.push('', '### Every file, with the size and SHA-256 the app checks', '', '| Artifact | File | Size (bytes) | SHA-256 |', '| --- | --- | --- | --- |');
  for (const item of items) {
    for (const file of item.files) lines.push(`| ${artifactKey(item)} | \`${cell(file.name)}\` | ${bytes(file.size)} | \`${file.sha256}\` |`);
  }
  lines.push('', '### Not in the catalogs', '', '| Artifact | Source | Licence | Commercial use | Status | Note |', '| --- | --- | --- | --- | --- | --- |');
  for (const item of review.uncatalogued ?? []) {
    lines.push(`| ${cell(item.name)} | ${cell(item.source)} | ${cell(item.license)} | ${cell(item.commercialUse)} | ${cell(item.status)} | ${cell(item.note)} |`);
  }
  return lines.join('\n');
}

export function replaceGenerated(document, generated) {
  const start = document.indexOf(BEGIN);
  const end = document.indexOf(END);
  if (start < 0 || end < start) throw new Error(`the document needs the markers ${BEGIN} and ${END}, in that order`);
  return `${document.slice(0, start + BEGIN.length)}\n${generated}\n${document.slice(end)}`;
}

export function generateDocument(document, items, review) {
  return replaceGenerated(document, renderTables(items, review));
}

const normalise = (text) => text.replace(/\r\n/g, '\n');

export function checkDocument(document, items, review) {
  return normalise(document) === normalise(generateDocument(document, items, review));
}

function main(argv) {
  const path = join(REPO_ROOT, 'docs/architecture/model-provenance.md');
  const document = readFileSync(path, 'utf8');
  const review = JSON.parse(readFileSync(join(REPO_ROOT, 'scripts/licenses/model-review.json'), 'utf8'));
  const items = loadCatalogs(join(REPO_ROOT, 'config'));
  if (argv.includes('--check')) {
    if (checkDocument(document, items, review)) return 0;
    console.error('docs/architecture/model-provenance.md is out of date: run `node scripts/licenses/models.mjs`');
    return 1;
  }
  writeFileSync(path, generateDocument(document, items, review));
  console.log(`wrote ${path}`);
  return 0;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) process.exit(main(process.argv.slice(2)));
