-- Pickup list: import_pickups, export_pickups, next_pickup, resolve_pickup and count_pickups (see
-- docs/architecture/reaper-bridge.md). Project markers named `PICKUP: <body>` (open) and `PICKUP_DONE: <body>`
-- (resolved), reusing the `PREFIX:` marker convention (narration_compare.lua's marker_kind). `<body>` is the note,
-- or `[tag] note` when a tag was given (Open Question 5: generic CSV first, start time, note, optional tag).

local H = require('harness')

local function new_session()
  return H.session({ project_path = H.join(host.tmpdir(), 'Book.rpp') })
end

local function payload(s, name, lines)
  local path = s:path(name)
  H.write_file(path, table.concat(lines, '\n') .. '\n')
  return path
end

-- import_pickups -------------------------------------------------------------------------------------------------

H.test('import_pickups needs a marker API', function()
  local s = new_session()
  s.fake:remove_api('AddProjectMarker2')
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '1.5||First pickup' }))
  H.eq(s:events(), { { 'ERROR', 't1', 'This REAPER version cannot add markers.' } })
end)

H.test('import_pickups reports a missing payload', function()
  local s = new_session()
  s:send('import_pickups', 't1', s:path('missing.txt'))
  H.eq(s:events(), { { 'ERROR', 't1', 'The pickup list was not found.' } })
end)

H.test('import_pickups adds one PICKUP: marker per row in one undo step', function()
  local s = new_session()
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '1.5||First pickup', '9.25||Second pickup' }))
  H.eq(s:events(), { { 'PICKUPS_IMPORTED', 't1', '2', '0', '0' } })
  H.eq(#s.fake.markers, 2)
  H.eq(s.fake.markers[1].name, 'PICKUP: First pickup')
  H.eq(s.fake.markers[1].pos, 1.5)
  H.eq(s.fake.markers[1].is_region, false)
  H.eq(s.fake.markers[2].name, 'PICKUP: Second pickup')
  H.eq(s.fake:undo_labels(), { 'Narration Utils: import pickups' })
  H.eq(s.fake.arrange_updates, 1)
end)

H.test('import_pickups folds a tag into the marker name', function()
  local s = new_session()
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '1.5|narrator|Mispronounced' }))
  H.eq(s.fake.markers[1].name, 'PICKUP: [narrator] Mispronounced')
end)

H.test('import_pickups is idempotent: re-sending the same list adds nothing and opens no undo point', function()
  local s = new_session()
  local path = payload(s, 'p.txt', { '1.5||First pickup', '9.25|tag|Second pickup' })
  s:send('import_pickups', 't1', path)
  s:events()
  s:send('import_pickups', 't2', path)
  H.eq(s:events(), { { 'PICKUPS_IMPORTED', 't2', '0', '2', '0' } })
  H.eq(#s.fake.markers, 2)
  H.eq(#s.fake.undo, 1)
end)

H.test('import_pickups treats an already-resolved pickup as existing, not a new one', function()
  local s = new_session()
  s.fake:insert_marker({ is_region = false, pos = 1.5, rgnend = 0, name = 'PICKUP_DONE: First pickup', color = 0 })
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '1.5||First pickup' }))
  H.eq(s:events(), { { 'PICKUPS_IMPORTED', 't1', '0', '1', '0' } })
  H.eq(#s.fake.markers, 1)
end)

H.test('import_pickups treats a different note at the same time as new, not a duplicate', function()
  local s = new_session()
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '1.5||First pickup', '1.5||Different note' }))
  H.eq(s:events(), { { 'PICKUPS_IMPORTED', 't1', '2', '0', '0' } })
end)

H.test('import_pickups counts malformed rows as invalid and skips blank lines', function()
  local s = new_session()
  local path = payload(s, 'p.txt', { '1.5||Fine', '', 'nonsense', '-1||Negative', '1.5||', '|tag|No start' })
  s:send('import_pickups', 't1', path)
  H.eq(s:events(), { { 'PICKUPS_IMPORTED', 't1', '1', '0', '4' } })
end)

H.test('import_pickups treats the same note beyond the duplicate tolerance as a new pickup, not a duplicate', function()
  local s = new_session()
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '1||Same note', '4||Same note' }))
  H.eq(s:events(), { { 'PICKUPS_IMPORTED', 't1', '2', '0', '0' } })
  H.eq(#s.fake.markers, 2)
end)

H.test('import_pickups reads a payload with Windows line endings', function()
  local s = new_session()
  local path = s:path('crlf.txt')
  H.write_file(path, '1.5||First pickup\r\n')
  s:send('import_pickups', 't1', path)
  H.eq(s.fake.markers[1].name, 'PICKUP: First pickup')
end)

H.test('import_pickups keeps a pipe in the note', function()
  local s = new_session()
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '1.5||Either | or' }))
  H.eq(s.fake.markers[1].name, 'PICKUP: Either | or')
end)

-- export_pickups -------------------------------------------------------------------------------------------------

H.test('export_pickups reports an output file it cannot write', function()
  local s = new_session()
  s:send('export_pickups', 't1', s:path('no-such-folder') .. package.config:sub(1, 1) .. 'out.txt')
  H.eq(s:events(), { { 'ERROR', 't1', 'Could not write the pickup list.' } })
end)

H.test('export_pickups writes every open pickup as start|tag|note and skips resolved ones', function()
  local s = new_session()
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '1.5||First pickup', '9.25|narrator|Second pickup' }))
  s:events()
  s.fake:insert_marker({ is_region = false, pos = 20, rgnend = 0, name = 'PICKUP_DONE: Already fixed', color = 0 })
  local out = s:path('out.txt')
  s:send('export_pickups', 't2', out)
  H.eq(s:events(), { { 'PICKUPS_EXPORTED', 't2', out, '2' } })
  H.eq(H.read_text(out), '1.500000||First pickup\n9.250000|narrator|Second pickup\n')
end)

H.test('export_pickups writes nothing when there are no pickups', function()
  local s = new_session()
  local out = s:path('out.txt')
  s:send('export_pickups', 't1', out)
  H.eq(s:events(), { { 'PICKUPS_EXPORTED', 't1', out, '0' } })
  H.eq(H.read_text(out), '')
end)

H.test('export_pickups ignores markers that are not pickups', function()
  local s = new_session()
  s.fake:insert_marker({ is_region = false, pos = 0, rgnend = 0, name = 'COMPARE: something', color = 0 })
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '5||Real pickup' }))
  s:events()
  local out = s:path('out.txt')
  s:send('export_pickups', 't2', out)
  H.eq(s:events(), { { 'PICKUPS_EXPORTED', 't2', out, '1' } })
  H.eq(H.read_text(out), '5.000000||Real pickup\n')
end)

H.test('export_pickups touches nothing in the project', function()
  local s = new_session()
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '1.5||First pickup' }))
  s:events()
  s:send('export_pickups', 't2', s:path('out.txt'))
  H.eq(#s.fake.undo, 1)
end)

H.test('a pickup list round-trips: export after import reproduces the same rows', function()
  local s = new_session()
  local original = { '1.5||First pickup', '9.25|narrator|Second pickup', '30|proofer|Third "one"' }
  s:send('import_pickups', 't1', payload(s, 'p.txt', original))
  s:events()
  local out = s:path('out.txt')
  s:send('export_pickups', 't2', out)
  local reimport = s:path('reimport.txt')
  H.write_file(reimport, H.read_text(out))
  s:send('import_pickups', 't3', reimport)
  H.eq(s:events(), { { 'PICKUPS_EXPORTED', 't2', out, '3' }, { 'PICKUPS_IMPORTED', 't3', '0', '3', '0' } })
end)

-- next_pickup ----------------------------------------------------------------------------------------------------

H.test('next_pickup reports when none remain', function()
  local s = new_session()
  s:send('next_pickup', 't1')
  H.eq(s:events(), { { 'ERROR', 't1', 'No pickups remain.' } })
end)

H.test('next_pickup jumps to the nearest pickup after the cursor', function()
  local s = new_session()
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '1.5||First', '9.25|tag|Second', '30||Third' }))
  s:events()
  s.fake.cursor = 5
  s:send('next_pickup', 't2')
  H.eq(s:events(), { { 'PICKUP_NEXT', 't2', '9.25', 'tag', 'Second' } })
  H.eq(s.fake.cursor, 9.25)
  H.eq(s.fake.cursor_moveview, true)
end)

H.test('next_pickup wraps to the earliest pickup when the cursor is past all of them', function()
  local s = new_session()
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '1.5||First', '9.25||Second' }))
  s:events()
  s.fake.cursor = 100
  s:send('next_pickup', 't2')
  H.eq(s:events()[1], { 'PICKUP_NEXT', 't2', '1.5', '', 'First' })
end)

H.test('next_pickup ignores markers that are not pickups even when one sits between the cursor and the real pickup', function()
  local s = new_session()
  s.fake:insert_marker({ is_region = false, pos = 2, rgnend = 0, name = 'COMPARE: something', color = 0 })
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '5||Real pickup' }))
  s:events()
  s:send('next_pickup', 't2')
  H.eq(s:events(), { { 'PICKUP_NEXT', 't2', '5', '', 'Real pickup' } })
end)

H.test('next_pickup skips resolved pickups', function()
  local s = new_session()
  s.fake:insert_marker({ is_region = false, pos = 1.5, rgnend = 0, name = 'PICKUP_DONE: Fixed', color = 0 })
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '9.25||Still open' }))
  s:events()
  s:send('next_pickup', 't2')
  H.eq(s:events(), { { 'PICKUP_NEXT', 't2', '9.25', '', 'Still open' } })
end)

H.test('next_pickup does not select a media item; a marker has none', function()
  local s, track = new_session(), nil
  track = s.fake:add_track('Narrator')
  local item = s.fake:add_item(track, { guid = '{AAAAAAAA-0000-4000-8000-000000000001}', selected = true })
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '9.25||Open' }))
  s:events()
  s:send('next_pickup', 't2')
  H.eq(item.selected, true)
end)

-- resolve_pickup -------------------------------------------------------------------------------------------------

H.test('resolve_pickup needs an API to rename a marker', function()
  local s = new_session()
  s.fake:remove_api('SetProjectMarker3')
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '9.25||Open' }))
  s:events()
  s:send('resolve_pickup', 't2', '9.25')
  H.eq(s:events(), { { 'ERROR', 't2', 'This REAPER version cannot rename markers.' } })
end)

H.test('resolve_pickup needs a position', function()
  local s = new_session()
  s:send('resolve_pickup', 't1', '')
  H.eq(s:events(), { { 'ERROR', 't1', 'Send a pickup position to resolve.' } })
end)

H.test('resolve_pickup reports when nothing is found near that position', function()
  local s = new_session()
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '9.25||Open' }))
  s:events()
  s:send('resolve_pickup', 't2', '50')
  H.eq(s:events(), { { 'ERROR', 't2', 'No open pickup was found at that position.' } })
  H.eq(s.fake.markers[1].name, 'PICKUP: Open')
end)

H.test('resolve_pickup renames the nearest open pickup to PICKUP_DONE, keeping its body, in one undo step', function()
  local s = new_session()
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '9.25|narrator|Open one' }))
  s:events()
  s:send('resolve_pickup', 't2', '9.3')
  H.eq(s:events(), { { 'PICKUP_RESOLVED', 't2', '9.25', 'narrator', 'Open one' } })
  H.eq(s.fake.markers[1].name, 'PICKUP_DONE: [narrator] Open one')
  H.eq(s.fake.markers[1].pos, 9.25)
  H.eq(s.fake:undo_labels(), { 'Narration Utils: import pickups', 'Narration Utils: resolve pickup' })
end)

H.test('resolve_pickup is idempotent: resolving an already-done pickup finds no open match', function()
  local s = new_session()
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '9.25||Open one' }))
  s:events()
  s:send('resolve_pickup', 't2', '9.25')
  s:events()
  s:send('resolve_pickup', 't3', '9.25')
  H.eq(s:events(), { { 'ERROR', 't3', 'No open pickup was found at that position.' } })
end)

H.test('resolve_pickup picks the closest pickup within tolerance when two are near', function()
  local s = new_session()
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '9.20||Near', '9.30||Far' }))
  s:events()
  s:send('resolve_pickup', 't2', '9.22')
  H.eq(s:events(), { { 'PICKUP_RESOLVED', 't2', '9.2', '', 'Near' } })
end)

-- count_pickups --------------------------------------------------------------------------------------------------

H.test('count_pickups reports zero of zero for an empty project', function()
  local s = new_session()
  s:send('count_pickups', 't1')
  H.eq(s:events(), { { 'PICKUPS_COUNTED', 't1', '0', '0' } })
end)

H.test('count_pickups reports remaining and total, and touches nothing', function()
  local s = new_session()
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '1||A', '2||B', '3||C' }))
  s:events()
  s:send('resolve_pickup', 't2', '2')
  s:events()
  s:send('count_pickups', 't3')
  H.eq(s:events(), { { 'PICKUPS_COUNTED', 't3', '2', '3' } })
  H.eq(#s.fake.undo, 2)
end)

H.test('count_pickups ignores markers and regions that are not pickups', function()
  local s = new_session()
  s.fake:insert_marker({ is_region = false, pos = 5, rgnend = 0, name = 'COMPARE: something', color = 0 })
  s.fake:add_region(0, 10, 'Chapter 1')
  s:send('import_pickups', 't1', payload(s, 'p.txt', { '1||A' }))
  s:events()
  s:send('count_pickups', 't2')
  H.eq(s:events(), { { 'PICKUPS_COUNTED', 't2', '1', '1' } })
end)
