// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {liveflags} from '../models';

export function AssetsInstall(arg1:string,arg2:string):Promise<string>;

export function AssetsInstallCancel(arg1:string):Promise<string>;

export function AssetsInstallState(arg1:string):Promise<string>;

export function AssetsList():Promise<string>;

export function AssetsRemove(arg1:string,arg2:string):Promise<string>;

export function AssetsVerify(arg1:string,arg2:string):Promise<string>;

export function Bootstrap():Promise<Record<string, any>>;

export function ChapterSuggestion():Promise<string>;

export function ChapterTagsEmbed(arg1:string):Promise<string>;

export function ChapterTagsPreview():Promise<string>;

export function ChapterTrackMapClear(arg1:string):Promise<string>;

export function ChapterTrackMapConfirm(arg1:string,arg2:string):Promise<string>;

export function ChapterTrackMapList():Promise<string>;

export function ChapterTrackMatch(arg1:string):Promise<string>;

export function CoverageCancel():Promise<string>;

export function CoverageResult(arg1:string):Promise<string>;

export function CoverageStart(arg1:string):Promise<string>;

export function CoverageState():Promise<string>;

export function CreditsChapterAnnouncements(arg1:string):Promise<string>;

export function CreditsDeleteTemplate(arg1:string):Promise<string>;

export function CreditsDuplicateTemplate(arg1:string):Promise<string>;

export function CreditsPreview(arg1:string):Promise<string>;

export function CreditsProjectValues():Promise<string>;

export function CreditsRetailSample():Promise<string>;

export function CreditsSaveProjectValues(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string):Promise<string>;

export function CreditsSaveRetailSample(arg1:string,arg2:string):Promise<string>;

export function CreditsSaveTemplate(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CreditsTemplates():Promise<string>;

export function DawCatalogList():Promise<string>;

export function DawCatalogOpenDownloadPage(arg1:string):Promise<string>;

export function DawLaunch():Promise<string>;

export function GuideBuild(arg1:boolean):Promise<string>;

export function GuideBuildState():Promise<string>;

export function GuideCreate(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function GuideDelete(arg1:string):Promise<string>;

export function GuideEdit(arg1:string,arg2:Record<string, string>):Promise<string>;

export function GuideEntities():Promise<string>;

export function GuideMerge(arg1:string,arg2:string):Promise<string>;

export function GuidePreview(arg1:string,arg2:any):Promise<string>;

export function GuidePronounce(arg1:string,arg2:any,arg3:string):Promise<string>;

export function GuideRelate(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GuideRescan(arg1:string):Promise<string>;

export function GuideSetLocked(arg1:string,arg2:boolean):Promise<string>;

export function GuideUnrelate(arg1:string,arg2:string,arg3:string):Promise<string>;

export function LineIdentityRead():Promise<string>;

export function LineIdentityStamp(arg1:Array<main.LineIdentityStampRow>,arg2:boolean):Promise<string>;

export function LineIdentityState():Promise<string>;

export function ManuscriptBeginImport(arg1:string):Promise<string>;

export function ManuscriptChapters():Promise<string>;

export function ManuscriptClearProjectData(arg1:boolean):Promise<string>;

export function ManuscriptCreateBookmark(arg1:Record<string, any>):Promise<string>;

export function ManuscriptCreateNote(arg1:string,arg2:string,arg3:string,arg4:string,arg5:any,arg6:any):Promise<string>;

export function ManuscriptDeleteBookmark(arg1:string):Promise<string>;

export function ManuscriptDeleteNote(arg1:string):Promise<string>;

export function ManuscriptImportCancel(arg1:string):Promise<string>;

export function ManuscriptImportCommit(arg1:string,arg2:boolean,arg3:Record<string, string>,arg4:Array<string>,arg5:Record<string, boolean>):Promise<string>;

export function ManuscriptImportPreview(arg1:string,arg2:number):Promise<string>;

export function ManuscriptImportState(arg1:string):Promise<string>;

export function ManuscriptNotes(arg1:string):Promise<string>;

export function ManuscriptParagraphs(arg1:string):Promise<string>;

export function ManuscriptReader():Promise<string>;

export function ManuscriptReaderState():Promise<string>;

export function ManuscriptSaveReaderState(arg1:string,arg2:any,arg3:Array<string>):Promise<string>;

export function ManuscriptSearch(arg1:string):Promise<string>;

export function ManuscriptSelectFile():Promise<string>;

export function ManuscriptSetChapterStatus(arg1:string,arg2:string):Promise<string>;

export function PickupsCount():Promise<string>;

export function PickupsExport():Promise<string>;

export function PickupsImport(arg1:string):Promise<string>;

export function PickupsNext():Promise<string>;

export function PickupsResolve(arg1:number):Promise<string>;

export function PickupsState():Promise<string>;

export function ProjectCreateIn(arg1:string,arg2:string):Promise<string>;

export function ProjectLinkDawFile():Promise<string>;

export function ProjectRecents():Promise<string>;

export function ProjectRemoveRecent(arg1:string):Promise<string>;

export function ProjectSelectFolder():Promise<string>;

export function ProjectStateChangedSince(arg1:number,arg2:number):Promise<string>;

export function ProjectStateCheck():Promise<string>;

export function ProjectStateState():Promise<string>;

export function ProjectSwitch(arg1:string,arg2:string):Promise<string>;

export function Ready():Promise<Record<string, any>>;

export function RenderConfigConfigure(arg1:string):Promise<string>;

export function RenderConfigState():Promise<string>;

export function RenderConfigSuggestFolder():Promise<string>;

export function SystemNotify(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SystemReportDiagnostic(arg1:string,arg2:string):Promise<string>;

export function SystemSaveSettings(arg1:string,arg2:string,arg3:Record<string, any>):Promise<string>;

export function SystemSettingsForScope(arg1:string):Promise<string>;

export function TakeReviewCreateTake(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<string>;

export function TakeReviewFindings(arg1:string):Promise<string>;

export function TakeReviewScan(arg1:string):Promise<string>;

export function TeleprompterDevices():Promise<string>;

export function TeleprompterLocate(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TeleprompterSaveFlags(arg1:string,arg2:Array<liveflags.Flag>):Promise<string>;

export function TeleprompterSeek(arg1:number):Promise<string>;

export function TeleprompterStart(arg1:Record<string, string>):Promise<string>;

export function TeleprompterState():Promise<string>;

export function TeleprompterStop():Promise<string>;

export function TracksDiscover():Promise<string>;

export function TracksList():Promise<string>;

export function TracksSelect(arg1:string):Promise<string>;

export function TranscriptAddEquivalence(arg1:string):Promise<string>;

export function TranscriptCancel():Promise<string>;

export function TranscriptExportMarkers():Promise<string>;

export function TranscriptHints():Promise<string>;

export function TranscriptJump(arg1:string):Promise<string>;

export function TranscriptLastCompleted():Promise<string>;

export function TranscriptReset():Promise<string>;

export function TranscriptSaveHints(arg1:Array<string>):Promise<string>;

export function TranscriptStart(arg1:Record<string, string>):Promise<string>;

export function TranscriptSuggestHints():Promise<string>;

export function TtsCatalog():Promise<string>;

export function TtsInstall(arg1:string):Promise<string>;

export function TtsInstallCancel(arg1:string):Promise<string>;

export function TtsInstallState(arg1:string):Promise<string>;

export function TtsRemove(arg1:string):Promise<string>;

export function UpdateCheck():Promise<string>;

export function UpdateDownload():Promise<string>;

export function UpdateInstall(arg1:string):Promise<string>;

export function UpdateJobCancel(arg1:string):Promise<string>;

export function UpdateJobState(arg1:string):Promise<string>;

export function UpdateOpenNotes():Promise<string>;

export function UpdateShowDownload():Promise<string>;

export function UpdateStatus():Promise<string>;

export function WhisperCatalog():Promise<string>;

export function WhisperInstall(arg1:string):Promise<string>;

export function WhisperInstallCancel(arg1:string):Promise<string>;

export function WhisperInstallState(arg1:string):Promise<string>;

export function WhisperRemove(arg1:string):Promise<string>;
