// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssetsInstall(arg1, arg2) {
  return window['go']['main']['Host']['AssetsInstall'](arg1, arg2);
}

export function AssetsInstallCancel(arg1) {
  return window['go']['main']['Host']['AssetsInstallCancel'](arg1);
}

export function AssetsInstallState(arg1) {
  return window['go']['main']['Host']['AssetsInstallState'](arg1);
}

export function AssetsList() {
  return window['go']['main']['Host']['AssetsList']();
}

export function AssetsRemove(arg1, arg2) {
  return window['go']['main']['Host']['AssetsRemove'](arg1, arg2);
}

export function AssetsVerify(arg1, arg2) {
  return window['go']['main']['Host']['AssetsVerify'](arg1, arg2);
}

export function Bootstrap() {
  return window['go']['main']['Host']['Bootstrap']();
}

export function ChapterTagsEmbed(arg1) {
  return window['go']['main']['Host']['ChapterTagsEmbed'](arg1);
}

export function ChapterTagsPreview() {
  return window['go']['main']['Host']['ChapterTagsPreview']();
}

export function ChapterTrackMapClear(arg1) {
  return window['go']['main']['Host']['ChapterTrackMapClear'](arg1);
}

export function ChapterTrackMapConfirm(arg1, arg2) {
  return window['go']['main']['Host']['ChapterTrackMapConfirm'](arg1, arg2);
}

export function ChapterTrackMapList() {
  return window['go']['main']['Host']['ChapterTrackMapList']();
}

export function ChapterTrackMatch(arg1) {
  return window['go']['main']['Host']['ChapterTrackMatch'](arg1);
}

export function CoverageCancel() {
  return window['go']['main']['Host']['CoverageCancel']();
}

export function CoverageResult(arg1) {
  return window['go']['main']['Host']['CoverageResult'](arg1);
}

export function CoverageStart(arg1) {
  return window['go']['main']['Host']['CoverageStart'](arg1);
}

export function CoverageState() {
  return window['go']['main']['Host']['CoverageState']();
}

export function CreditsDeleteTemplate(arg1) {
  return window['go']['main']['Host']['CreditsDeleteTemplate'](arg1);
}

export function CreditsDuplicateTemplate(arg1) {
  return window['go']['main']['Host']['CreditsDuplicateTemplate'](arg1);
}

export function CreditsPreview(arg1) {
  return window['go']['main']['Host']['CreditsPreview'](arg1);
}

export function CreditsProjectValues() {
  return window['go']['main']['Host']['CreditsProjectValues']();
}

export function CreditsSaveProjectValues(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['Host']['CreditsSaveProjectValues'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function CreditsSaveTemplate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Host']['CreditsSaveTemplate'](arg1, arg2, arg3, arg4);
}

export function CreditsTemplates() {
  return window['go']['main']['Host']['CreditsTemplates']();
}

export function DawCatalogList() {
  return window['go']['main']['Host']['DawCatalogList']();
}

export function DawCatalogOpenDownloadPage(arg1) {
  return window['go']['main']['Host']['DawCatalogOpenDownloadPage'](arg1);
}

export function DawLaunch() {
  return window['go']['main']['Host']['DawLaunch']();
}

export function GuideBuild(arg1) {
  return window['go']['main']['Host']['GuideBuild'](arg1);
}

export function GuideBuildState() {
  return window['go']['main']['Host']['GuideBuildState']();
}

export function GuideCreate(arg1, arg2, arg3) {
  return window['go']['main']['Host']['GuideCreate'](arg1, arg2, arg3);
}

export function GuideDelete(arg1) {
  return window['go']['main']['Host']['GuideDelete'](arg1);
}

export function GuideEdit(arg1, arg2) {
  return window['go']['main']['Host']['GuideEdit'](arg1, arg2);
}

export function GuideEntities() {
  return window['go']['main']['Host']['GuideEntities']();
}

export function GuideMerge(arg1, arg2) {
  return window['go']['main']['Host']['GuideMerge'](arg1, arg2);
}

export function GuidePreview(arg1, arg2) {
  return window['go']['main']['Host']['GuidePreview'](arg1, arg2);
}

export function GuidePronounce(arg1, arg2, arg3) {
  return window['go']['main']['Host']['GuidePronounce'](arg1, arg2, arg3);
}

export function GuideRelate(arg1, arg2, arg3) {
  return window['go']['main']['Host']['GuideRelate'](arg1, arg2, arg3);
}

export function GuideRescan(arg1) {
  return window['go']['main']['Host']['GuideRescan'](arg1);
}

export function GuideSetLocked(arg1, arg2) {
  return window['go']['main']['Host']['GuideSetLocked'](arg1, arg2);
}

export function GuideUnrelate(arg1, arg2, arg3) {
  return window['go']['main']['Host']['GuideUnrelate'](arg1, arg2, arg3);
}

export function LineIdentityRead() {
  return window['go']['main']['Host']['LineIdentityRead']();
}

export function LineIdentityStamp(arg1, arg2) {
  return window['go']['main']['Host']['LineIdentityStamp'](arg1, arg2);
}

export function LineIdentityState() {
  return window['go']['main']['Host']['LineIdentityState']();
}

export function ManuscriptBeginImport(arg1) {
  return window['go']['main']['Host']['ManuscriptBeginImport'](arg1);
}

export function ManuscriptChapters() {
  return window['go']['main']['Host']['ManuscriptChapters']();
}

export function ManuscriptClearProjectData(arg1) {
  return window['go']['main']['Host']['ManuscriptClearProjectData'](arg1);
}

export function ManuscriptCreateBookmark(arg1) {
  return window['go']['main']['Host']['ManuscriptCreateBookmark'](arg1);
}

export function ManuscriptCreateNote(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['Host']['ManuscriptCreateNote'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ManuscriptDeleteBookmark(arg1) {
  return window['go']['main']['Host']['ManuscriptDeleteBookmark'](arg1);
}

export function ManuscriptDeleteNote(arg1) {
  return window['go']['main']['Host']['ManuscriptDeleteNote'](arg1);
}

export function ManuscriptImportCancel(arg1) {
  return window['go']['main']['Host']['ManuscriptImportCancel'](arg1);
}

export function ManuscriptImportCommit(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Host']['ManuscriptImportCommit'](arg1, arg2, arg3, arg4);
}

export function ManuscriptImportPreview(arg1, arg2) {
  return window['go']['main']['Host']['ManuscriptImportPreview'](arg1, arg2);
}

export function ManuscriptImportState(arg1) {
  return window['go']['main']['Host']['ManuscriptImportState'](arg1);
}

export function ManuscriptNotes(arg1) {
  return window['go']['main']['Host']['ManuscriptNotes'](arg1);
}

export function ManuscriptParagraphs(arg1) {
  return window['go']['main']['Host']['ManuscriptParagraphs'](arg1);
}

export function ManuscriptReader() {
  return window['go']['main']['Host']['ManuscriptReader']();
}

export function ManuscriptReaderState() {
  return window['go']['main']['Host']['ManuscriptReaderState']();
}

export function ManuscriptSaveReaderState(arg1, arg2, arg3) {
  return window['go']['main']['Host']['ManuscriptSaveReaderState'](arg1, arg2, arg3);
}

export function ManuscriptSearch(arg1) {
  return window['go']['main']['Host']['ManuscriptSearch'](arg1);
}

export function ManuscriptSelectFile() {
  return window['go']['main']['Host']['ManuscriptSelectFile']();
}

export function ManuscriptSetChapterStatus(arg1, arg2) {
  return window['go']['main']['Host']['ManuscriptSetChapterStatus'](arg1, arg2);
}

export function PickupsCount() {
  return window['go']['main']['Host']['PickupsCount']();
}

export function PickupsExport() {
  return window['go']['main']['Host']['PickupsExport']();
}

export function PickupsImport(arg1) {
  return window['go']['main']['Host']['PickupsImport'](arg1);
}

export function PickupsNext() {
  return window['go']['main']['Host']['PickupsNext']();
}

export function PickupsResolve(arg1) {
  return window['go']['main']['Host']['PickupsResolve'](arg1);
}

export function PickupsState() {
  return window['go']['main']['Host']['PickupsState']();
}

export function ProjectCreateIn(arg1, arg2) {
  return window['go']['main']['Host']['ProjectCreateIn'](arg1, arg2);
}

export function ProjectLinkDawFile() {
  return window['go']['main']['Host']['ProjectLinkDawFile']();
}

export function ProjectRecents() {
  return window['go']['main']['Host']['ProjectRecents']();
}

export function ProjectRemoveRecent(arg1) {
  return window['go']['main']['Host']['ProjectRemoveRecent'](arg1);
}

export function ProjectSelectFolder() {
  return window['go']['main']['Host']['ProjectSelectFolder']();
}

export function ProjectStateChangedSince(arg1, arg2) {
  return window['go']['main']['Host']['ProjectStateChangedSince'](arg1, arg2);
}

export function ProjectStateCheck() {
  return window['go']['main']['Host']['ProjectStateCheck']();
}

export function ProjectStateState() {
  return window['go']['main']['Host']['ProjectStateState']();
}

export function ProjectSwitch(arg1, arg2) {
  return window['go']['main']['Host']['ProjectSwitch'](arg1, arg2);
}

export function Ready() {
  return window['go']['main']['Host']['Ready']();
}

export function RenderConfigConfigure(arg1) {
  return window['go']['main']['Host']['RenderConfigConfigure'](arg1);
}

export function RenderConfigState() {
  return window['go']['main']['Host']['RenderConfigState']();
}

export function RenderConfigSuggestFolder() {
  return window['go']['main']['Host']['RenderConfigSuggestFolder']();
}

export function SystemNotify(arg1, arg2, arg3) {
  return window['go']['main']['Host']['SystemNotify'](arg1, arg2, arg3);
}

export function SystemReportDiagnostic(arg1, arg2) {
  return window['go']['main']['Host']['SystemReportDiagnostic'](arg1, arg2);
}

export function SystemSaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['Host']['SystemSaveSettings'](arg1, arg2, arg3);
}

export function SystemSettingsForScope(arg1) {
  return window['go']['main']['Host']['SystemSettingsForScope'](arg1);
}

export function TakeReviewCreateTake(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['Host']['TakeReviewCreateTake'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function TakeReviewFindings(arg1) {
  return window['go']['main']['Host']['TakeReviewFindings'](arg1);
}

export function TakeReviewScan(arg1) {
  return window['go']['main']['Host']['TakeReviewScan'](arg1);
}

export function TeleprompterDevices() {
  return window['go']['main']['Host']['TeleprompterDevices']();
}

export function TeleprompterSeek(arg1) {
  return window['go']['main']['Host']['TeleprompterSeek'](arg1);
}

export function TeleprompterStart(arg1) {
  return window['go']['main']['Host']['TeleprompterStart'](arg1);
}

export function TeleprompterState() {
  return window['go']['main']['Host']['TeleprompterState']();
}

export function TeleprompterStop() {
  return window['go']['main']['Host']['TeleprompterStop']();
}

export function TracksDiscover() {
  return window['go']['main']['Host']['TracksDiscover']();
}

export function TracksList() {
  return window['go']['main']['Host']['TracksList']();
}

export function TracksSelect(arg1) {
  return window['go']['main']['Host']['TracksSelect'](arg1);
}

export function TranscriptAddEquivalence(arg1) {
  return window['go']['main']['Host']['TranscriptAddEquivalence'](arg1);
}

export function TranscriptCancel() {
  return window['go']['main']['Host']['TranscriptCancel']();
}

export function TranscriptExportMarkers() {
  return window['go']['main']['Host']['TranscriptExportMarkers']();
}

export function TranscriptHints() {
  return window['go']['main']['Host']['TranscriptHints']();
}

export function TranscriptJump(arg1) {
  return window['go']['main']['Host']['TranscriptJump'](arg1);
}

export function TranscriptLastCompleted() {
  return window['go']['main']['Host']['TranscriptLastCompleted']();
}

export function TranscriptReset() {
  return window['go']['main']['Host']['TranscriptReset']();
}

export function TranscriptSaveHints(arg1) {
  return window['go']['main']['Host']['TranscriptSaveHints'](arg1);
}

export function TranscriptStart(arg1) {
  return window['go']['main']['Host']['TranscriptStart'](arg1);
}

export function TranscriptSuggestHints() {
  return window['go']['main']['Host']['TranscriptSuggestHints']();
}

export function TtsCatalog() {
  return window['go']['main']['Host']['TtsCatalog']();
}

export function TtsInstall(arg1) {
  return window['go']['main']['Host']['TtsInstall'](arg1);
}

export function TtsInstallCancel(arg1) {
  return window['go']['main']['Host']['TtsInstallCancel'](arg1);
}

export function TtsInstallState(arg1) {
  return window['go']['main']['Host']['TtsInstallState'](arg1);
}

export function TtsRemove(arg1) {
  return window['go']['main']['Host']['TtsRemove'](arg1);
}

export function UpdateCheck() {
  return window['go']['main']['Host']['UpdateCheck']();
}

export function UpdateDownload() {
  return window['go']['main']['Host']['UpdateDownload']();
}

export function UpdateInstall(arg1) {
  return window['go']['main']['Host']['UpdateInstall'](arg1);
}

export function UpdateJobCancel(arg1) {
  return window['go']['main']['Host']['UpdateJobCancel'](arg1);
}

export function UpdateJobState(arg1) {
  return window['go']['main']['Host']['UpdateJobState'](arg1);
}

export function UpdateOpenNotes() {
  return window['go']['main']['Host']['UpdateOpenNotes']();
}

export function UpdateShowDownload() {
  return window['go']['main']['Host']['UpdateShowDownload']();
}

export function UpdateStatus() {
  return window['go']['main']['Host']['UpdateStatus']();
}

export function WhisperCatalog() {
  return window['go']['main']['Host']['WhisperCatalog']();
}

export function WhisperInstall(arg1) {
  return window['go']['main']['Host']['WhisperInstall'](arg1);
}

export function WhisperInstallCancel(arg1) {
  return window['go']['main']['Host']['WhisperInstallCancel'](arg1);
}

export function WhisperInstallState(arg1) {
  return window['go']['main']['Host']['WhisperInstallState'](arg1);
}

export function WhisperRemove(arg1) {
  return window['go']['main']['Host']['WhisperRemove'](arg1);
}
