name: Create unsigned beta
on: { workflow_dispatch: {}, push: { branches: [main] } }
permissions: { contents: read }
concurrency:
  group: prerelease-${{ github.ref }}
  cancel-in-progress: false
jobs:
  quality:
    uses: ./.github/workflows/_quality.yml
  package:
    needs: quality
    uses: ./.github/workflows/_build-native.yml
    with:
      upload: true
      artifact-prefix: unsigned-beta
